### ISSUE TITLE
[New Integration] Jamf Pro

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#10026]
## Description
This is a new security integration with Jamf Pro. Jamf Pro is a device management tool for Apple devices that enables organizations to efficiently manage and secure their entire Apple ecosystem at scale.

We would like to enable users to:
- Detect policy violations on endpoints, such as unauthorized software installations or configuration changes.
- Take action on detected threats, including tasks like isolating compromised devices or enforcing policies remotely.
- Use Jamf Pro data in compliance reporting to ensure all Apple devices meet regulatory requirements and internal security policies.
- Track and audit device compliance over time to support regulatory audits and assessments.
The scope of this integration includes both event ingestion from Jamf Pro, plus inventory information (outlined [here](https://learn.jamf.com/en-US/bundle/jamf-pro-security-overview/page/Data_Collection.html)) ingested via our Entity Analytics input.

References:
- [Jamf Pro Overview](https://www.youtube.com/watch?v=ZW5nfcb-u3M)
- [Jamf Pro Reporting Solution Series](https://www.youtube.com/watch?v=4tsV-wZE6aw&t=18s)

## Dashboard
The dashboard(s) should help a security analyst quickly answer questions about security incidents, compliance monitoring, user activity, and software management.

For a quick win, we can create the dashboard found here: [Creating a dashboard for Jamf Pro Data in Splunk](https://learn.jamf.com/en-US/bundle/technical-paper-splunk-current/page/Creating_a_Dashboard_for_Jamf_Pro_Data.html). The link contains detailed information on how to create a dashboard in Splunk using imported computer and mobile device data, including the following examples which can be taken as inspiration:

### Total Number of macOS Computers
- Retrieve a list of all computers to count the total number of macOS devices.

### Number of macOS Computers by Hardware Model and Category
- Retrieve detailed information about each computer, including hardware model and category, to categorize and count macOS computers.

### Remote Managed Computers
- Retrieve information about the management status of computers to identify which ones are remotely managed.

### Location Based on Reported IP Address
- Fetch computer inventory data, including IP addresses, to determine the location of devices.

### Capabilities, Supervision, and Enrollment Types
- Retrieve extension attributes data to understand device capabilities, supervision status, and enrollment types such as automated enrollment or user-approved MDM.

### Timeseries Events Like Date Device Last Enrolled and Days Since Last Check-In
- Retrieve historical data on computers to track the date of the last enrollment and calculate the days since the last check-in.

### Acceptance Criteria
- [ ] Provides insights into security incidents, compliance monitoring, user activity, and software management.
- [ ] Data is accurately retrieved from all specified endpoints and displayed correctly in the dashboard.
- [ ] Handles the scale of the organization’s Apple ecosystem without performance degradation.
- [ ] Enables security analysts to take immediate action on detected threats and policy violations.
- [ ] Dashboard is intuitive and easy to use for security analysts and system administrators.

## Architecture
Please refer to the [Jamf Pro API Documentation](https://developer.jamf.com/jamf-pro/reference/jamf-pro-api). 

Additionally, there is valuable information shared by the Jamf folks in the Jamf Pro Splunkbase [app](https://docs.jamf.com/10.16.0/jamf-pro/administrator-guide/Advanced_Computer_Searches.html), copied below.

### Advanced Computer and Mobile Search

The Computers and Mobile Devices tabs use a specific Jamf Pro endpoint referred to as Advanced Computer Searches. The power of these searches lies in the Criteria section, which allows you to narrow your selection of devices. For example, you can collect data only on managed devices, ensuring you don't include devices no longer under your responsibility. You can also control the data that goes into the Splunk engine using the Display section, allowing you to reduce logging to only the values you want or exclude Personally Identifiable Information.

To use these features, highlight the Computer or Mobile Device tab and then enter the name of the Advanced Search in the Custom URL field.

Learn more here:
- [Advanced Computer Searches](https://docs.jamf.com/10.16.0/jamf-pro/administrator-guide/Advanced_Computer_Searches.html)

### Custom API Endpoints

Custom API endpoints allow you to collect information from Jamf Pro by integrating directly with the API. Below is a list of common endpoints that you may want to collect data from. Copy-paste these code paths into the custom fields to get the described data or go to the Jamf API page found here:

### Structure

The API endpoints function such that if you call any of the JSSResource endpoints, it will take that call and then iterate across all objects that return. For example, if you call `/JSSResource/computers/`, it will call all computers. If you enter a NAME or ID field in the custom URL, it will only call that specific object. For example, `/JSSResource/computers/id/10` returns only the computer with the JSS_ID equal to 10. If you use the name, it will return the computer that last reported having that system name.

### Interesting Custom API Strings

- **/JSSResource/computers**
  - Iterates across and pulls data from every computer, excluding only the FONTS field.

- **/JSSResource/mobiledevices**
  - Iterates across and pulls data from every iPad, iPhone, AppleTV, and other mobile devices, returning all fields.

- **/JSSResource/byoprofiles**
  - Collects configuration profiles applied to computers or mobile devices that are user-enrolled.

- **/JSSResource/computerconfigurations**
  - Collects all Computer Configurations that could be applied to a computer, including details related to the configuration profile.

- **/JSSResource/directorybindings**
  - Collects User Directory Bindings and authentication data used for user lookup with conditional access systems.

- **/JSSResource/licensedsoftware**
  - Collects data on software licensed through the Apple Store, requiring connection with Apple School or Business Manager.

- **/JSSResource/macapplications**
  - Collects every application the Jamf Pro server has seen on devices since it began collecting data (high data usage).

- **/JSSResource/mobiledeviceapplications**
  - Collects every application installed on a mobile device that the Jamf Pro server has seen (high data usage).

- **/JSSResource/restrictedsoftware**
  - Collects data on applications marked as restricted by the Jamf Pro administrator and removes them if possible.

- **/JSSResource/scripts**
  - Collects scripts that could be deployed to a computer, combining this with Smart Groups to find all computers with these scripts installed.

- **/JSSResource/sites**
  - Collects multi-tenancy information available with sites, exposing hierarchical relationships within the Jamf Pro server.

- **/JSSResource/users**
  - Collects data on users seen by the Jamf Pro server, correlating assigned devices with this endpoint.

- **/JSSResource/vppassignments**
  - Shows applications purchased through the Apple Volume Purchasing Program and their deployment to users or devices.

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:
