### ISSUE TITLE
[Meta] AWS ELB Integration Improvements

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#10151]
The current ELB integration, we are collecting metrics from 3 different kinds of load balancers: Classic Load Balancer, Application Load Balancer, and Network Load Balancer. 

Below are the various enhancement requests for AWS ELB Integration package
```[tasklist]
### Requirements
- [ ] https://github.com/elastic/integrations/issues/4800
- [ ] https://github.com/elastic/integrations/issues/5953
- [ ] https://github.com/elastic/integrations/issues/9201
- [ ] https://github.com/elastic/integrations/issues/10149
- [ ] https://github.com/elastic/integrations/issues/10326
```

**Comment by agithomas** [comment]
PR Link : https://github.com/elastic/integrations/pull/10444

**Comment by agithomas** [comment]
All the planned enhancements are complete. Marking the meta issue as closed.
