### ISSUE TITLE
[Tychon] Rework field mapping - remove non-ECS fields from root level for all data streams

### ISSUE THREAD

**Issue by narph** [elastic/integrations#10221]
This is the work to get fields and their pipelines in good shape, ready for use in updated dashboards.

```[tasklist]
### Tasks
- [x] Ensure pipelines pass for all sample data.
- [x] Check the differences between field names in incoming data files and in the final documents ingested. Make a list of any differences. Do this by reading pipelines or comparing the input and output of pipeline tests for full data.
- [x] Fix transforms: add fields to distinguish between source and destination, speed up processing.
- [x] Name data streams, transforms, destination indexes appropriately. Duplicate for ease of comparison during dashboard adjustments.
- [x] De-duplicate/align common pipeline processing.
- [x] Move incoming fields under a `tychon.*` prefix, repeat ECS fields in the root.
- [x] For each existing index pattern, write a filter that will select those records directly from logs-*, for use in dashboards. It should distinguish between each subset of records output by the merged transforms.
```
