### ISSUE TITLE
[Tychon] Clean up for review

### ISSUE THREAD

**Issue by chrisberkhout** [elastic/integrations#10263]
Miscellaneous clean-up for review.

```[tasklist]
### Tasks
- [x] remove data views
- [x] remove old data streams and transforms
- [x] check whether all skipped validations should still be skipped
- [x] README: make fields helper refereces use the new data stream names
- [x] Mark as partner supported
- [x] set publisher_pipeline.disable_host: true for all data streams
- [x] external_device_control: Ensure it collects from linux paths, if only for testing
- [x] make docker-compose.yml files all the same
- [x] external_device_control: Ensure we have some test data. Use the assumed tychon_devicecontrolpolicy_info.json
- [x] external_device_control: generate sample_event.json
- [x] consider bringing back '[TYCHON] - Device Control Events' dashboard with assumed data => the dashboard still doesn't populate (only a couple of points on 1/5 panels, all show errors), probably because the dashboard is for "Device Control Events" and we only have an example device control policy event (from tychon_devicecontrolpolicy_info.json).
- [x] Tidy/remove any additiona/unnecessary assets in kibana/
- [x] rename stream.yml.hbs files (and manifest refs) to filestream.yml.hbs to match actual input name
- [x] Assert hit counts in system tests
- [x] Consolidate docker-compose.yml (2 versions, should be 1), stream.yml.hbs (3 versions, should be 2)
- [x] email tychon re review
- [x] Regenerate all sample_event.json files
- [x] Check ILM policies, make them have short retention
- [x] Review categorizations in manifest files and ECS fields => manifest categories updated, event.category values seem ok.
- [x] Add "preserve original event" option for the CMRS data stream
- [x] Set correct initial version number and changelog entry
- [x] Add screenshots for all dashboards
- [x] Use modern ECS? => probably not. it's easier to keep data_stream/<ds>/fields/ecs.yml, since although that could go away, we'll need the same in elasticsearch/transform/<ds>/fields/ecs.yml, and keeping both means synchronization of the two directories is more straightforward
- [x] Remove any data streams or other elements that should be postponed until after the initial merge => couple of dashboards removed, all datastreams seem okay to go into review
- [x] browser DS: in Kibana, field says "Conflict" for tychon.package.version_{build,major,minor,release}: {0,124,0,2} => fixed
- [x] check for TODOs in repo
- [x] extra pipline improvement: check that host.ip is populated if there's a value in the ipv4 or ipv6 fields => already done in input data
- [x] extra pipline improvement: remove fields that may be unused: elastic_agent (in agent.yml), input, log (in base-fields.yml)
- [x] extra pipline improvement: simplify: convert+set+split+set+remove+convert
- [x] extra pipline improvement: simplify/improve: consider removing 'ignore_failure: true'
- [x] populate ECS related.*
- [x] transforms: are we using the right field for deduplication? (originally id, except one that was tychon.id) => yes, some explanation in https://github.com/elastic/integrations/pull/10811/commits/517d4f06fda34c5a03672cb71dee3eb22a66c5cf. The id field of the data files (tychon.id after ingestion) seems to be unique for each event and looks like sha1 hashes.
- [x] Ensure publisher_pipeline.disable_host and preserve_original_event options are used appropriately => no surprises. open question re collecting host files to mention in PR and ask tychon about
- [x] ----------v checklist for draft PR v----------
- [x] Summarize approach and changes in draft PR
- [x] Note unusual data streams: externaldevicecontrol, cmrs?, ?
- [x] Is the CMRS data stream useful? Test data has large base64 encoded XML data in it, not touched by the pipeline
- [x] Note potential dashboard duplication
- [x] Note un-dashboarded data streams: cmrs, coams, features
- [x] transforms: should we bring back the filter for event.kind==state? this would exclude other types such as pipeline_error from the dests => mentioned in draft PR description
- [x] Check and note issue of some fields, when switch to prefixed in visualizations, say "This might be an approximation. For more precise results, you can enable accuracy mode, but it increases load on the Elasticsearch cluster." => mentioned in draft PR description
- [x] Review and update README => mentioned in draft PR description
- [x] Clean up terminology: host vs filesystem certificates (appear to be the same, separate from listening certificates) => mentioned in draft PR description
```
