### ISSUE TITLE
[Custom STIX]Support for system and pipeline tests

### ISSUE THREAD

**Issue by chemamartinez** [elastic/integrations#10261]
This is a subtask for https://github.com/elastic/integrations/issues/4710.

The goal of this task is to add pipeline and system tests to the Custom STIX integration.
```[tasklist]
### Tasks
- [ ] Create pipeline tests for every supported STIX Domain Object
- [ ] Create system tests over CEL input
- [ ] Create system tests over Filestream input
```
