### ISSUE TITLE
[Mimecast] Add support for API 2.0

### ISSUE THREAD

**Issue by narph** [elastic/integrations#11159]
- [x] archive_search_logs #11782
- [x] audit_events #11782
- [x] dlp_logs #11782
- [x] message_release_logs #11782
- [ ] siem_logs #11801
- [x] threat_intel_malware_customer #11782
- [x] threat_intel_malware_grid #11782
- [x] ttp_ap_logs #11782
- [x] ttp_ip_logs #11782
- [x] ttp_url_logs #11782

V2 migration guide here:

https://developer.services.mimecast.com/api-1-0-to-2-0-migration-guide

Steps:
- API 1.0 does not support OAuth 2.0, and API 2.0 is OAuth 2.0
- Consider using CEL input (for existing data streams we should avoid breaking the upgrade process for existing users. IIUC as long as you are not renaming existing config options for the auth data stream there won't be any upgrade issues. But do manually test upgrading. The cursor state will be lost, but we are mitigating duplicates with a fingerprint in auth (it's not a 100% guarantee of no duplicates through).
- Verify data compatibility between v1/v2

Note:
There is no deprecation/stop date for API 1.0 but access will be restricted to new application creation in their Administration Console at the beginning of 2025.
