### ISSUE TITLE
[meta] Qualys VMDR: Enhancement to leverage cloud workflows

### ISSUE THREAD

**Issue by kcreddy** [elastic/integrations#11673]
As part of effort to support Cloud Security features with the data from these 3rd party integrations, the vulnerabilities findings data from Qualys VMDR should be enriched.

The vulnerability data resides in 2 datastreams in Qualys VMDR integration.

1. [Asset Host Detection](https://qualysguard.qg2.apps.qualys.com/qwebhelp/fo_portal/api_doc/assets/index.htm#t=host_lists%2Fhost_detection.htm): Provides some vulnerability information for hosts in users’s account.
2. [Knowledge Base](https://qualysguard.qg2.apps.qualys.com/qwebhelp/fo_portal/api_doc/scans/index.htm#t=kbase%2Fknowledgebase.htm): Provides detailed vulnerability data from the Qualys KnowledgeBase. Doesn’t associate with any user’s resources.

We will need both datastreams and use it to enrich vulnerability findings workflow, as Asset Host Detection is missing CVE and description which would be important to stitch in the vulnerability findings coming from Qualys. The integration should be performing the join as it queries the data. For example, as it queries the assets, it could fetch the related knowledge base entries related by the QID field.

Tasks:
- [x] Create Qualys user with access to asset host detections and knowledge base: https://github.com/elastic/infosec/issues/19399
- [x] Setup Qualys Asset(s) to use with the asset host detections API.
- [x] Setup `Asset Host Detection` data in demo environment.
- [x] Analyse and get clarifications on mapping changes with Cloud team.
   - [x] Fix any existing bugs: 
      - [x] https://github.com/elastic/integrations/pull/11877
      - [x] https://github.com/elastic/integrations/pull/12006
      - [x] https://github.com/elastic/integrations/pull/12009
   - [x] Cleanup https://github.com/elastic/integrations/pull/11927
- [x] Implement mapping changes: https://github.com/elastic/integrations/pull/11999
- [x] Implement transform: https://github.com/elastic/integrations/issues/12718

**Comment by kcreddy** [comment]
**Update:**
With @clement-fouque's assistance, the asset is now available with vulnerability data. Also got access to the relevant API for fetching the asset vulnerability data.

**Comment by kcreddy** [comment]
> We will need both datastreams and use it to enrich vulnerability findings workflow, as Asset Host Detection is missing CVE and description which would be important to stitch in the vulnerability findings coming from Qualys. The integration should be performing the join as it queries the data

As [enrich processor](https://github.com/elastic/package-spec/blob/main/spec/integration/elasticsearch/pipeline.spec.yml#L26) is not yet supported to enrich data across indices, there are couple of ways this join can be done between [`Asset Host Detection (AHD)`](https://qualysguard.qg2.apps.qualys.com/qwebhelp/fo_portal/api_doc/assets/index.htm#t=host_lists%2Fhost_detection.htm) and [`Knowledge Base (KB)`](https://qualysguard.qg2.apps.qualys.com/qwebhelp/fo_portal/api_doc/scans/index.htm#t=kbase%2Fknowledgebase.htm) data-streams (both inside CEL input):

**Option 1:**
1. Call the `AHD` API and get list of host detections (each record includes a QID).
2. Iterate over this list of QID. For each `<qid>`: 
   - Call the `KB` API with query param `ids=<qid>`.
   - Return KB response along with top-level `AHD` response.
Pros:
- More straight-forward and clean.
Cons:
- With `AHD` [default batch_size](https://github.com/elastic/integrations/blob/main/packages/qualys_vmdr/data_stream/asset_host_detection/manifest.yml#L29) of `1000`, we need to make 1000 `KB` API calls for each CEL evaluation. The default value needs to be set to much lower value. Any performance drop need to be evaluated.


**Option 2:**
1. Call the `AHD` API and get list of host detections (each record includes a QID).
2. Use the `worklist` approach using `state.want_more` to call `KB` API only once per CEL evaluation. Examples: [Snyk](https://github.com/elastic/integrations/blob/main/packages/snyk/data_stream/audit_logs/agent/stream/cel.yml.hbs#L55), [Microsoft Sentinel](https://github.com/elastic/integrations/blob/main/packages/microsoft_sentinel/data_stream/alert/agent/stream/cel.yml.hbs#L51)
Pros:
- Only 1 (max 2) call per CEL evaluation. If users set `batch_size > 1000`, they need to increase CEL `max_executions` (default also `1000`).
Cons:
- Unlike the current examples using `worklist` approach, here the top-level `AHD` response needs to be part of the event. Hence, this `AHD` response needs to be stored inside the `state` until entire worklist is finished. This increases the size of CEL `state`.

**Comment by andrewkroh** [comment]
Between those options, option 2 seems better because it is less prone to breakage due to batch size and requires less tuning by users.

A really nice side effect of this is that we won't need to fetch all data from the KB API. The KB API has been problematic because it does not have any "page size" query options, which results in very large, unbounded response bodies. By querying the KB API based on QID, the integration will have more predictable memory requirements (once users no longer need to enable the knowledge base data stream).

**Comment by kcreddy** [comment]
Created draft https://github.com/elastic/integrations/pull/11999 using option 2. The `knowledge_base` API response is present at `qualys_vmdr.asset_host_detection.knowledge_base`

**Comment by kcreddy** [comment]
After an internal discussion within Cloud team, it was suggested to remove transform from this enhancement to help unblocking. The transform will be added later after Kibana side changes are made for improvising UI in CDR workflow.

**Comment by kcreddy** [comment]
The PR for mapping related changes is merged: https://github.com/elastic/integrations/pull/11999
Transform will be added after UI improvements is done in order to handle empty and multiple CVEs.
I created https://github.com/elastic/integrations/issues/12718 for transform work.

@smriti0321 / @maxcold, let us know when its good to take up transform task.

cc: @narph

**Comment by kcreddy** [comment]
Moved to blocked until we get acceptance from Cloud Security team to work on transform.

**Comment by kcreddy** [comment]
We got the go-ahead from the Cloud team. 
The transform PR: https://github.com/elastic/integrations/pull/13455 is created. Cloud team is running tests on the PR.

**Comment by kcreddy** [comment]
Closing as all tasked are Done.

**Comment by kcreddy** [comment]
Closing as all tasked are Done.
