### ISSUE TITLE
[Epic] Road to Agentless + Security Integrations Release (Phase I)

### ISSUE THREAD

**Issue by qcorporation** [elastic/integrations#11810]
## Topic
The Epic describes the Development efforts to release the first initial Security Integrations under the Agentless deployment model.
Product Ticket is defined [here](https://github.com/elastic/security-team/issues/10092)

## What are we releasing?
Security Integrations targeted for the initial release for the **8.18 release**, are:

1. Office 365
2. Okta
3. AWS Security Hub
4. SentinelOne
5. AbuseCH
6. Microsoft Defender Cloud
7. Microsoft 365 Defender
8. Microsoft Defender for Endpoint
9. Google Security Command Center
10. Google Workspace
11. Tenable IO
12. Wiz
13. Qualys VMDR
14. Microsoft Sentinel
15. Google SecOps
16. Splunk

## What is required for the release?

- Enabling the integrations listed above within the integration `manifest.yml` template policy to have an agentless deployment mode
- Providing important Agentless information within the integration documentation
- End-to-end testing for each integration (require account/permission to vendors)

## Dependencies
State Storage for Filebeat: PR: https://github.com/elastic/beats/pull/41446
Disable Agentless in UI for on-prem users: https://github.com/elastic/kibana/issues/201217
~~Hide unsupported inputs and outputs https://github.com/elastic/package-spec/issues/805~~ (all listed integrations have been vetted for supported inputs) 

## Breakdown

```[tasklist]
## Tasks
- [ ] https://github.com/elastic/security-team/issues/8883
- [ ] https://github.com/elastic/integrations/issues/11812
- [ ] https://github.com/elastic/integrations/issues/11811
- [ ] https://github.com/elastic/integrations/issues/11813
- [ ] Documentation for agentless for Phase I Integrations (pending ownership)
```

**Comment by smriti0321** [comment]
@qcorporation The dependency related to the state store has been resolved with the merge of [this](https://github.com/elastic/beats/pull/41446) pull request. Since the CSPM integration does not use this capability by design, we want to see this new capability utilized in Okta or any other integration that stores state.

As discussed during out sync on agentless integration yesterday, with the public release of 9.0 Beta approaching on [February 18th](https://docs.google.com/spreadsheets/d/1ohPWWkUy5Cc2k4HJSx3XBKXY5nxeuiehApFLFHdHM3U/edit?gid=1759203167#gid=1759203167), we need to gain more confidence in these changes. Please keep us updated on your agentless support progress for these SaaS integrations and report any issues you encounter. cc @oren-zohar @norrietaylor @snehsach19 @tehilashn
