### ISSUE TITLE
Microsoft Office 365 Message Trace

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1200]
### Description
Message trace in the Security & Compliance Center follows email messages as they travel through your Exchange Online organization. You can determine if a message was received, rejected, deferred, or delivered by the service. It also shows what actions were taken on the message before it reached its final status.

You can use the information from message trace to efficiently answer user questions about what happened to messages, troubleshoot mail flow issues, and validate policy changes.

### Architecture
The Mailtrace API can be leveraged. @P1llus has a draft PR available [here](https://github.com/elastic/beats/pull/22532). 

Sample Pipeline: [O365 Message Trace Pipeline.txt](https://github.com/elastic/integrations/files/9208620/O365.Message.Trace.Pipeline.txt)

Sample Document: [Message Trace Sample Doc.txt](https://github.com/elastic/integrations/files/9208623/Message.Trace.Sample.Doc.txt)

Required processor:
```
- decode_json_fields:
    fields: [message]
    target: exchange
```

Response split:
```
target: body.value
```

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exist

**Comment by gils3nan** [comment]
+1 - would be a great integration to have

**Comment by jamiehynds** [comment]
Relevant PR here: https://github.com/elastic/integrations/pull/4135

Thanks to @WildDogOne!

**Comment by colin-stubbs** [comment]
Upvote! It would be good to see the PR reviewed and ideally accepted.

In summary, if Elastic Security/SIEM needs to be able to ingest all relevant endpoint, web, email and network events related to an organisation, across as many major / typically used products as possible.

Microsoft 365/Exchange Online is a pretty major product and should have priority.

**Comment by WildDogOne** [comment]
@colin-stubbs you're in luck, my PR got accepted yesterday, so I guess the integration should be available very soon

**Comment by jamiehynds** [comment]
Closing via https://github.com/elastic/integrations/pull/4135

Thanks again @WildDogOne!
