### ISSUE TITLE
AWS Network Firewall

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1204]
### Description
AWS Network Firewall is a managed service that makes it easy to deploy essential network protections for all of your Amazon Virtual Private Clouds (VPCs). AWS Network Firewall’s flexible rules engine lets you define firewall rules that give you fine-grained control over network traffic, such as blocking outbound Server Message Block (SMB) requests to prevent the spread of malicious activity. AWS Network Firewall works together with AWS Firewall Manager so you can build policies based on AWS Network Firewall rules and then centrally apply those policies across your VPCs and accounts.

Full overview available [here](https://aws.amazon.com/network-firewall/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc). 

### Architecture
An API is available and logging to both CloudWatch and S3 are supported. Relevant documentation [here](https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-logging.html). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- ~~[ ] Supported versions of the monitoring target are documented~~
- ~~[ ] Supported operating systems are documented (if applicable)~~
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: `^7.15.0 || ^8.0.0` (follows AWS package)

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists

**Comment by taylor-swanson** [comment]
The integration has been promoted to staging (version `1.7.0`)

Adding "add integration" page screenshots for reference:

![Screen Shot 2021-12-14 at 11 41 50 AM](https://user-images.githubusercontent.com/90622908/146059066-18290ff7-9ef2-4d8d-ae35-a5821941de0c.png)
![Screen Shot 2021-12-14 at 11 42 05 AM](https://user-images.githubusercontent.com/90622908/146059065-234e768f-1403-4a59-a394-1e7980b2ea6c.png)
