### ISSUE TITLE
Barracuda WAF

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1302]
### Description
Barracuda Web Application Firewall protects applications, APIs, and mobile app backends against a variety of attacks including the OWASP Top 10, zero-day threats, data leakage, and application-layer denial of service (DoS) attacks. By combining signature-based policies and positive security with robust anomaly-detection capabilities, Barracuda Web Application Firewall can defeat today’s most sophisticated attacks targeting your web applications.

### Architecture
Syslog is supported - samples provided by Barracuda and available internally. For relevant documentation see [here](https://campus.barracuda.com/product/webapplicationfirewall/doc/45025450/logs-overview/).

This integration will replace our existing experimental Barracuda WAF integration. 

 Worth noting that Barracuda have an [existing Logstash .conf](https://campus.barracuda.com/product/webapplicationfirewall/doc/88113551/integrating-the-elk-stack-v7-2-0-with-the-barracuda-web-application-firewall) which they recommend to users. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 8.4.0

### New Package

- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists

**Comment by jamiehynds** [comment]
Keeping this open.

**Comment by ebeahan** [comment]
Completed in #5493 #5746
