### ISSUE TITLE
[Meta] Move Observability integrations to GA

### ISSUE THREAD

**Issue by sorantis** [elastic/integrations#1438]
The majority of Observability integrations are currently either experimental or beta. The modules they have been migrated from are predominantly GA. We need to move the existing packages to GA before the 8.0. Below is the list of packages that should be migrated. Similar to the [security integrations GA effort](https://github.com/elastic/integrations/issues/961),  the list is prioritized according to beats modules' usage telemetry. Should there be any hinders that prevent a package from moving to GA please highlight them here.

**Integrations**
- [x] Docker https://github.com/elastic/integrations/pull/1571
- [x] Nginx https://github.com/elastic/integrations/pull/1614
- [x] Kubernetes https://github.com/elastic/integrations/pull/1610
- [x] Windows Custom Event Logs https://github.com/elastic/integrations/pull/1716
- [x] Kafka https://github.com/elastic/integrations/pull/1609
- [x] Zookeeper https://github.com/elastic/integrations/pull/1622
- [x] Apache https://github.com/elastic/integrations/pull/1607
- [x] MySQL https://github.com/elastic/integrations/pull/1612
- [x] Redis https://github.com/elastic/integrations/pull/1618
- [x] MongoDB https://github.com/elastic/integrations/pull/1611
- [x] Postgres https://github.com/elastic/integrations/pull/1616
- [x] AWS https://github.com/elastic/integrations/pull/1623
- [ ] Azure
- [x] GCP https://github.com/elastic/integrations/pull/1568 https://github.com/elastic/integrations/pull/1717
- [x] HAProxy https://github.com/elastic/integrations/pull/1608
- [x] traefik https://github.com/elastic/integrations/pull/1621
- [x] Tomcat https://github.com/elastic/integrations/pull/1620
- [x] NATS https://github.com/elastic/integrations/pull/1613
- [x] STAN https://github.com/elastic/integrations/pull/1619
- [x] Nginx Ingress Controller https://github.com/elastic/integrations/pull/1615
- [x] RabbitMQ https://github.com/elastic/integrations/pull/1617
- [x] CEF https://github.com/elastic/integrations/pull/1604
- [x] Cassandra (BETA) https://github.com/elastic/integrations/pull/2129

**Requirements for moving a package to GA:**

- Any package with httpjson input requires:
  - Closed beats/integrations gap on httpjson system tests
- All packages require:
  - ~Edge processing moved to ingest node pipeline https://github.com/elastic/security-team/issues/791~ we decided to remove it in integrations team meeting on July 16th
  - event.original is optional https://github.com/elastic/integrations/issues/777
  - Bump version to >=1.x.x

**Comment by kaiyan-sheng** [comment]
@sorantis For GCP integration, it still only includes the log part from Filebeat. We should finish migrating the metric parts first. So maybe the requirements for moving a package to GA should also include: Make sure all data streams are included?

**Comment by sorantis** [comment]
let's log this as a prerequisite under the GCP bullet above. This applies to all above integrations. Let's track them under each integration's entry in this meta issue.

**Comment by sorantis** [comment]
@kaiyan-sheng I changed your edit to a sub-bullet. Do we have a GH issue we could link to?

**Comment by mukeshelastic** [comment]
Hi @sorantis is the list in priority order? If not, can we make it in the order of priority we want to see it completed? 

@masci are you and folks on integrations team able to evaluate this list and provide a comments on what work is needed to make these integrations GA and then the feasibility of the number of integrations we are able to make GA in 7.16? I will also send an email to the integrations team about this so that everyone on the team can share their perspective.

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng I changed your edit to a sub-bullet. Do we have a GH issue we could link to?

@sorantis We don't have an issue for only migrating the metrics part but here is the [main issue](https://github.com/elastic/integrations/issues/490) for migrating GCP overall.

**Comment by mukeshelastic** [comment]
What is the remaining on the Azure integration to make it GA? For all integrations, we had a meta issue to describe what was needed but not for azure so can't tell what is  to be done for azure to make it GA? 

cc @ravikesarwani

**Comment by masci** [comment]
Let's discuss what we're missing for Azure specifically here https://github.com/elastic/integrations/issues/2197

Closing this one as done.
