### ISSUE TITLE
GA Security Integrations

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1562]
To encourage adoption of our Elastic Integrations, we need to officially support them. This ticket outlines the integrations we plan to GA over the coming releases. 

- [x] CEF
  - [x] Bump version

- [x] Check Point
  - [x] GA Beats module
  - [x] Bump version

- [x] Cloudflare
  - [x] HTTP system tests
  - [x] Bump version

- [x] CrowdStrike
  - [x] Bump version

- [x] CyberArk PAS
  - [x] Bump version

- [x] Custom Windows Events
  - [x] HTTP system tests
  - [x] Bump version

- [x] Google Cloud Platform (GCP)
  - [x] Pub/sub system tests
  - [x] All edge processing in ingest pipelines
  - [x] `event.original` is optional
  - [x] Bump version

- [x] Google Santa
  - [x] Bump version

- [x] Google Workspace
  - [x] HTTP system tests
  - [x] Bump version

- [x] Hashicorp Vault
  - [x] HTTP system tests
  - [x] Bump version

- [x] Juniper SRX
  - [x] Bump version
 
- [x] Microsoft Defender ATP 
  - [x] Rename package to 'Microsoft Defender for Endpoint'
  - [x] HTTP system tests
  - [x] Bump version

- [x] osquery Log Collection
  - [x] Bump version
 
- [x] Sophos
  - [x] Bump version

~~- [ ] VMware Carbon Black~~ (moved to #1879)
  ~~- [ ] Bump version~~

- [x] Zerofox
  - [x] HTTP system tests
  - [x] Bump version

- [x] Zoom
  - [x] HTTP system tests
  - [x] Bump version
