### ISSUE TITLE
Replace RSA2ELK Based Integrations

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1733]
We released a set of experimental integrations (and Beats modules) based on open source RSA Netwitness parsers. The goal was to quickly expand our supported sources. However, it has transpired that these integrations are hard to maintain and never moved beyond experimental. At this point, the plan is to replace these experimental integrations with new integrations built from scratch. For each new integration we develop, the corresponding experimental integration (and Beats module) will be deprecated. In some cases, new integrations will not be developed due to very little uptake of the experimental module. 

**Integrations to build and deprecate experimental integration (not finalized)**
- [ ] Barracuda WAF
- [ ] Cisco Nexus
- [x] Cisco Meraki | https://github.com/elastic/integrations/issues/2691
- [x]  Cyberark
- [ ] Cylance Protect
- [x] F5 Big-IP Access Policy Manager
- [x]  F5 Big-IP Advanced Firewall Manager
- [ ] Fortinet Client Endpoint
- [ ] Fortinet Fortimail
- [ ]  Fortinet Fortimanager
- [ ]  Imperva Secure Sphere
- [x]  Infoblox NIOS
- [x] Microsoft DHCP
- [x]  Proofpoint Email Security
- [x] Snort
- [x] Sonicwall
- [ ]  Squid
- [x] Symantec Endpoint Protection 
- [ ]  Tomcat
- [x] Zscaler

**Experimental integrations to deprecate (not finalized)**
- [ ] Barracuda Spam Firewall
- [ ] Bluecoat Director
- [ ]  Juniper JUNOS
- [ ] Juniper Netscreen
- [ ] Netscout Arbor Peakflow
- [ ] Radware Defense Pro
- [ ]  Sophos UTM

**Comment by felixfiskare** [comment]
Where can I found the replacement code for Zscaler? Would need it for a customer.

**Comment by jamiehynds** [comment]
> Where can I findthe replacement code for Zscaler? Would need it for a customer.

@felixfiskare Zscaler ZIA and ZPA are now available as agent integrations. 

https://github.com/elastic/integrations/tree/main/packages/zscaler_zia
https://github.com/elastic/integrations/tree/main/packages/zscaler_zpa
