### ISSUE TITLE
GA Security Integrations - 8.1

### ISSUE THREAD

**Issue by leehinman** [elastic/integrations#1879]
- [x] 1Password
   - [x] Bump version

- [x] Cisco Duo
   - [x] Bump version

- [x] Cisco Secure Endpoint
   - [x] Bump version

- [x] Microsoft DHCP
   - [x] Bump version

- [x] Palo Alto Cortex XDR
   - [x] Add system tests
   - [x] Bump version

- [x] VMware Carbon Black
   - [x] Add icon (#2042)
   - [x] Bump version
