### ISSUE TITLE
[META] Update title and description based on guidelines for Elastic Agent integrations

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/integrations#1884]
In 7.16, we are planning to introduce the unified integrations view. The primary goal of this view is to improve the discoverability for all data ingest options at Elastic. As part of this initiative, we'd like to improve the titles and descriptions of each integration card and do so in a uniform way. 

## Guidelines
These are the general guidelines we plan to use for the integration cards

![image](https://user-images.githubusercontent.com/25181823/136435492-1ccf2666-a20c-4b95-af0c-80d1e784f82a.png)

## Elastic Agent example
Here's an example for how agent can leverage these guidelines, but please follow the guidelines as you see fit.

| Current Title | Current Description                                                              | New Title   | New Description                                                       |
|---------------|----------------------------------------------------------------------------------|-------------|-----------------------------------------------------------------------|
| ActiveMQ      | ActiveMQ Integration                                                             | ActiveMQ    | Collect logs and metrics from ActiveMQ servers with Elastic Agent.    |
| Apache        | This Elastic integration collects logs and metrics from Apache servers           | Apache      | Collect logs and metrics from Apache servers with Elastic Agent.      |
| Auditd        | This Elastic integration collects and parses logs from the Audit daemon (auditd) | Auditd      | Collect logs from the Linux audit daemon with Elastic Agent.          |
| AWS           | This integration collects logs and metrics from Amazon Web Services (AWS)        | AWS         | Collect logs and metrics from Amazon Web Services with Elastic Agent. |
| AWS Billing   |                                                                                  | AWS Billing | Collect logs and metrics from AWS Billing with Elastic Agent.         |
| Azure Logs    | This Elastic integration collects logs from Azure                                | Azure       | Collect logs from Microsoft Azure with Elastic Agent.                 |

@akshay-saraswat will follow up with the appropriate folks

**Comment by jamiehynds** [comment]
@akshay-saraswat are the o11y team updating all integrations, or do you need assistance from my team to update our security integrations?

**Comment by akshay-saraswat** [comment]
Treating this as a meta issue for the following issues created for apps

- [ ] https://github.com/elastic/integrations/issues/1900
- [ ] https://github.com/elastic/integrations/issues/1901
- [ ] https://github.com/elastic/integrations/issues/1902

**Comment by alexfrancoeur** [comment]
@akshay-saraswat I wanted to follow up on this work for 7.16. In your opinion, would you call this done?

**Comment by akshay-saraswat** [comment]
I believe, yes, this is done. Closing it now.
