### ISSUE TITLE
Network Packet Capture Dashboards

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2169]
Our experimental NPC integration currently lacks dashboards. Existing Packetbeat dashboards needs to be migrated to Lens and included with the NPC integration. The Packbeat dashboards also use old maps, which need to be updated also - https://github.com/elastic/beats/issues/26015

- [ ] [Network Packet Capture - DNS Tunneling](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/DNS-Unique-Domains-ecs.json)
- [ ] [Network Packet Capture - DNS Overview](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/65120940-1454-11e9-9de0-f98d1808db8e-ecs.json)
- [ ] [Network Packet Capture - Cassandra](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Cassandra-ecs.json)
- [ ] [Network Packet Capture - Overview](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Dashboard-ecs.json)
- [ ] [Network Packet Capture - Flows](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Flows-ecs.json)
- [ ] [Network Packet Capture - HTTP](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-HTTP-ecs.json)
- [ ] [Network Packet Capture - MongoDB](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-MongoDB-performance-ecs.json)
- [ ] [Network Packet Capture - MySQL Performance](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-MySQL-performance-ecs.json)
- [ ] [Network Packet Capture - Network File System](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-NFS-ecs.json) | [Bug](https://github.com/elastic/beats/issues/19547#event-5635140638) to consider fixing. 
- [ ] [Network Packet Capture - PostgreSQL Performance ](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-PgSQL-performance-ecs.json)
- [ ] [Network Packet Capture - Thrift Performance](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Thrift-performance-ecs.json) 
- [ ] [Network Packet Capture - DHCP Overview](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/a7b35890-8baa-11e8-9676-ef67484126fb-ecs.json)
- [ ] [Network Packet Capture - TLS Sessions ](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/tls-sessions-ecs.json)
