### ISSUE TITLE
[Meta] Auth and Billing

### ISSUE THREAD

**Issue by andrewvc** [elastic/integrations#2205]
This meta issue covers all auth related issues related to implementing an MVP version of auth and billing.

## Auth Issues

See [this design doc](https://docs.google.com/document/d/1nxJ0r0LZ2EUjfPkoHi2QdS8-ouN7XL1IgFhNubVKO48/edit#heading=h.2h1xm6qf9u3z)

- [ ] Follow-up with findings on what current cert kibana contains in https://github.com/elastic/synthetics-service/issues/82  . We're hoping it contains the customer's cluster ID for use in billing. @AlexP-Elastic  + @daniel-bytes
- [ ] Design / create mechanism for synthetics service to keep track of latest CA bundle for all regions (@lucasmoore )
- [ ] Add new Kibana YML options for path to current x509 cert for mtls comms with service @andrewvc @shahzad31 @dominiqueclarke  

## Billing issues

**Comment by andrewvc** [comment]
Created by mistake.
