### ISSUE TITLE
[Meta] Move rest of the Observability agent integrations to GA

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#2337]
We have already moved 20+ agent-based Observability integrations from experimental or beta to GA. We should keep the momentum going towards the Beats → Agent migration and eventual GA so that we could reduce adoption friction for fleet and agent. Below is the list of packages that should be migrated as a second batch. This list is prioritized according to beats modules' usage telemetry as well as the number of ERs received. Should there be any hinders that prevent a package from moving to GA please highlight them here.

#### vSphere
- [x] https://github.com/elastic/integrations/issues/3508 
- [x] Fix https://github.com/elastic/integrations/issues/3429
- [ ] Remove beta flag

#### IIS
- [x] Fix https://github.com/elastic/integrations/issues/2347
- [x] #3523 
- [x] Remove beta flag

#### CockroachDB
- [x] https://github.com/elastic/integrations/issues/480
- [x] #3550 
- [ ] Remove beta flag
