### ISSUE TITLE
Replace logfile input using filestream input in all packages

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#2495]
This meta issue is to track updating all the integrations that are using `logfile` input to use `filestream` input instead. 
Here is the list of integrations:

- [x] kubernetes https://github.com/elastic/integrations/pull/2139
- [ ] panw
- [ ] activemq
- [ ] cyberarkpas
- [ ] postgresql
- [ ] fireeye
- [ ] osquery
- [ ] cylance
- [ ] crowdstrike
- [ ] checkpoint
- [ ] carbonblack_edr
- [ ] zscaler
- [ ] cyberark
- [ ] microsoft_defender_endpoint
- [ ] tomcat
- [ ] kibana
- [ ] cisco_asa
- [ ] logstash
- [ ] redis
- [ ] hashicorp_vault
- [ ] squid
- [ ] microsoft
- [ ] f5
- [ ] proofpoint
- [ ] suricata
- [ ] barracuda
- [ ] netscout
- [ ] atlassian_jira
- [ ] atlassian_confluence
- [ ] bluecoat
- [ ] cisco
- [ ] rabbitmq
- [ ] sonicwall
- [ ] cosco_nexus
- [x] nginx_ingress_controller https://github.com/elastic/integrations/issues/4841
- [ ] cef
- [ ] mongodb
- [ ] stan
- [ ] radware
- [ ] system
- [ ] nats
- [ ] cisco_ftd
- [ ] santa
- [ ] nginx
- [ ] kafka
- [ ] cassandra
- [ ] snort
- [ ] infoblox
- [ ] mysql
- [ ] zeek
- [ ] atlassian_bitbucket
- [ ] auditd
- [ ] juniper
- [ ] log
- [ ] modsecurity
- [ ] cisco_meraki
- [ ] mattermost
- [ ] sophos
- [ ] iptables
- [ ] imperva
- [ ] elasticsearch
- [ ] apache
- [ ] traefik
- [ ] microsoft_dhcp
- [ ] fortinet
- [ ] haproxy
- [ ] cisco_ios

**Comment by taylor-swanson** [comment]
Another issue to consider is migrating configuration from the logfile input to filestream. I'm having a similar problem with moving the syslog input to tcp/udp input with syslog processor. I did write up a change proposal for package-spec to address this: https://github.com/elastic/package-spec/issues/383
