### ISSUE TITLE
Cisco Meraki Integration

### ISSUE THREAD

**Issue by r00tu53r** [elastic/integrations#2691]
### Description
Cisco Meraki is a leader in cloud controlled Wi-Fi, routing, and security. This ticket is intended to support Meraki MX. MS and MR series devices will be considered in a future integration. 

Worth noting this new integration will replace our existing experimental Meraki integration. 

### Architecture
Syslog is supported - relevant documentation [here](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples)

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### Migration Checklist

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [x] Generated output for at least 1 log file exists
- [x] Documentation explains how to configure monitoring target to work with the integration
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:
- [ ] Screenshot of the "Add Integration" page on Fleet added to PR

### Dashboards

- [ ] Dashboards exists
- [ ] Screenshots added to manifest
- [ ] Data stream filters added to visualizations

### Data Streams
- meraki
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
  - Inputs
    - tcp
    - udp
    - logfile
      - [x] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) added

**Comment by jamiehynds** [comment]
Pipelines created by @dainperkins which may help as we build this integration: https://github.com/dainperkins/Elastic-ECS-SIEM/tree/master/Meraki

**Comment by r00tu53r** [comment]
Thanks @jamiehynds. Couple of questions -

Will the new package replace the current one at the source ? I don't see the current `cisco_meraki` package having a deprecated marker. I was wondering if both need to be supported.

What is would be the recommendation for the `kibana.version` value (`7.17 || 8.0`) ?

**Comment by jamiehynds** [comment]
@r00tu53r ideally, we'd like to make the make the switch from the the experimental integration (which isn't supported) to this new integration as seamless as we can for users. One option is to include new pipelines in the current integration, and when a user upgrades the package they get the new and improved pipelines, without the need to jump to a new integration. Would rely on @andrewkroh for guidance on whether that's achievable technically. If not, we'll just simply create a net new integration and deprecate or pull the experimental integration. 

Can you tell from the pipelines if the current Meraki integration supports MX (security appliacnce), MS (switch) and MR (access points) series?

**Comment by andrewkroh** [comment]
No need to deprecate anything. We can replace the logic within the `cisco_meraki.log` data stream. Assuming it's still reading all of the log data from a single input I think it makes sense to continue having all of the logic withing the `log` data stream.

I can't really tell what's supported in the current config, but https://github.com/adriansr/nwdevice2filebeat/blob/master/devices/ciscomeraki/ciscomerakimsg.xml is the source from which it was generated.

**Comment by jamiehynds** [comment]
Thanks @andrewkroh. Looking at the [RSA docs](https://community.rsa.com/yfcdo34327/attachments/yfcdo34327/netwitness-integrations/96/1/Cisco_Meraki.pdf), the integration is focused on the MX-series which makes sense given the security use case. @r00tu53r I've updated the issue description to narrow our focus to MX series. Some sample events in their docs here - https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples

**Comment by dainperkins** [comment]
FWIW, I'd recommend ditching the RSA version entirely, and either rebuilding the whole thing from the API, or minimally building an asset index from the API to then enrich syslog data with e.g. device specifics

**Comment by andrewkroh** [comment]
@dainperkins We are fully replacing the rsa2elk implementation.

So you're saying that the data from the [API/webhook](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Meraki_Device_Reporting_-_Syslog%2C_SNMP%2C_and_API#API_Reporting) is better than we get in the syslogs? If we did away with log ingestion would we still have all of the data from the API alone?

We don't have a mechanism for enrichment today in Fleet packages.

**Comment by dainperkins** [comment]
It's definitely more complete - you'll know what type of device you are polling, get all of the syslog data, and be able to get device stats, client information, etc.

It does require recursively going thru the apis (orgs, networks, devices, device stats, clients iirc)

IIRC theres a devnet demo install that you can poll (and I've got some in the logstash configs Jamie referenced above)

**Comment by r00tu53r** [comment]
@jamiehynds I see the scope of the ticket has been adjusted to just MX. 

The current RSA2ELK integrations does process syslog messages but most of the processing on the agent. The ingest pipeline is quite minimal and does not have logic specific to any message/event type.

@andrewkroh - as @dainperkins  mentioned API/Webhook integration supports a wider variety of event gathering. The table towards the end of the page here - https://documentation.meraki.com/General_Administration/Cross-Platform_Content/Alerts_and_Notifications has details of what can be monitored from Syslog vs API vs SNMP.

If we plan to add more than just MX, MR and MS devices I think the API/Webhook might be a better choice. If not syslog might be sufficient.

I am in the process of adding a `syslog` input and using this (https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples) as a reference to build the pipeline.

**Comment by r00tu53r** [comment]
I am in the process of adding a `syslog` input and using this (https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples) as a reference to build the pipeline.

**Comment by r00tu53r** [comment]
@dainperkins I have a dev-net sandbox too but I don't have any clients using which I can generate traffic. Do you have events being generated as a result of traffic on the network / events being described [here](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples) ? 

I didn't see event log formats from webhook in the documentation - https://developer.cisco.com/meraki/webhooks/#!webhook-sample-alerts/aps-came-up

**Comment by jamiehynds** [comment]
@r00tu53r I adjusted to MX on the assumption that's what our current parser is limited to, but it probably makes sense to ensure we have broad coverage if possible (understood this will likely take longer to achieve). If the API is a better choice and also avoids us having to add it down the line, makes total sense to work on it now. Looking at other vendors, older integrations (like RSA) rely on syslog only, but all recent integrations seem to hit the Meraki API.

**Comment by dainperkins** [comment]
Part of the problem with just syslog is it is difficult to determine what type of device the logs are coming from (an MX device for instance can be wired-only, or with integrated wireless...)

**Comment by andrewkroh** [comment]
I think we'll need to continue supporting ingestion of syslog data via udp/tcp/log in the `cisco_meraki.logs` data stream in order to not make unnecessary breaking changes.

**Comment by r00tu53r** [comment]
`kibana.version` has been set to `7.17 || 8.0.0`. Should I be setting it to what the earlier version supported ? Considering this is a complete rewrite.
