### ISSUE TITLE
[Meta] Implement input parameter ignore_older for all log inputs

### ISSUE THREAD

**Issue by nimarezainia** [elastic/integrations#3147]
There are many input parameters that need to be considered for configuration either globally or per individual data stream. https://github.com/elastic/kibana/issues/122892

_ignore_older_ (which allows the user to ignore older logs) is applied to each data_stream and is currently missing from many integrations that use logs as input. In order to improve scalability of Elastic Agent, this is one of the first (and most useful) parameters to have configured.

ignore_older is already done for Windows custom events (see below). The same approach should be taken for the other integrations:

![image](https://user-images.githubusercontent.com/13442829/164336942-e8c04d34-7bd8-4dd0-bedd-bfb5c197a187.png)

List of integrations that need to add/implement _ignore_older:_

- [ ] [System Integration](https://github.com/elastic/integrations/issues/3149)
- [x] [Windows Integration](https://github.com/elastic/integrations/issues/3148)
- [ ] [NGINX](https://github.com/elastic/integrations/issues/3150)

**Comment by jlind23** [comment]
@nimarezainia System and windows belong to us, but the NGINX one should be done by the service integration team

**Comment by amolnater-qasource** [comment]
Hi @nimarezainia @jlind23 

We have created **03 testcases** for this under our Fleet test suite at links:

- [Validate Ignore events older than field is available for datasets of System integration](https://elastic.testrail.io/index.php?/cases/view/167687)
- [Validate Ignore events older than field is available for datasets of Nginx integration](https://elastic.testrail.io/index.php?/cases/view/167689)
- [Validate Ignore events older than field is available for datasets of Windows integration](https://elastic.testrail.io/index.php?/cases/view/167690)

Could you please share more testing details for this, if any other testing is required?

Please let us know if we are missing anything here.

Thanks

**Comment by bvader** [comment]
Hi Team /  @nimarezainia 

I have users asking for the `ignore_older` particularly one for the IIS logs I tried 8.4.4-SNAPSHOT and 8.5.0-SNAPSHOT `ignore_older` setting is not there in the Kibana Integrations page. I am testing this on Elastic Cloud.

This [code appears](https://github.com/elastic/integrations/pull/4212) to be merged to main, is there a planned release label, it says 8.4 above but that does not appear accurate. Is dependent on other Kibana work? 

Screen shot is from 8.5.0-SNAPSHOT in the cloud.

<img width="867" alt="Screen Shot 2022-10-09 at 12 32 18 PM" src="https://user-images.githubusercontent.com/15572155/194776036-75e9c690-bd1a-4cbd-98d1-ae3427714801.png">

**Comment by jlind23** [comment]
@andresrc it seems like this IIS version stayed at the snapshot stage - https://github.com/elastic/package-storage/tree/snapshot/packages/iis/1.1.0 
Could you please help @bvader out?

**Comment by andresrc** [comment]
@lalit-satapathy @rameshelastic can we move IIS forward?

**Comment by lalit-satapathy** [comment]
> @lalit-satapathy @rameshelastic can we move IIS forward?
Yes, we will be promoting iis to prod.

**Comment by lalit-satapathy** [comment]
promoted iis 1.2.0 to production,
