### ISSUE TITLE
Resolve potential IDs conflicts between Kibana dashboards

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#318]
As there is chance of naming (ID) conflict between Kibana dashboards, it's advised to prepend a package name.

There are few action items identified that can help in resolving the issue:

- [x] Prepare some script to prepend the package name to the dashboard id. Ideally we should do the same with the existing dashboard links: #319 @ycombinator 
- [x] Release new package revisions for 7.10+ @ycombinator 
- [ ] Add some validations to elastic-package for future packages: https://github.com/elastic/package-spec/issues/65 @mtojek 
- [x] Add this logic to the migration script. #322 @mtojek (in review)

**Comment by mtojek** [comment]
Promotion from snapshot to staging:
https://github.com/elastic/package-storage/pull/497
https://github.com/elastic/package-storage/pull/498

**Comment by mtojek** [comment]
Promotion from staging to production
https://github.com/elastic/package-storage/pull/499
https://github.com/elastic/package-storage/pull/500

**Comment by mtojek** [comment]
Branches merged, let's wait for Jenkins jobs to finish, package will be deployed tomorrow.

**Comment by mtojek** [comment]
Affected packages have been promoted.
