### ISSUE TITLE
Remove lightweight modules in packages

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#3188]
### Background
Before Elastic Agent and packages existed we introduced lightweight modules in Metricbeat to simplify the development of new metricsets and packages. The goal was to move to pure config defined modules as we have in Filebeat. Over time we have been making more and more use of it, for example in the AWS package. This is great as it reduces the number of code changes we have to make.

With the introduction of elastic packages, it has become even more important to have packages purely based on configurations because that is what is delivered as part of the package. Unfortunately many modules use lightweight modules but the packages we build also depend on the lightweight modules to be there, meaning the code/config files have to be contributed to the beats repository to work. This makes it easier to keep packages and modules in sync but it also means we keep adding to the beats repository. This issue is caused by running the migration script from Metricbeat to integrations. 

### Actions

1. For the old migrated data streams (from Bests) like `rds`: we should move the configuration part from Beats into integrations.
2. For all data streams: use ingest pipeline instead of rename processor.
3. For all new packages, we should add configuration directly into integrations.

### Impacted Integrations (wip)

- [x] aws dynamodb https://github.com/elastic/integrations/issues/3597
- [x] aws ebs https://github.com/elastic/integrations/issues/3598
- [x] aws lambda https://github.com/elastic/integrations/issues/3599
- [x] aws natgateway https://github.com/elastic/integrations/issues/3600
- [x] aws s3_daily_storage https://github.com/elastic/integrations/issues/3601
- [x] aws s3_request https://github.com/elastic/integrations/issues/3602
- [x] aws sns https://github.com/elastic/integrations/issues/3603
- [x] aws sqs https://github.com/elastic/integrations/issues/3604
- [x] aws transitgateway https://github.com/elastic/integrations/issues/3605
- [x] aws usage https://github.com/elastic/integrations/issues/3606
- [x] aws kinesis https://github.com/elastic/integrations/issues/3822
- [x] azure_metrics container_instance https://github.com/elastic/integrations/issues/3592
- [x] azure_metrics container_registry https://github.com/elastic/integrations/issues/3594
- [x] azure_metrics container_service https://github.com/elastic/integrations/issues/3595
- [x] azure_metrics database_account https://github.com/elastic/integrations/issues/3596
- [x] `gcp.billing` https://github.com/elastic/integrations/issues/3720
- [x] `gcp.compute` https://github.com/elastic/integrations/issues/3721
- [x] `gcp.firestore` https://github.com/elastic/integrations/issues/3722
- [x] `gcp.storage` https://github.com/elastic/integrations/issues/4262
- [x] `gcp.pubsub` https://github.com/elastic/integrations/issues/4263
- [x] `gcp.loadbalancing` https://github.com/elastic/integrations/issues/4264
- [x] `gcp.dataproc` https://github.com/elastic/integrations/issues/4265

**Comment by ruflin** [comment]
++ on moving to a fully package based approach. There is another benefit of this that the data collection part on the edge becomes less complex and needs less changes. This might make it easier that also newer version of Elastic Agent can ship data to older versions of Elasticsearch as the data format shipped stays the same. What matters is only the package that is installed.

On side effect of 2 is that we will use the rename processor a lot more (see https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/aws/rds/manifest.yml#L79 as an example). Lets make sure to involve the es-perf team ( @DJRickyB ) in this. I'm not too concerned on the metrics front about this change as my understanding is the number of events is not very high compared to logs and we do much heavier processing on the logs side but it is worth investigating. It might be useful to have a bulk rename processor that could also make it easier to write these renames.

**Comment by kaiyan-sheng** [comment]
One problem showed up is: before moving configuration from Beats to Integrations, EC2 metrics data stream generates events with field:
```
    "metricset": {
        "period": 300000,
        "name": "ec2"
    }
```
With moving the configuration into integrations, EC2 metrics data stream generates events with field:
```
    "metricset": {
        "period": 300000,
        "name": "cloudwatch"
    }
```
This is caused by `metricsets` field in `stream.yml.hbs`. It changed from `ec2` to `cloudwatch` after moving the configuration to integrations: https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/ec2_metrics/agent/stream/stream.yml.hbs#L1

Should we add a rename processor to rename `metricset.name` from `cloudwatch` to `ec2` in this case?

**Comment by endorama** [comment]
Should we add a removal step in the ingest pipeline to remove `metricset.name` in integrations?

**Comment by kaiyan-sheng** [comment]
> Should we add a removal step in the ingest pipeline to remove `metricset.name` in integrations?

@endorama Good question! This field does tell us which metricset is it using from Metricbeat. This way, user knows we are using the cloudwatch metricset in the background instead of the ec2 metricset for example. Not sure how useful this is but since this field exist across all integrations, maybe we can keep it for now?

**Comment by tommyers-elastic** [comment]
@kaiyan-sheng @endorama @zmoog i think everything is done here - shall we close this issue once and for all?

**Comment by kaiyan-sheng** [comment]
@tommyers-elastic I just went though our GCP package and found these data streams are added but not with lightweight module removed. I will move these into the issue description. 
- [ ] GCP storage 
- [ ] GCP pubsub
- [ ] GCP loadbalancing
- [ ] GCP dataproc

**Comment by ChrsMark** [comment]
@kaiyan-sheng shall we communicate this effort with the wider audience of integrations' teams? This would help to advertise the recommended way when it comes to the usage (or non usage :)) of leighweight modules.

We discovered this while implementing/reviewing at https://github.com/elastic/integrations/pull/4253#discussion_r976789784.
cc: @gsantoro

**Comment by kaiyan-sheng** [comment]
@ruflin +1! I also suggested working on documentation for how to build integrations (especially with lightweight module) for our team for 8.6.0 planning.

**Comment by kaiyan-sheng** [comment]
@tommyers-elastic I think this meta issue is ready to be closed now.
