### ISSUE TITLE
[meta] ECS 8.3 Updates (Security External Integrations)

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#3200]
This is a meta issue to track ECS 8.3 updates to Fleet integrations maintained by the `elastic/security-external-integrations` team.

### ECS 8.3 Changes

This is a summary of the changes in ECS 8.3. You can view the official changelog [here](https://github.com/elastic/ecs/blob/8.3/CHANGELOG.next.md#830-soft-feature-freeze).

#### Added

* Added `pattern` attribute to `.mac` fields. #1871
* Add `orchestrator.cluster.id` #1875
* Add `orchestrator.resource.id` #1878

### Integrations

TODO: This list will be refined by bucketing it based packages that are affected and are not affected by the ECS changes.

- [ ] 1password
- [ ] akamai
- [ ] atlassian_bitbucket
- [ ] atlassian_confluence
- [ ] atlassian_jira
- [ ] auditd
- [ ] auth0
- [ ] barracuda
- [ ] bluecoat
- [ ] carbon_black_cloud
- [ ] carbonblack_edr
- [ ] cef
- [ ] checkpoint
- [ ] cisco
- [ ] cisco_asa
- [ ] cisco_duo
- [ ] cisco_ftd
- [ ] cisco_ios
- [ ] cisco_ise
- [ ] cisco_meraki
- [ ] cisco_nexus
- [ ] cisco_secure_endpoint
- [ ] cisco_umbrella
- [ ] cloudflare
- [ ] crowdstrike
- [ ] cyberark
- [ ] cyberarkpas
- [ ] cylance
- [ ] f5
- [ ] fim
- [ ] fireeye
- [ ] fortinet
- [ ] gcp
- [ ] gcp_pubsub
- [ ] github
- [ ] google_workspace
- [ ] hashicorp_vault
- [ ] hid_bravura_monitor
- [ ] http_endpoint
- [ ] httpjson
- [ ] imperva
- [ ] infoblox
- [ ] iptables
- [ ] juniper
- [ ] juniper_junos
- [ ] juniper_netscreen
- [ ] juniper_srx
- [ ] keycloak
- [ ] m365_defender
- [ ] mattermost
- [ ] microsoft
- [ ] microsoft_defender_endpoint
- [ ] microsoft_dhcp
- [ ] microsoft_sqlserver
- [ ] mimecast
- [ ] modsecurity
- [ ] mysql_enterprise
- [ ] netflow
- [ ] netscout
- [ ] netskope
- [ ] network_traffic
- [ ] o365
- [ ] okta
- [ ] oracle
- [ ] osquery
- [ ] panw
- [ ] panw_cortex_xdr
- [ ] pfsense
- [ ] proofpoint
- [ ] pulse_connect_secure
- [ ] qnap_nas
- [ ] radware
- [ ] santa
- [ ] snort
- [ ] snyk
- [ ] sonicwall
- [ ] sophos
- [ ] squid
- [ ] suricata
- [ ] symantec_endpoint
- [ ] tcp
- [ ] tenable_sc
- [ ] ti_abusech
- [ ] ti_anomali
- [ ] ti_cybersixgill
- [ ] ti_misp
- [ ] ti_otx
- [ ] ti_recordedfuture
- [ ] ti_threatq
- [ ] tomcat
- [ ] udp
- [ ] winlog
- [ ] zeek
- [ ] zerofox
- [ ] zoom
- [ ] zscaler
- [ ] zscaler_zia
- [ ] zscaler_zpa

**Comment by andrewkroh** [comment]
It's going to be difficult to implement the MAC address formatting because there are parts of Beats producing these fields.

- Modify Beats to format the MACs before sending.
  - The code change is rather simple. https://github.com/andrewkroh/beats/commit/0bbcb1fc715b332c474cde9081b53e1b09d6c910
  - Impacts Beat users. IMO we only want to impact Agent data.
  - Doesn't fix the problem for older Agent versions. Integration system tests use 7.17 in a lot of cases.
    - We could raise the required stack version to ^8.3.0.

- Add a processor to the Fleet final pipeline.
  - Adds unnecessary processing costs to some integrations.
  - Not all data ingestion paths should be subjected to ECS rules.
- Have Agent inject a Beat processor into the Beat configuration to format the MAC.
  - Does not fix data coming from older Agent versions.
- Modify every integration that uses add_host_metadata to have an ingest node processor to format `host.mac`.
  - Touches a lot of integrations.
  - This is only option that I think will work given the constraints. Going forward the inputs and processors in Agent v2 should switch to the ECS mac address format.
