### ISSUE TITLE
Make Vsphere GA

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#3508]
- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists

### Metric dataset changes

_This entry is currently only recommended. It will be mandatory once we provide better support for it._

- [x] Sample event (`sample_event.json`) exists

### Tasks to be Completed:
- [x] Bring up the Vsphere Setup
- [x] Check if all the metrics and logs are being received correctly
- [x] Add the metric_type and unit to all the metrics fields
- [x] Add system tests for host, datastore, virtual machine metrics data streams
- [x] Pipeline Testing should work fine, verify all the log format supported
- [x] Dashboards should be presented by value and not by reference
- [x] Resolve the open issue https://github.com/elastic/integrations/issues/3429

**Comment by ishleenk17** [comment]
Fix https://github.com/elastic/integrations/issues/3429  before making Vsphere GA

**Comment by ishleenk17** [comment]
The Technical doc fror Vsphere: https://docs.google.com/document/d/1xi1CLwSLSoLlPXqI8PgwjcSGmypw_iDHu7huMhbzLpo/edit#

**Comment by ishleenk17** [comment]
This issue will close: 

[Adding new usage metrics](https://github.com/elastic/beats/issues/24401)
[Improve Documentation](https://github.com/elastic/obs-infraobs-team/issues/432)
[Better Documentation ](https://github.com/elastic/beats/issues/22990)
