### ISSUE TITLE
CyberArk Privileged Threat Analytics (PTA)

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#3533]
### Description
CyberArk’s PTA is a modern system designed for privileged account security intelligence that provides detailed, immediate actionable threats analytics by pinpointing previously hidden malicious privileged user activity. Privileged Threat Analytics (PTA) continuously monitors the use of privileged accounts that are managed in the CyberArk Privileged Access Security (PAS) platform, as well as accounts that are not yet managed by CyberArk, and looks for indications of abuse or misuse of the CyberArk platform. PTA also looks for attackers who compromise privileged accounts by running sophisticated attacks, such as Golden Ticket.

For a full list of detections reported by PTA, see [here](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.2/en/Content/PTA/What-Does-PTA-Detect.htm). 

### Architecture
Syslog is supported and events are CEF formatted. Relevant docs [here](https://docs.cyberark.com/Product-Doc/Onlinehelp/PAS/latest/en/Content/PTA/Outbound-Sending-%20PTA-syslog-Records-to-SIEM.htm?TocPath=Administration%7CComponents%7CPrivileged%20Threat%20Analytics%7CConfigure%20Privileged%20Threat%20Analytics%7CSend%20PTA%20Data%7CSend%20PTA%20syslog%20Records%20to%20SIEM%7C_____0). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to:

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes

- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (`sample_event.json`) exists
