### ISSUE TITLE
[Epic] Release Istio integration to Beta

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#3552]
**Context**
Istio is one of the most popular service meshes, its position in the CNCF landscape has helped its adoption and [growing ecosystem](https://istio.io/latest/about/ecosystem/) thus becoming one of the layers that users need to observe to aim for full-stack observability.

**User outcome**
The goal of this work is to increase the breadth of technologies we support the integration outcomes (ingestion and curated data views with dashboards) by enabling users to collect and ingest Istio data

- Elastic cloud operators who are using elastic agent should be able to add the Istio integration 
- The data collected should be metrics, logs and any other metadata available.
- Elastic cloud users should be able to toggle on/off which data they want to collect
- Elastic cloud users who install the Istio integration should have an out of the box dashboard to provide them with correlation relevant to the Istio data collected.

**Tasks to be completed:**

- [x]  Support collection of logs

  - Implement log collection based on default Istio logging provider ([envoy](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-DefaultProviders))
  - Implement log collection based on Json output format

- [x] Implement Metrics collection (relevant [info](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/)) 

- [x]  Istio installation guide in [here](https://github.com/elastic/observability-dev/tree/main/docs/dc/integrations/testing)

- [x] Define some default dashboards as assets to be installed with integration. Minimal samples and this can be enhanced even later

**Relevant backlog stories for reference:**
Create a integrations to collect [Istio](https://istio.io/) logs.
Related to elastic/beats#15505

**Comment by gsantoro** [comment]
5. Should we add a graph visualization (similarly to what we had in metricbeat)?
This is the one from metricbeat (taken from https://www.elastic.co/blog/istio-monitoring-with-elastic-observability) where we connect source_app to destination_app and response_code
![Screenshot 2022-11-01 at 17 18 18](https://user-images.githubusercontent.com/2378291/199295928-3801730d-a926-4917-8b08-5e86fd965896.png)

Instead of the previous one, I would suggest to graph `source/destination workload` instead. Each source/destination app can have multiple versions (like api versions). I believe that this other metric label gives more useful details for the user.
![Screenshot 2022-10-28 at 13 21 15](https://user-images.githubusercontent.com/2378291/199297046-9177bfc6-3d45-4594-bddd-05d00de44620.png)

**Comment by gsantoro** [comment]
6. I have generated some more graphs. What do you guys think about them? Can we embed them with the integration?

![Screenshot 2022-11-02 at 10 10 27](https://user-images.githubusercontent.com/2378291/199463276-70b33554-29e6-4ad2-bd8f-e6d651d92ac2.png)
![Screenshot 2022-11-02 at 10 11 37](https://user-images.githubusercontent.com/2378291/199463286-a35d5ec2-a9bc-499e-af9a-f561789e612b.png)
![Screenshot 2022-11-02 at 10 11 50](https://user-images.githubusercontent.com/2378291/199463290-419588dc-343a-4529-ad77-6ae1cc090c41.png)

There is this concept of drilldown that would enable us to click on one of those graph nodes to navigate to another kibana page (eg. discovery or dashboards). Should we investigate it for this iteration?

**Comment by gsantoro** [comment]
7. Istiod dashboards
![Screenshot 2022-11-02 at 12 33 25](https://user-images.githubusercontent.com/2378291/199490909-fdf0bfc2-2edb-4286-8f41-11a034040b56.png)

![Screenshot 2022-11-02 at 12 33 19](https://user-images.githubusercontent.com/2378291/199490902-debc0ffb-6d33-412b-bc1d-7259a04cdbd3.png)

**Comment by gsantoro** [comment]
1. Ok. I'll try to migrate them all to Lens. I'll take notes of limitations and write them down. We are going to have a mix of lens and TSDB
2. Ok. I don't have a strong opinion on this. I'll revert the naming back to Overview and Traffic
3. Great I'll keep the new tag cloud as well
4. Cool I'll keep the controllers
5. About the graphs, I can't embed them into the dashboard. Do we want to still use them? can we put them into the integrations? Mostly I am asking since in that blog post you created some.

**Comment by gsantoro** [comment]
Limitations of using Lens for Istio dashboard:
- Gauge visualisation is not available in Lens (as it is). There is a technical preview of a gauge but it doesn't provide the same functionalities
- Line chart with percentile in TSDB allow to have multiple percentiles in the same chart (eg. 25, 50, 75, 95, 99 percentiles). We would need 5 different charts to represent 1 in the TSDB version. 
- Some metrics are in milliseconds and are converted to seconds by the TSDB visualisation. Lens dashboard doesn't support "Duration" format
- Mixing and matching Lens and TSDB visualisations will give a non homogeneous look to the entire dashboard, so for this iteration I'll stick to TSDB for the entire dashboard.

**Comment by mlunadia** [comment]
1. Let's use what gives the best result for the user.
2. If you think it makes more sense for the user to have the name as the source, I support this based on simplicity
3. +1 add it
4. Given that you have most context with Istio I think things like this are a useful change and see no problem on exploring them.

**Comment by mlunadia** [comment]
Given the comments above let's for TSDB over lens for these dashboards

**Comment by gizas** [comment]
1. In general indeed Lens is the suggested way to go. 
I attach two more docs for references:
https://docs.google.com/document/d/1uyyFGx6xA5Kvl8c-ZdvXdvBGrHTylxU9F69TGqfzdmw/edit
https://docs.google.com/document/d/1_7ZYOO5KsSG4J3ovdlB4obBF5i0FQfsiXrRtI3wWFpg/edit#heading=h.gi2lpayry05p

For Gauges I would say to give an extra effort  with Lens if possible. For chart the changes are big so ok leave them as is.

2. You can enhance the markdown with sample text to explain what is what. I think some text can be helpful whatever title you put

3. +1 add it

4. Mind to add the latest controllers (not the old ones which are deprecated) 

5. For graph I would say remove it. Although beautiful dont see the actual value to users

Ingress, Egress Traffic will be valuable to this dashbaords?
In many dashboards we have Title and same subtitle in the bottom. Keep only one
And also (I know is painfull) keep a consistency in colours. For eg all lines to be green or blue

**Comment by gsantoro** [comment]
Mostly for @gizas but left here for posterity

1. about the gauges. This is the comparison for the same metric

![Screenshot 2022-11-03 at 09 30 45](https://user-images.githubusercontent.com/2378291/199687235-f1e2e1d2-ff9b-4e03-a8da-62b3200964e9.png)

The top one is from TSDB, the second one is from Lens. No need for comments 😄 

2. What would you suggest as text for the dashboards? Do you have an example?
3. ok
4. Yes, I am using the latest controllers.
5. There is no way to embed the graph in the integration anyway. So I won't include them
6. I am not sure if there are metrics about Ingress and Egress. I'll have a look
7. I assume you mean about the Gauge having both titles on top and at the bottom. I managed to find a way just now to remove the bottom title. It looks a bit hacky though. You need to provide a Custom Label = " " (that's a blank space). I'll update them all
8. About the consistency of the lines. For all the charts with a single line they are blue. All the other ones are using the default palette since they need to use many colours for the many different labels (eg. source or destination labels).

Thanks for the feedback

**Comment by gizas** [comment]
Something like below with title "Istiod" and second "Proxy" and short description what we see, or any importan information for how you should read the dashboards

![Screenshot 2022-11-03 at 1 15 10 PM](https://user-images.githubusercontent.com/1685415/199707335-58c0902e-07cf-466b-8a0a-bde2a582120c.png)
