### ISSUE TITLE
Google Workspace | DLP audit log support

### ISSUE THREAD

**Issue by pedrosk** [elastic/integrations#4079]
There is a need to collect the DLP alerts from the Alerts center, the api access is "https://admin.googleapis.com/admin/reports/v1/activity/users/all/applications/rules?eventName=action_complete" and to have the correct mapping to work with the alerts. 

It does not seem that any integrations exist at the moment. 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by 4rth4S** [comment]
+1

**Comment by jamiehynds** [comment]
@4rth4S and @pedrosk - we're currently working on a Workspace Alerts integration, which will support ingestion of Workspace Alerts, fully mapped to ECS, including DLP alerts. You can view the PR [here](https://github.com/elastic/integrations/pull/3837). 

Could you confirm if support for these alerts will meet your needs, or do you also require support for [Workspace Rules log ](https://support.google.com/a/answer/9656783) also?

**Comment by jamiehynds** [comment]
Closed via https://github.com/elastic/integrations/issues/3277
