### ISSUE TITLE
[META] Azure Logs integration doc update

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#4169]
Some users struggle to properly set up the Azure Logs integration for their use cases.

In general, we need to add more details about Event Hub: what it is, its role, the moving parts, and how to configure it.

Recurring difficult points from support and direct user conversations:

- [ ] (1) **Collective vs individual integration** — It is not clear what's the difference between "collective" integrations (for example, Azure Logs) and the "individual" integrations (for example, Activity logs).
- [x] (2) **How many Event Hubs are required?** — Can we use one event hub for all integrations, or should we use one for each? UPDATE: addressed in #4300
- [ ] (3) **Fine-grained vs generic mapping** — some integration can ingest any log category with minimal parsing; others support only one log category but with full parsing. Users need to know which one fits their best. 
- [x]  (4) **Lack of setting options descriptions** UPDATE: addressed in #4300
- [x] (5) **Event Hubs vs Event Hub (main vs sub)** UPDATE: addressed in #4300

We must update the Azure Logs integration to address all these pain points and make the user experience smoother.

Additional updates:

 - [ ] Document how the generic event hub integration works (upsides, trade-offs)
