### ISSUE TITLE
MSSQL integration updates needed

### ISSUE THREAD

**Issue by lalit-satapathy** [elastic/integrations#4238]
### Named [instance support](https://github.com/elastic/integrations/issues/4431) 

Currently the integration supports named instance via [dynamic ports](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver15).  Enhancements needed for named instance support.

https://github.com/elastic/integrations/issues/4431

   * [X]  Named Instance support #4257
   * [x]  Metrics mapping to instance or database. Get instance name from SQL Server instance,  We should make sure the metrics displayed can be associated either to instance or database; it should be clear for the user to which instance the metrics above belong. https://github.com/elastic/integrations/issues/4259 
   * [X] The current integration does not support passing multiple ports. This is resolved as part of the the [PR] (https://github.com/elastic/integrations/pull/4501). Port will be passed as part of the host configuration.

### Password parsing issue
Generic SQL "hosts" is compiled inline using user passed "password". While it is working for some special characters and it fails for some. Refer the [issue](https://github.com/elastic/beats/issues/30947).
   * [X] Alternative solution provided. https://github.com/elastic/integrations/issues/4198#issuecomment-1269960456
   * No other plans  on password post-processing currently.

### Additional metrics
 **Planned for 8.7**
- [x] Explore support a list of "Dynamic Counter Name" can be passed instead of just one. https://github.com/elastic/integrations/issues/4432
- [x] Add additional metrics like "deadlock" performance counters.  List from @pmeresanu85. Finalise whether new data stream of existing data stream for these.
[new-counters.txt](https://github.com/elastic/integrations/files/9722323/new-counters.txt)

### Support user databases.
Supporting additional user database for transaction logs metrics.
- [ ] https://github.com/elastic/integrations/issues/4258 and https://github.com/elastic/integrations/issues/4108 
  -  [X] Short-term solution where user database can be manually provided is [done](https://github.com/elastic/integrations/pull/4869). 

### Merge Results.

- [x] Enable [merge_results](https://github.com/elastic/integrations/issues/4433) for performance data_stream

**Comment by Danouchka** [comment]
An important thing is to know if those metrics are per named instance or per named instance / database name ... For instance, we could have some naming prefix convention like mssql.metrics.instance.** or mssql.metrics.database.*

**Comment by pmeresanu85** [comment]
@lalit-satapathy let's make sure we fix the explicit password problem as well in the integration

**Comment by lalit-satapathy** [comment]
Issues reference:
https://github.com/elastic/integrations/issues/4257
https://github.com/elastic/integrations/issues/4258
https://github.com/elastic/integrations/issues/4259
https://github.com/elastic/integrations/issues/4260
https://github.com/elastic/integrations/issues/4272

Issue for reference:
https://github.com/elastic/integrations/issues/4244

**Comment by muralidharanvenkataraman** [comment]
I am working with a client here and found that two lines were merged into a single line for the sql server error log.  We figured out that it was due to the encoding and by adding this line to the config.yml file, the logs were parsed correctly.

`encoding: utf-16le`

a) Is there a possibility to add this as option within the integration UI
b) Support the ability to ignore files older than a certain time frame

Thanks
Murali

**Comment by lalit-satapathy** [comment]
> I am working with a client here and found that two lines were merged into a single line for the sql server error log. We figured out that it was due to the encoding and by adding this line to the config.yml file, the logs were parsed correctly.
> 
> `encoding: utf-16le`
> 
> a) Is there a possibility to add this as option within the integration UI b) Support the ability to ignore files older than a certain time frame
> 
> Thanks Murali

Lets file and track this in separate github issue.

**Comment by pmeresanu85** [comment]
@lalit-satapathy is there any update on this enhancement request?

**Comment by lalit-satapathy** [comment]
Individual [issues](https://github.com/elastic/integrations/issues/4238#issue-1379211116) listed above in the meta issue will track specific progress. 

One of the critical "Named Instance support" [issue](https://github.com/elastic/integrations/issues/4431) has been fixed [PR](https://github.com/elastic/integrations/pull/4501) is merged.

**Comment by mholttech** [comment]
Any idea on when support for User defined Databases will be added? Without this the SQL Metrics integration is completely useless.

**Comment by mholttech** [comment]
Any updates on when additional metrics will be added? The issue description mentioned that it was planned for 8.7 release, but it does not appear that any work has been done.

**Comment by lalit-satapathy** [comment]
> Any updates on when additional metrics will be added? The issue description mentioned that it was planned for 8.7 release, but it does not appear that any work has been done.

You can provide user DBs [manually](https://github.com/elastic/integrations/pull/4869) and run the integration as of now.

**Comment by mholttech** [comment]
What about automatic database discovery and the additional metrics that are mentioned? It's great that user databases can be defined manually but we are a large enterprise with hundreds of SQL Clusters and countless databases hosted in those clusters. Also without the additional metrics there is a huge gap in capabilities compared to our legacy solution using System Center Operations Manager.

> Add additional metrics like "deadlock" performance counters. List from @pmeresanu85. Finalise whether new data stream of existing data stream for these.
> [new-counters.txt](https://github.com/elastic/integrations/files/9722323/new-counters.txt)

**Comment by mholttech** [comment]
It seems like no progress is being made in making this more usable and providing meaningful performance counters. #4903 for supporting automatic discovery of databases also seems to be stalled out. The lack of comprehensive performance monitoring continues to be a blocker in our adoption as we cannot properly monitor our MSSQL Servers, forcing us to keep legacy tooling in place specifically for this. Is this still being worked on?

**Comment by lalit-satapathy** [comment]
@mholttech, We are not expanding any new performance counters currently. However there is a way to pass "Dynamic Counters" for performance metrics. Have you tried this [same](https://docs.elastic.co/en/integrations/microsoft_sqlserver)?
<img width="865" alt="Screenshot 2023-05-17 at 9 41 02 PM" src="https://github.com/elastic/integrations/assets/69236064/21a66295-74b0-4293-bd09-700f9ebe3271">

**Comment by mholttech** [comment]
Thanks @lalit-satapathy, i'll research this. Any chance of getting #4903 implemented? We have over 800 SQL Servers and it'll be a large undertaking having to identify & configure each database to monitor on each SQL Server

**Comment by mholttech** [comment]
Hi @lalit-satapathy,

After reviewing the implementation of this [here](https://github.com/elastic/integrations/blob/a5ae00805943522fbb6d7fe793628ed921bd0c51/packages/microsoft_sqlserver/data_stream/performance/agent/stream/stream.yml.hbs#L46-L47C22) & speaking with some of our DBA's this will not be a usable solution. 

The Dynamic Counters option only accounts for the Counter Name, ignoring the fact that the counter name can be duplicated across Object Names, or more commonly there can be multiple instance_names for the same counter. The way the dynamic counters query is structured it has no way of differentiating between instance_names.

A few of the use cases they have are:

## Case 1
```
SELECT *
  FROM sys.dm_os_performance_counters
 WHERE counter_name = 'Number of Deadlocks/sec'
```

This results in 15 different counters with different instance_names, they need the `_Total` instance_name which they would normally query with:

```
SELECT *
  FROM sys.dm_os_performance_counters
 WHERE object_name = 'SQLServer:Locks'
   AND counter_name = 'Number of Deadlocks/sec'
   AND instance_name = '_Total'
```

## Case 2

```
SELECT *
  FROM sys.dm_os_performance_counters
  WHERE counter_name = 'Errors/sec'
```

This results in 5 different instance_names, our DBA's need instance_names `User Errors`, `Kill Connection Errors`, & `DB Offline` Errors.

## Case 3

```
SELECT *
  FROM sys.dm_os_performance_counters
  WHERE counter_name = 'Log Growths'
```

This results in 8 different instance_names, they need the instance_name `_Total`

**Comment by Danouchka** [comment]
Hi @mholttech 

I dont really see a problem here:

- Having same counters for different instance names is not an issue because each metrics come with the instance name 
- As to the total, it can be aggregated by elasticsearch on any visualization of your own 

Unless I am missing something ... for my own curiosity (I am not a DBA) but is `_Total` a virtual instance name of MSSQL servers ...?

**Comment by mholttech** [comment]
@Danouchka,

If you look at the implementation of the query being run for Dynamic Counters [here](https://github.com/elastic/integrations/blob/a5ae00805943522fbb6d7fe793628ed921bd0c51/packages/microsoft_sqlserver/data_stream/performance/agent/stream/stream.yml.hbs#L46-L47C22) you can see that the data collected does not extract instance_name so there is no differentiation between the different instance names.

So, when I run the query as built in the integration:

```
SELECT counter_name, cntr_value FROM sys.dm_os_performance_counters WHERE counter_name like 'Log Grow%'
```

It returns:

| counter_name | cntr_value |
| --- | --- |
Log Growths | 0
Log Growths | 0
Log Growths | 1
Log Growths | 0
Log Growths | 0
Log Growths | 0
Log Growths | 1
Log Growths | 0

If I modify it to

```
SELECT counter_name, instance_name, cntr_value FROM sys.dm_os_performance_counters WHERE counter_name like 'Log Grow%'
```

It returns:

| counter_name | instance_name | cntr_value | 
|  --- | --- | --- |
Log Growths | OperationsManager | 0
Log Growths | OperationsManagerDW | 0
Log Growths | tempdb | 1
Log Growths | model | 0
Log Growths | mssqlsystemresource | 0
Log Growths | msdb | 0
Log Growths | _Total | 1
Log Growths | master | 0


I wouldn't mind being limited to Dynamic Counters returning all of them, as long as the instance_name context is available. It would also be useful to be able to define multiple counter names. Right now you can only define one pattern which is also very limiting.

In the meantime, I've began exploring the [SQL Input](https://github.com/elastic/integrations/tree/a5ae00805943522fbb6d7fe793628ed921bd0c51/packages/sql_input) integration and it looks promising, however it is missing the ability to merge multiple queries into a single event as documented in the underlying metricbeat integration [here](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-sql.html#_example_merge_multiple_queries_to_single_event).

**Comment by Danouchka** [comment]
OK understood ! Good Catch, Thanks

**Comment by mholttech** [comment]
I have opened #6243 since the new SQL Input integration is very close to filling the gap. It is missing the merge_results option, but if that is added we will then be able to easily add any additional SQL performance metrics that our DBAs desire.

That only leaves a gap in automatic discovery of the databases which has stalled under #4903. While we can add database names individually, automatic discovery of the databases will simplify the onboarding process of our 800+ MSSQL Servers.

**Comment by mholttech** [comment]
I've been able to work around the merge_results limitation by using "UNION ALL" to combine multiple quires into a single query.  Would still be nice to see merge_results implemented to make it easier though

Here's what i'm running in the SQL Input plugin for anyone looking to do the same,

```
- query: "SELECT REPLACE(concat(object_name, ' ', counter_name, instance_name),'  ', '') as counter_name, convert(varchar(12),cntr_value) as cntr_value FROM sys.dm_os_performance_counters WHERE counter_name LIKE 'Processes blocked%' UNION ALL SELECT REPLACE(concat(object_name, ' ', counter_name, ' ', instance_name),'  ', '') as counter_name, convert(varchar(12),cntr_value) FROM sys.dm_os_performance_counters WHERE ( object_name = 'SQLServer:SQL Errors' AND counter_name = 'Errors/sec' AND instance_name in ('User Errors', 'Kill Connection Errors', 'DB Offline errors')) UNION ALL SELECT REPLACE(concat(object_name, ' ', counter_name, instance_name),'  ', '') as counter_name, convert(varchar(12),cntr_value) FROM sys.dm_os_performance_counters  WHERE (object_name = 'SQLServer:Databases' AND counter_name = 'Log Growths' AND instance_name = '_Total') UNION ALL select 'server_name' as counter_name, @@SERVERNAME as cntr_value UNION ALL select 'instance_name' as counter_name, @@servicename as cntr_value"
  response_format: variables
```

I have the data_stream set to `microsoft_sqlserver.performance.custom` and run the data through this custom pipeline

```
PUT _ingest/pipeline/metrics-microsoft_sqlserver.performance.custom@custom
{
  "processors": [
    {
      "remove": {
        "field": "sql.driver",
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "remove": {
        "field": "sql.query",
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "rename": {
        "field": "sql",
        "target_field": "mssql",
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "trim": {
            "field": "_ingest._key",
            "ignore_missing": true
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": " ",
            "replacement": "_"
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "/",
            "replacement": "_"
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": ">",
            "replacement": "_"
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": ":",
            "replacement": "_"
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "\\(",
            "replacement": ""
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "%",
            "replacement": "pct"
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "\\)",
            "replacement": ""
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "__",
            "replacement": "_"
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "sqlserver_",
            "replacement": ""
          }
        },
        "ignore_failure": true
      }
    },
    {
      "foreach": {
        "field": "mssql.metrics",
        "processor": {
          "gsub": {
            "field": "_ingest._key",
            "pattern": "sql_errors_errors_sec",
            "replacement": "sql_errors_per_sec"
          }
        },
        "ignore_failure": true
      }
    }
  ],
  "on_failure": [
    {
      "set": {
        "field": "error.message",
        "value": "{{ _ingest.on_failure_message }}"
      }
    }
  ]
}
```

I think created this custom pipeline

**Comment by SubhrataK** [comment]
> I have opened #6243 since the new SQL Input integration is very close to filling the gap. It is missing the merge_results option, but if that is added we will then be able to easily add any additional SQL performance metrics that our DBAs desire.
> 
> That only leaves a gap in automatic discovery of the databases which has stalled under #4903. While we can add database names individually, automatic discovery of the databases will simplify the onboarding process of our 800+ MSSQL Servers.

@mholttech The automatic discovery of the databases is on our roadmap and we are looking into it. We do not have a timeline as of now, by when we can ship this feature. 

The additional SQL performance metrics, is low on our priority list currently.  Please feel free to set up a call with us, so that we can discuss the requirements.

**Comment by Danouchka** [comment]
Yess, that's great all the progress done so far

**Comment by lalit-satapathy** [comment]
Closing per [above](https://github.com/elastic/integrations/issues/4238#issuecomment-1835676304).
