### ISSUE TITLE
Airflow Migration Subtasks

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#4465]
# Airflow Integration Subtasks

These subtasks are intended to track the  progress while creating a Package or Dataset for an Integration.

### Set up Airflow Environment and Run

- [x] Setup, install and configure Airflow
- [x] Run StatsD

### Run Airflow Metricbeat

- [x] Get the metrics in ES

### Run Statsd Metricbeat

- [x] Get the metrics in ES

### Create Dummy Airflow Integration using statsD as Input

- [x] Get the metrics in ES

### Configure and complete Datastream 

- [x] Add StatsD datastream
- [x]  Configure all fields.yml, ecs.yml, manifest.yml and any ingest pipeline if needed.

### Create Dashboards

- [x] Add Dashboards
- [x] Datastream filters added to visualizations

### Write System Test Cases

- [ ] Write system test case for statsd datastream

### Tracking Task of
- https://github.com/elastic/integrations/issues/3748

**Comment by ritalwar** [comment]
Initial beta release [PR](https://github.com/elastic/integrations/issues/3748) merged.
Task for Dashboads: https://github.com/elastic/integrations/issues/5001

**Comment by ritalwar** [comment]
Dashboards [PR](https://github.com/elastic/integrations/issues/5001) merged.
Pending: System Test cases.

**Comment by lalit-satapathy** [comment]
@ritalwar should we close this and create backlog task for system test?

**Comment by ritalwar** [comment]
Sure, @lalit-satapathy . I will create a task for it and add it to the backlog. After that, I will close this meta.

**Comment by ritalwar** [comment]
System test cases are the only pending task, which can be tracked here: https://github.com/elastic/integrations/issues/6282.
