### ISSUE TITLE
[Stack Monitoring] Add missing period field to data stream manifests

### ISSUE THREAD

**Issue by mohamedhamed-ahmed** [elastic/integrations#4910]
### Summary
The [period](https://github.com/elastic/integrations/blob/5a86ebb86dabc94e8f4b23b6363d4e3ef7eb59ba/packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs#L13) parameter can be defined by user we don't have a corresponding input in the [manifest](https://github.com/elastic/integrations/blob/5a86ebb86dabc94e8f4b23b6363d4e3ef7eb59ba/packages/elasticsearch/data_stream/ccr/manifest.yml) that would allow that.
We need to define the field in the data stream's manifest and not the package's to allow more fine grained control.

### Implementation hints
- Go through the [stream](https://github.com/elastic/integrations/blob/5a86ebb86dabc94e8f4b23b6363d4e3ef7eb59ba/packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs) files where the period is defined and check the relevant [manifest](https://github.com/elastic/integrations/blob/5a86ebb86dabc94e8f4b23b6363d4e3ef7eb59ba/packages/elasticsearch/data_stream/ccr/manifest.yml) file to make sure that a respective field is defined.

### Tasks
- [x] https://github.com/elastic/integrations/pull/5141
- [x] https://github.com/elastic/integrations/pull/4926
- [x] https://github.com/elastic/integrations/pull/5201
- [x] https://github.com/elastic/integrations/pull/5202
- [x] ~beats~ already has it
  - [stats](https://github.com/elastic/integrations/blob/main/packages/beat/data_stream/stats/manifest.yml)
  - [state](https://github.com/elastic/integrations/blob/main/packages/beat/data_stream/state/manifest.yml)

**Comment by crespocarlos** [comment]
@mohamedhamed-ahmed , is [this](https://github.com/elastic/integrations/blob/main/packages/elasticsearch/manifest.yml) an example of a manifest that should have `period` parameter added?

**Comment by mohamedhamed-ahmed** [comment]
> @mohamedhamed-ahmed , is [this](https://github.com/elastic/integrations/blob/main/packages/elasticsearch/manifest.yml) an example of a manifest that should have `period` parameter added?
@crespocarlos  yes we are missing the period field in this manifest, but we were thinking that it would be better to add this field per [data stream](https://github.com/elastic/integrations/blob/5a86ebb86dabc94e8f4b23b6363d4e3ef7eb59ba/packages/elasticsearch/data_stream/ccr/manifest.yml) and not on the level of the package.
