### ISSUE TITLE
[Meta] Input Package : IM Ecosystem

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#4945]
This is a meta issue that tracks all the Input Packages built by IM Ecosystem Team
Know more about Input packages from [here](https://docs.google.com/document/d/1vzBh2frnlxEBBcab8-ist8pu_PDZUjOHdsV-QuUn_WA/edit)
### IM Ecosystem Input Packages

- [x] Jolokia Input package
    - [x] Initial development of [Jolokia Input Package](https://github.com/elastic/integrations/issues/4498)
    - [x] [Enhancements](https://github.com/elastic/integrations/issues/4957) for Jolokia Input Package
    - [x] [System Tests for Jolokia Input Package](https://github.com/elastic/integrations/issues/5341)
- [ ] Statsd Input Package
    - [x] Initial development of [Statsd Input Package](https://github.com/elastic/integrations/issues/4809)
    - [ ] [Enhancements](https://github.com/elastic/integrations/issues/4958) for Statsd Input Package
    - [x] [System Tests for Statsd Input Package](https://github.com/elastic/integrations/issues/6284)
- [x] SQL Input Package
    - [x] [Generic SQL](https://github.com/elastic/integrations/issues/5078) Input package
    - [x] [System Tests for SQL Input Package](https://github.com/elastic/integrations/issues/6285)
    - [x] Enhancements of SQL Input Package
         - [x] [Support of merge_results](https://github.com/elastic/integrations/issues/6243)
         - [x] [Period Configuration](https://github.com/elastic/integrations/issues/6122)
- [ ] Prometheus Input Package
    - [x] [Scoping](https://github.com/elastic/integrations/issues/5845) of Prometheus Input Package
    - [x] [Prometheus](https://github.com/elastic/integrations/issues/4615) Input package
    - [x] [System Tests for Prometheus Input Package](https://github.com/elastic/integrations/issues/6286)
    - [ ] [Enhancements](https://github.com/elastic/integrations/issues/6320) of Prometheus Input Package

#### Generic Input Package Tasks
- [x] [Update kibana version to 8.8.0](https://github.com/elastic/integrations/issues/6323)
- [ ] Rerouting in Input Packages
    
cc: @ruflin @elastic/obs-service-integrations

**Comment by ishleenk17** [comment]
Some of the open dependencies for Input package: 

1. Custom Ingest Pipelines not working https://github.com/elastic/kibana/issues/145529
2. System Tests not available https://github.com/elastic/package-spec/issues/361

**Comment by ishleenk17** [comment]
> Hi @ishleenk17,
> 
> Is there any plan to have sample events (in the documents) for the input packages being released? How will a new user learn the structure of documents to be ingested by the input packages?

We can have some sample events once system tests are completed. 
But since an input package will always be agnostic of what service the customer is using for that package, the sample events will vary accordingly. Hence, I am not sure if it would add much value there

**Comment by ishleenk17** [comment]
In 8.7, the index gets created for the input package after this [issue](https://github.com/elastic/kibana/issues/145529) was resolved, but still we are unable to add the ingest pipeline and custom mappings. 
https://github.com/elastic/kibana/issues/145529 is tracking the issue.
