### ISSUE TITLE
[Meta] Check Point Integration Enhancements

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5109]
This issue is intended to track enhancements and bug fixes to the Check Point firewall integration, to ensure the integration continues to remain relevant, performant and reliable. 

**OS Compatibility**
- [x] https://github.com/elastic/integrations/issues/5079

**Documentation**
- [x] https://github.com/elastic/integrations/issues/5113
- [x] https://github.com/elastic/integrations/issues/5002

**Dashboard**
- [x] https://github.com/elastic/integrations/issues/5111

**Parsing/Bug Fixes**
- [x] https://github.com/elastic/integrations/issues/2723
- [x] https://github.com/elastic/integrations/issues/5107
- [x] https://github.com/elastic/integrations/issues/5108
- [x] https://github.com/elastic/integrations/issues/5110
- [x] https://github.com/elastic/integrations/issues/5126

**Comment by efd6** [comment]
Completed.
