### ISSUE TITLE
[Meta] Create Package for Apache Tomcat Integration

### ISSUE THREAD

**Issue by SubhrataK** [elastic/integrations#5200]
The overall scope of this integration is to cover the below mentioned logs and metrics. This will be phased out in multiple releases.

- Access Logs
- Catalina Logs
- Localhost Logs
- Request Metrics
- Cache Metrics
- Thread Pool Metrics
- Memory Metrics
- Connection Pool Metrics
- Session Metrics

As part of Phase 1 of this integration, the following are covered:

# Apache Tomcat

### Data stream: cache
  - [x] Create data stream related to Apache Tomcat cache metrics
    - #5424

### Data stream: access
  - [x] Create data stream related to Apache Tomcat access metrics
    - #5883

### Data stream: catalina
  - [x] Create data stream related to Apache Tomcat catalina logs
    - #5926 

### Data stream: localhost
  - [x] Create data stream related to Apache Tomcat localhost logs
    - #5983

### Data stream: request
  - [x] Create data stream related to Apache Tomcat request metrics
    - #6003 

### Deprecate Tomcat package
- [x] Rename `Tomcat` integration to `Tomcat NetWitness Logs` and add deprecation note in README
    - #6091
- [x] Add Add link of new “apache_tomcat” package in README.
    - #6124 

# **Phase 2 data streams:**

### Data stream: ConnectionPool
  - [x] Create data stream related to Apache Tomcat ConnectionPool metrics
    - Issue: #6389
    - PR: #6596 

### Data stream: ThreadPool
  - [x] Create data stream related to Apache Tomcat ThreadPool metrics
    - Issue: #6387 
    - PR: #6609

### Data stream: Memory
  - [x] Create data stream related to Apache Tomcat Memory metrics
    -  Issue: #6388
    - PR: #6527  

### Data stream: Session
  - [x] Create data stream related to Apache Tomcat Session metrics
    - Issue: #6391 
    - PR: #6573

### In-review PRs

- #6788 

### Related Issues
  - #6777
  - #7098
  - #6750
  - #6890
  - #6934

### TSDB Issue
  - #6099

### Enhancement Requests
- [x] #7204
   - Support multiline parser for multiple date formats and support Log4j format for the Catalina and Localhost data streams
- [x] #7635
   - The forwarded tag will enable the `publisher_pipeline.disable_host: true`, which is the functionality of a Filebeat input setting that only applies to Filebeat-based integrations. The Apache Tomcat metrics data streams are using Metricbeat-based input. Hence need to remove the forwarded tag for metrics data streams.
- [ ] #7634 
   - In the Filebeat-based integrations, support the description related to the forwarded tag information.
- [ ] #7584
   - A user is testing to ingest JIRA access logs via Tomcat integration. However, the log parsing fails because of the wrong log pattern. Need to support the log format that is being used.
- [x] #7773
   - If the user hasn't `%A %X %T` or one of them, need to update the grok pattern by making the fields optional so that user can ingest the data without any error.
- [x] #7622
   - Fix ingest pipeline tests and update X-forwared-for IP field from `header_forwarder` to `client.ip`

### Troubleshooting docs / issues
- #8365
  - Update By Query API steps that can help rename fields for ingested documents.

**Comment by niraj-elastic** [comment]
As discussed with @ishleenk17, localhost logs are collected as part of this scope since it helps users to monitor [application activity.](https://docs.progress.com/bundle/pas-for-openedge-management/page/Configure-Tomcat-and-Tomcat-web-application-logging.html#:~:text=.log%E2%80%94-,Web%20application%20activity,-.%20The%20default%20Tomcat) and  It monitors HTTP transactions between the application server and the client.

**Comment by ishleenk17** [comment]
We will be creating a new package for Apache Tomcat (with version 0.0.1) in Technical Preview. 
The older package will be slowly deprecated. We should add "To be deprecated" in the title of the Integration and point to the new integration from the older one.

**Comment by niraj-elastic** [comment]
As discussed with @ishleenk17,  filestream input will be used over TCP/UDP inputs for all the logs data streams for now.

**Comment by SubhrataK** [comment]
> We will be creating a new package for Apache Tomcat (with version 0.0.1) in Technical Preview. The older package will be slowly deprecated. We should add "To be deprecated" in the title of the Integration and point to the new integration from the older one.

The existing package shall be renamed as "Tomcat NetWitness Logs" and the new package shall be named as "Apache Tomcat". 
The documentation of the "Tomcat NetWitness Logs" shall be updated to add "To be deprecated" and a link to the new "Apache Tomcat" integration. The new Apache Tomcat integration shall be in Beta.

**Comment by lalit-satapathy** [comment]
> The existing package shall be renamed as "Tomcat NetWitness Logs" and the new package shall be named as "Apache Tomcat".

Package name in manifest file to be all lower case. Instead of renaming the existing package directory, we can change the title and/or the description?

**Comment by ishleenk17** [comment]
> > The existing package shall be renamed as "Tomcat NetWitness Logs" and the new package shall be named as "Apache Tomcat".
> 
> Package name in manifest file to be all lower case. Instead of renaming the existing package directory, we can change the title and/or the description?

Clarification: 

The package name in the integrations repository will be tomcat for the older one and apache_tomcat for the newer one.
The title (visible to the customer) of the packages will change: The older one will be "Apache Netwitness Logs" and the newer one will be "Apache Tomcat".

**Comment by lalit-satapathy** [comment]
- Please link the deprecation [PR](https://github.com/elastic/integrations/pull/6091) in the meta description.
- Question: I see the documents are [separate](https://github.com/elastic/integrations/blob/bde101498bcf6ee0244b862db5d363e9bd4ee6be/packages/apache_tomcat/docs/README.md) for each PR. Are the documentation changes of the PRs to be merged and all merge conflicts to be resolved during that process?
- Is this [request](https://github.com/elastic/integrations/pull/6003) data stream PR ready to be [merged](https://github.com/elastic/integrations/pull/6003#issuecomment-1529614337), since it is not reviewed internally once?

**Comment by ishleenk17** [comment]
@niraj-elastic : I assume that there are no histogram values in either of the metrics datastream since we are using Prometheus input?

**Comment by niraj-elastic** [comment]
> * Please link the deprecation [PR](https://github.com/elastic/integrations/pull/6091) in the meta description.
> * Question: I see the documents are [separate](https://github.com/elastic/integrations/blob/bde101498bcf6ee0244b862db5d363e9bd4ee6be/packages/apache_tomcat/docs/README.md) for each PR. Are the documentation changes of the PRs to be merged and all merge conflicts to be resolved during that process?
> * Is this [request](https://github.com/elastic/integrations/pull/6003) data stream PR ready to be [merged](https://github.com/elastic/integrations/pull/6003#issuecomment-1529614337), since it is not reviewed internally once?

- Sure, updated the meta with the link of package deprecation PR.
- Yes, once the PR is merged we will resolve the merge conflicts for the next PR.
- Internally Harnish is reviewing the PRs and I see he has just approved the PR.

**Comment by niraj-elastic** [comment]
> @niraj-elastic : I assume that there are no histogram values in either of the metrics datastream since we are using Prometheus input?

Yes, there are no histogram values

**Comment by niraj-elastic** [comment]
While developing the integration we we found that in Catalina and Localhost logs timezone offset is not coming, hence the timezone is getting considered UTC by default by [date processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-processor.html#:~:text=no-,UTC,-The%20timezone%20to). If the event is getting generated in a different timezone then the timestamp needs to get calculated accordingly otherwise by default it will consider as UTC and the timestamp will not be calculated properly. Hence we have introduced a new configuration parameter called `Timezone Offset` in the configuration section from where the user will be able to provide the timezone in which the events are generated so based on that timestamp calculation will be done in pipeline accordingly and events will be displayed with a correct timestamp.

**Comment by rameshelastic** [comment]
The following will be covered as part of Phase 2.

Thread Pool Metrics
Memory Metrics
Connection Pool Metrics
Session Metrics

**Comment by lalit-satapathy** [comment]
@ishleenk17, @milan-elastic,

Anything pending on apache tomcat, since it is [made GA now](https://github.com/elastic/integrations/pull/8385).

**Comment by milan-elastic** [comment]
> @ishleenk17, @milan-elastic,
> 
> Anything pending on apache tomcat, since it is [made GA now](https://github.com/elastic/integrations/pull/8385).

Yes, Apache tomcat is GA. hence closing this issue!
