### ISSUE TITLE
MySQL TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#5277]
## Test Environment Setup
- [x] Creation of MySQL setup for testing / Data preparation for testing.
- [x] Creation of Galera Cluster for Galera Status

## Datastream : Performance 
  - [ ] Add dimension fields 

  - [x] Adding metric_type mapping  
    - https://github.com/elastic/integrations/pull/5378
#### Verification and validation
  - [ ] Verify if field mapping is correct in the data stream template.
  - [ ] Verification of data in visualisation after enabling TSDB flag in kibana
  - [ ] Verification of the count of documents (before & after TSDB enablement) in Discover Interface

## Datastream : Status
  - [x] Add dimension fields  
    - https://github.com/elastic/integrations/pull/5337
  - [x] Adding metric_type mapping 
     - https://github.com/elastic/integrations/pull/5387
#### Verification and validation
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana.  [Details](https://github.com/elastic/integrations/issues/5277#issuecomment-1446171259)
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface

## Datastream : Galera Status
  - [x] Add dimension fields  
    - https://github.com/elastic/integrations/pull/5337
  - [x] Adding metric_type mapping 
    - https://github.com/elastic/integrations/pull/5407
#### Verification and validation
  - [x] Verify if field mapping is correct in the data stream template.
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana. [Details](https://github.com/elastic/integrations/issues/5277#issuecomment-1446171259)
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface

## Issues
  - https://github.com/elastic/elasticsearch/issues/94113
## Backlog Items
   Links to  backlog issues that could not be addressed in this TSDB enablement activity
  - https://github.com/elastic/integrations/issues/5385

**Comment by agithomas** [comment]
Verified the Dashboard Rendering

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/101976829/221553248-0bccaf59-155d-48d3-9284-b65a0ad696ff.png">

**Comment by lalit-satapathy** [comment]
Currently blocked on: https://github.com/elastic/elasticsearch/issues/94113.

**Comment by agithomas** [comment]
MySQL Performance Field mapping details added below after using 8.8 and having flattened issue

```json
"mysql": {
        "properties": {
          "performance": {
            "properties": {
              "events_statements": {
                "properties": {
                  "avg": {
                    "properties": {
                      "timer": {
                        "properties": {
                          "wait": {
                            "type": "long",
                            "time_series_metric": "gauge"
                          }
                        }
                      }
                    }
                  },
                  "count": {
                    "properties": {
                      "star": {
                        "type": "long",
                        "time_series_metric": "gauge"
                      }
                    }
                  },
                  "digest": {
                    "type": "flattened"
                  },
                  "last": {
                    "properties": {
                      "seen": {
                        "type": "date"
                      }
                    }
                  },
                  "max": {
                    "properties": {
                      "timer": {
                        "properties": {
                          "wait": {
                            "type": "long",
                            "time_series_metric": "gauge"
                          }
                        }
                      }
                    }
                  },
                  "quantile": {
                    "properties": {
                      "95": {
                        "type": "long",
                        "time_series_metric": "gauge"
                      }
                    }
                  },
                  "query_id": {
                    "type": "keyword",
                    "time_series_dimension": true
                  }
                }
              },
              "table_io_waits": {
                "properties": {
                  "count": {
                    "properties": {
                      "fetch": {
                        "type": "long",
                        "time_series_metric": "gauge"
                      }
                    }
                  },
                  "index": {
                    "properties": {
                      "name": {
                        "type": "keyword",
                        "ignore_above": 1024
                      }
                    }
                  },
                  "object": {
                    "properties": {
                      "name": {
                        "type": "keyword",
                        "time_series_dimension": true
                      },
                      "schema": {
                        "type": "keyword",
                        "time_series_dimension": true
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "service": {
        "properties": {
          "address": {
            "type": "keyword",
            "time_series_dimension": true
          },
          "type": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      }
```

**Comment by agithomas** [comment]
PR review is currently blocked on - if it is Ok to keep 8.8.0 as the min dependency.

**Comment by lalit-satapathy** [comment]
@agithomas, Can we update the issue with plan for MySQL?

**Comment by agithomas** [comment]
> @agithomas, Can we update the issue with plan for MySQL?

The MySQL pipeline is presently [broken](https://github.com/elastic/integrations/pull/6531) .
Once the issue is resolved, TSDB changes can be merged.

**Comment by agithomas** [comment]
![image](https://github.com/elastic/integrations/assets/101976829/a79a3d16-c27e-4ce2-89e7-d1a00f2385f8)

**Comment by agithomas** [comment]
![image](https://github.com/elastic/integrations/assets/101976829/c7c30006-9cf8-4279-b992-f639f63d90e9)

**Comment by agithomas** [comment]
![image](https://github.com/elastic/integrations/assets/101976829/1d2b61e5-ee8e-4f1a-80dd-c6c62e795954)
