### ISSUE TITLE
[Meta Issue] Integrations Test Environment

### ISSUE THREAD

**Issue by ishleenk17** [elastic/integrations#5340]
The service integration team currently supports a wide number of integrations across platforms and standalone/cloud deployments. There is a time lapse when an integration goes GA and an issue gets reported from customers. The challenge is to quickly bring-up a specific service to test the corresponding integration and replicate the user issue when necessary. 

Some of the challenges have been discussed in this [document](https://docs.google.com/document/d/120BcF8pGFh62BhkODn6rUOCSeNeED9wIpAEFu3SHxj0/edit#). 

- [ ] https://github.com/elastic/integrations/issues/5338
    - [x] https://github.com/elastic/integrations/issues/5488
    - [x] https://github.com/elastic/integrations/issues/5489
    - [x] https://github.com/elastic/integrations/issues/5490
- [x] https://github.com/elastic/integrations/issues/5339
    - [x] Run an existing integration on elastic cloud with the default deployment: [Details](https://github.com/elastic/integrations/issues/5339#issuecomment-1446060007)
    - [x] Setup the observability cluster using oblt-cli with a customized deployment
    - [x] Test out local changes for integrations on elastic Cloud
