### ISSUE TITLE
[Meta] Kubernetes package/integration

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#601]
This is a meta issue to keep track of the open issues we have regarding the Kubernetes package/integration.

## Open issues

- [x] Deployment strategy for Standalone and Managed version of Agent: https://github.com/elastic/beats/issues/23613
- [x] Refactor kubernetes metricsets to use single calls per endpoint to improve performance. For instance, `state_*` metricsets fetch the same amount of data to only store some of them according the target k8s object. This can be improved if metricsets can share the input. Some goes for `pod`, `node`, `volume`,  `container` and `system` metricsets that get the same input from Kubelet's api -> https://github.com/elastic/beats/issues/24869
- [x] We want the Kubernetes integration to look like AWS, with one package shipping multiple integrations: kubelet, kube_state, etc.. Outcome from https://github.com/elastic/integrations/issues/526 should be able to apply to kubernetes integration as well -> https://github.com/elastic/beats/issues/24870
- [x] Integration tests: https://github.com/elastic/integrations/issues/822
- [x] ECS (https://github.com/elastic/integrations/issues/442, https://github.com/elastic/beats/issues/23585)

**Comment by ChrsMark** [comment]
@masci feel free to comment/edit/add on the description

**Comment by andresrc** [comment]
Thanks @ChrsMark !!

**Comment by ruflin** [comment]
@ChrsMark If my understanding is correct, point 1,3,4 are a requirement, 2 is an improvement.

**Comment by ChrsMark** [comment]
> @ChrsMark If my understanding is correct, point 1,3,4 are a requirement, 2 is an improvement.

@ruflin that's correct
