### ISSUE TITLE
[Meta] Integrations Beta to GA

### ISSUE THREAD

**Issue by rameshelastic** [elastic/integrations#6014]
This is a meta issue to track progress of moving packages from Beta to GA. 

```[tasklist]
### Phase 1
- [ ] https://github.com/elastic/integrations/issues/6049
- [ ] https://github.com/elastic/integrations/issues/6050
- [ ] https://github.com/elastic/integrations/issues/6056
- [ ] https://github.com/elastic/integrations/issues/6052
- [ ] https://github.com/elastic/integrations/issues/6054
- [ ] https://github.com/elastic/integrations/issues/6055
```

```[tasklist]
### Phase 2
- [ ] https://github.com/elastic/integrations/issues/7253
- [ ] https://github.com/elastic/integrations/issues/7441
- [ ] https://github.com/elastic/integrations/issues/7243
- [ ] https://github.com/elastic/integrations/issues/7239
- [ ] https://github.com/elastic/integrations/issues/7211
- [ ] https://github.com/elastic/integrations/issues/7281
- [ ] https://github.com/elastic/integrations/issues/7363
- [ ] https://github.com/elastic/integrations/issues/7289
- [ ] https://github.com/elastic/integrations/issues/7406
- [ ] https://github.com/elastic/integrations/issues/7412
```
```[tasklist]
### Phase 3
-  [ ] https://github.com/elastic/integrations/issues/6048
- [ ] https://github.com/elastic/obs-infraobs-team/issues/1104
- [ ] https://github.com/elastic/integrations/issues/8441
```

#### Yet to be picked up.

Salesforce - There are multiple client issues that are opened so it is not picked up yet

**Comment by ishleenk17** [comment]
There is a difference in packages being in Technical preview and Beta as per Semantic Versioning. 
We should just have that in mind as well before taking it to GA.

**Comment by lalit-satapathy** [comment]
@muthu-mps, Can we summarise the meta with key findings of the migration?

**Comment by muthu-mps** [comment]
### Key Findings

### ActiveMQ

ActiveMQ comes with two flavours, `Classic and Artemis.` We have an enhancement request to collect Artemis metrics. The current integration supports classic version. We need to evaluate and make a call on whether we can make the ActiveMQ GA without having Artemis implementation. Initiated discussions in the ActiveMQ issue.

https://github.com/elastic/enhancements/issues/11568

- [ ]  Are we considering Artemis for making ActiveMQ GA ? YES / NO


### Couchbase

The sync-gateway host configuration is mandatory. This config should be optional as the metrics collection for sync-gateway can be enabled or disabled. When disabling the metrics collection the user should not be forced to provide the host configuration. Created an issue to make the configuration optional.

- [ ] https://github.com/elastic/integrations/issues/6248

### IBMMQ

  - #### what is missing ?
     Currently we are collecting `queue manager` metrics. Here we are not collecting the queue and channel metrics. There may be multiple queue in a queue manager. There should be a way to segregate metrics based on queue and channel.
  
  - #### Nice to Have:
    Add Queues, Topics and Channel metrics to the integrations.
    Queue usage and messages processed in a queue are more valuable metrics.
    Queue depth metrics. This helps deciding on adding more messages to a queue.

    - [ ]  Can we consider the additional metrics to be collected before making the integration GA ? YES / NO

  - #### Enhancement Request on new way of collecting the metrics other than using prometheus 
    https://github.com/elastic/enhancements/issues/18669

    - [ ]  Using Go client for collecting metrics YES / NO ?


### MicrosoftSQLServer Performance & Transaction Log Datastream

The connection string with backslash is pre-encoded and provided as an input. This workaround is provided for the domain users to connect without issues. The idea here is to encode the the domain user names internally without asking customer to enter the encoded string as an input.

### NagiosXI

### Oracle Weblogic

### MemCached

**Comment by rameshelastic** [comment]
Added Phase 2 as part of planning for next sprint. 

cc: @milan-elastic

**Comment by lalit-satapathy** [comment]
@milan-elastic, @muthu-mps, 

Do we have any packages pending GA on this list above?

**Comment by milan-elastic** [comment]
@lalit-satapathy From above list Salesforce is yet to GA as we are working on revamping it, apart from that ActiveMQ is not GA. @muthu-mps can share more details on ActiveMQ

**Comment by muthu-mps** [comment]
The phase 3 migrations competed.
