### ISSUE TITLE
[Meta][TSDB] Modify the dimension field mapping to support public cloud deployment

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#6031]
Make the following changes to the integration packages which are already TSDB enabled.

- Add `cloud.region`, `cloud.availability_zone` as the dimension field
- Modify `cloud.project.id` to `cloud.account.id` as dimension field.
- Remove the field mapping of `cloud.project.id` field
- Generate the README file after the change. 
- Update manifest.yml and changelog file to contain the change details

Below are the packages needing the change

- Oracle - https://github.com/elastic/integrations/pull/6032
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- InfluxDB - https://github.com/elastic/integrations/pull/6035
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- Ngnix - https://github.com/elastic/integrations/pull/6033
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- CockroachDB https://github.com/elastic/integrations/pull/6156
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- RabbitMQ https://github.com/elastic/integrations/pull/6155
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- MSSQL  https://github.com/elastic/integrations/pull/6143
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- Redis - https://github.com/elastic/integrations/pull/6037
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- Airflow https://github.com/elastic/integrations/pull/6157
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- CouchDB - https://github.com/elastic/integrations/pull/6039
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- Kafka - https://github.com/elastic/integrations/pull/6036
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- MySQL - https://github.com/elastic/integrations/pull/6040
  - [x] Verified the need of changing dimension limit and applied changes if necessary
- Postgresql - https://github.com/elastic/integrations/pull/6044
  - [x] Verified the need of changing dimension limit and applied changes if necessary

**Comment by agithomas** [comment]
The issue is related to https://github.com/elastic/integrations/issues/5233
