### ISSUE TITLE
Lens Migration Phase 2

### ISSUE THREAD

**Issue by rameshelastic** [elastic/integrations#6141]
The initiative to migrate visualizations from TSVB to Lens was launched in 8.8 release. The first phase of this migration focused on prioritizing critical service integrations. The list of integrations that were migrated during the initial phase is available [here](https://github.com/elastic/integrations/issues/5221).  

There is a list of phases for this lens migration work, it can be found from below tracker issue:

**Phases and issues tracker** https://github.com/elastic/integrations/issues/6489

Continuing with our efforts in the same direction, the goal of Lens Migration Phase 2 is to migrate key Cloud Integrations. This issue describes the tasks to be accomplished in this phase.

- [x] Identifying the [list of Integrations](https://github.com/elastic/integrations/issues/6194) with visualizations that need migration to Lens and Prioritising a sub-set of Integrations to be migrated in this phase.
- [x] Creating a Migrations Check List
- [x] Migrations Status

**Completed Integrations:**
- [x] AWS Usage Metrics https://github.com/elastic/integrations/issues/6205
- [x] AWS Cloudtrail https://github.com/elastic/integrations/issues/6206
- [x] AWS SNS https://github.com/elastic/integrations/pull/5642
- [x] AWS RDS https://github.com/elastic/integrations/pull/5640
- [x] AWS SQS https://github.com/elastic/integrations/pull/5644
- [x] AWS DynamoDB https://github.com/elastic/integrations/pull/5288
- [x] AWS Lambda https://github.com/elastic/integrations/pull/5455
- [x] Airflow https://github.com/elastic/integrations/issues/6197
- [x] AWS S3 Storage Lens https://github.com/elastic/integrations/issues/6204
- [x] AWS EC2 https://github.com/elastic/integrations/issues/6207
- [x] AWS ELB https://github.com/elastic/integrations/issues/6201
- [x] AWS Metrics https://github.com/elastic/integrations/issues/6222

The next phase shall focus on Azure and GCP Integrations.

**Comment by rameshelastic** [comment]
Created duplicate of[ issue](https://github.com/elastic/obs-infraobs-team/issues/1001)

**Comment by rajvi-elastic** [comment]
All the mentioned integrations are migrated to lens. Therefore closing this issue.
