### ISSUE TITLE
[AWS API Gateway] Metrics datastream

### ISSUE THREAD

**Issue by lucianpy** [elastic/integrations#6270]
## Summary

Collect metrics, analyze them and produce an integration for API Gateway metrics. Analyzing these metrics helps detect bottlenecks, optimize resources, and troubleshoot issues.

This integration will include all three supported API types: HTTP, REST, and WebSocket. 

## Tasks

- [x] Set up or use existing instances for the three API types to generate metrics
- [x] Initially inspect metrics for confirmation via [AWS CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html) or [AWS CLI](https://aws.amazon.com/cli/)
- [x] Fetch metrics via [metricbeat](https://www.elastic.co/beats/metricbeat) and save sample event
- [x] Create the integration in accordance to fetched data which includes fields, dimensions, sample event, icon etc.
- [x] Spin up the stack locally; Set up and verify the integration via Kibana
- [ ] Create documentation which includes summary, setup, requirements, fields and sample event

## Challenges

- AWS naming scheme can be confusing (ex: `4XXError` for REST vs `4xx` for HTTP). Both metrics exist and appear to serve the exact same purpose but it's easy to assume one is just a typo initially.
- Given that no metrics are currently being generated in the Elastic account for API Gateway, metricbeat might not fetch metrics consistently. This is because they miss the [time window](https://github.com/elastic/beats/blob/f65554fdfb439f71f7107524c4c050767f2e9bb7/x-pack/metricbeat/module/aws/utils.go#L32-L37) that the CloudWatch metricset uses.

## Docs

Metrics and dimensions documentation:
- [HTTP API](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html) 
- [REST API](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-metrics.html) 
- [WebSocket](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-logging.html)
