### ISSUE TITLE
[AWS] TSDB enablement - track all metrics data streams

### ISSUE THREAD

**Issue by constanca-m** [elastic/integrations#6293]
## Test Environment Setup

Elastic package should be running the stack.

1. Go to the AWS directory and run `elastic-package build`.
2. Run `elastic-package stack up -v -d --services package-registry` to update the integration.

## Datastreams

Add `agent.id` and check for `cloud.availability_zone` on migrated and merged TSDB data streams: https://github.com/elastic/integrations/pull/6421
- [x] Usage  
- [x] ELB
- [x] DynamoDB
- [x] EBS
- [x] ECS
- [x] Kinesis
- [x] Lambda
- [x] Natgateway
- [x] Redshift

Add metrics and dimensions:

- [x] API Gateway
  - [x] Dimensions: https://github.com/elastic/integrations/pull/6950
  - [x] Metric type: https://github.com/elastic/integrations/pull/6952

- [x] EMR: https://github.com/elastic/integrations/pull/6964

- [ ] Billing - **Important**: TSDB was disabled on this data stream, because of this issue https://github.com/elastic/integrations/issues/7345
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6311
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6319
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.

- [x] Cloudwatch metrics
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6827
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6999

- [x] DynamoDB: https://github.com/elastic/integrations/issues/6227

- [x] EBS: https://github.com/elastic/integrations/issues/6061

- [x] EC2: 
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/7487
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/7490

- [x] ECS: https://github.com/elastic/integrations/issues/5894

- [x] ELB: https://github.com/elastic/integrations/issues/6227

- [x] Firewall metrics
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6339
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6365
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.

- [x] Kinesis: https://github.com/elastic/integrations/issues/5864
   

- [x] Lambda: https://github.com/elastic/integrations/issues/5970

- [x] Natgateway: https://github.com/elastic/integrations/issues/6101

- [x] RDS: https://github.com/elastic/integrations/issues/6078

- [x] Redshift: https://github.com/elastic/integrations/issues/6082

- [x] S3 daily storage & S3 request:
  - [x] Dimensions: https://github.com/elastic/integrations/pull/6666
  - [x] Metrics: https://github.com/elastic/integrations/pull/6667

- [x] S3 storage lens
  - [x] Add dimension fields: #6583 
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface - documents every 24h, not easy to check
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: #6584
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.

- [x] SNS
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6311
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6319
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.

- [x] SQS
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6311
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6319
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.
    

- [x] Transitgateway
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6339
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6365
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.

- [x] Usage: https://github.com/elastic/integrations/issues/6227

- [x] VPN
  - [x] Add dimension fields: https://github.com/elastic/integrations/pull/6339
    - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
    - [x] Verify if field mapping is correct in the data stream template.
  - [x] Adding metric_type mapping: https://github.com/elastic/integrations/pull/6365
    - [x] Verification of data in visualisation after enabling TSDB flag in kibana
    - [x] Verify if field mapping is correct in the data stream template.

## Testing

For every data stream:
- The number of documents is the same before and after enabling TSDB
- The dashboards works before TSDB is enabled
- The dashboard works after TSDB is disabled

Tested:
  - [x] API Gateway
  - [x] Billing
     - [x] Fix dimensions since documents are being overwritten: https://github.com/elastic/integrations/pull/6749
  - [x] Cloudwatch
  - [x] DynamoDB
  - [x] EBS
  - [ ] EC2
  - [x] ECS
  - [x] ELB
  - [x] EMR
  - [x] Firewall
  - [x] Kinesis
  - [x] Lambda
  - [x] Nat Gateway
  - [x] RDS
  - [x] Redshift
  - [x] S3 daily storage
  - [x] S3 request
      - [ ] issue: https://github.com/elastic/integrations/issues/6783 - not a blocker for TSDB
  - [x] S3 storage lens
  - [x] SNS
  - [x] SQS
  - [x] Transit Gateway
  - [x] Usage:
    - [ ] Issue: https://github.com/elastic/integrations/issues/6783 - not considered a blocker for TSDB enablement.
  - [x] VPN

## Enable TSDB by default

1. Billing, DynamoDB, EBS, ECS, ELB, Firewall, Kinesis, Lambda, NAT gateway, RDS, Redshift, S3 Storage Lens, SNS, SQS Transit Gateway, VPN: https://github.com/elastic/integrations/pull/6782
2. Usage: https://github.com/elastic/integrations/pull/6886
3. API Gateway and EMR: https://github.com/elastic/integrations/pull/6969
4. Enable in Cloudwatch: https://github.com/elastic/integrations/pull/7262
5. Enable in EC2 metrics data stream: https://github.com/elastic/integrations/pull/7497
