### ISSUE TITLE
Migrate Threat Intel package

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#650]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### Migration Checklist

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Generated output for at least 1 log file exists
- [ ] Documentation explains how to configure monitoring target to work with the integration
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:
- [ ] Screenshot of the "Add Integration" page on Fleet added to PR

### Dashboards

- [ ] Dashboards exists
- [ ] Screenshots added to manifest
- [ ] Data stream filters added to visualizations

### Data Streams
- misp
  - [ ] Convert edge processing to Ingest Node
  - [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
  - Inputs
    - httpjson
      - [ ] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) added

    - log
      - [ ] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) added

**Comment by andrewkroh** [comment]
I changed this from MISP to "Threat Intel" to reflect that we will wait for the new threat intel module to be done and migrate that over rather than bringing over the older `misp` module. The new module includes a `misp` source.

**Comment by rylnd** [comment]
Related issue: https://github.com/elastic/security-team/issues/1613. If we could ensure that these new packages conform to a more specific index pattern than `logs-*`, that would be incredibly helpful for future performance.
