### ISSUE TITLE
[Epic] Tagging Community/Partner Integrations

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#6569]
### Intro
Elastic currently supports 300+ integrations via Elastic Agent, to ingest data from common data sources across security and observability use cases. All integrations are treated equally from a support standpoint regardless of where the integration came from. We have three main sources of integrations: 

- Elastic integration teams (including contractors) 
- Vendors who build integrations for their products under our partnership program 
- Community users who develop and contribute integrations 

While we really appreciate and value community contributions, we are limited in our ability to test these integrations as we typically don't have access to the data source and don't have a technology partnerships in place with the vendor. Similarly, for vendor/partner developed integrations, while we review the PR, we didn't build the integration and can't guarantee the same quality as Elastic developed integrations. 

### Proposal
In order to set expectations with users on the quality and support they can expect from an integration, we should highlight the source of the integration within integration documentation and on the integrations UI. We will continue to provide best effort support and don't want situations where users adopt community developed integrations that are completely unsupported. However, expectations should be set that Elastic has not developed these integrations, does not have access to the data source and to expect possible parsing/mapping/performance issues. 

We need to finalise wording and ensure we set user expectations correctly, but something similar to[ Hashicorp's community supported wording](https://developer.hashicorp.com/vault/docs/configuration/storage/s3) is what we're aiming for:

`**Community Supported** – the S3 storage backend is supported by the community. While it has undergone review by HashiCorp employees, they may not be as knowledgeable about the technology. If you encounter problems with them, you may be referred to the original author.`

### To Consider

- All integrations, regardless of the source, reside in the elastic/integrations repo. Should we consider moving community and/or technology partner integrations to a separate repo? How would Elastic Package Registry handle this?
- Beyond a section within the documentation, could we add attributes to the packages and make those attributes visible in Fleet. e.g. Developed by
- Within Fleet could we add a filter based on integration source? e.g. Elastic, Vendor, Partner (unsure on the value of this, but worth considering at least). 

### Tasks

- [x] Add new field to package-spec to indicate owner/developer type
https://github.com/elastic/package-spec/pull/568
https://github.com/elastic/package-spec/pull/604
- [x] Update SEI packages to use new field
https://github.com/elastic/integrations/pull/7810
https://github.com/elastic/integrations/pull/8035
- [x] Document new field
https://github.com/elastic/kibana/issues/167981
https://github.com/elastic/integration-docs/issues/255

**Comment by jamiehynds** [comment]
@jsoriano - FYI as this will likely require changes on the elastic-package side. @andrewkroh has some thoughts. 

@SubhrataK I'm hoping we could extend this across all integrations across security and observability. Would be great to get your input.

**Comment by jsoriano** [comment]
> * All integrations, regardless of the source, reside in the elastic/integrations repo. Should we consider moving community and/or technology partner integrations to a separate repo? How would Elastic Package Registry handle this?

Not all integrations reside on the integrations repo, there are some integrations like APM or endpoint that reside on other repositories.

Package publication in the package registry works by [triggering a job in internal-ci](https://internal-ci.elastic.co/job/package_storage/job/publishing-job/job/main/). This job could be triggered from any CI pipeline that supports triggering Jenkins jobs. With this approach we could only support jobs owned by Elastic, as some credentials are required to trigger jobs in internal-ci.

With this approach we could allow contributors to open PRs to the current integrations repository, or we could have another repository with community contributors. In both cases the repository would need to be owned by Elastic so it has access to internal-ci, and we should approve the merges that would trigger package publication.

Something else to take into account is that all packages published now are signed with Elastic keys. This is the main reason to use internal-ci for publication now.

A more advanced approach would imply to implement a new public API to publish packages, that would replace the job in internal-ci. This would allow external contributors to directly publish their own packages, signed with their own keys.

If we start publishing packages from different sources it will be also interesting to add build information in the packages to know where the source comes from https://github.com/elastic/package-spec/issues/446.

> FYI as this will likely require changes on the elastic-package side.

In principle no changes would be required on elastic-package as it doesn't publish packages. Unless we decide to implement the public API and give support to it in elastic-package.

> Beyond a section within the documentation, could we add attributes to the packages and make those attributes visible in Fleet. e.g. Developed by

We currently have the `owner` section in the manifest. It currently supports github teams, what might be enough. Elastic packages would be owned by elastic teams, while community/partner packages wouldn't be.

> Within Fleet could we add a filter based on integration source? e.g. Elastic, Vendor, Partner (unsure on the value of this, but worth considering at least).

Yes, I think we could work on the UI for this. We could maybe add a badge to differentiate Elastic from Community contributions. cc @juliaElastic

**Comment by ebeahan** [comment]
As a first step, could we implement some sort of tagging in package-spec? Tagging integrations as community would set expectations about testing and supportability and include the `community supported` expectations in the integration's docs.

> Yes, I think we could work on the UI for this. We could maybe add a badge to differentiate Elastic from Community contributions. cc @juliaElastic

Same tagging could visually differentiate in the UI.

**Comment by SubhrataK** [comment]
We are working on a similar project under Observability. Please refer [Integrations Ecosystem](https://elasticco.atlassian.net/browse/OB-270).

Key points that I would like to highlight, which are being discussed as part of this project are:

1. We will not own and support integrations that are contributed by the community/partner. This shall be made explicit to the community/partner while signing the legal agreement. And to our customers through documentation and also through tags or description in the integrations catalog UI.
2. We should have a tag to identify and filter the community/partner developed integrations in the catalog for the users to filter.

CC: @lalit-satapathy and @rameshelastic

**Comment by taylor-swanson** [comment]
Hi all, here are my current thoughts/ideas/comments:

Regarding the separate community repo:

- Discussions on this are out of scope for this particular issue, but I'll give my thoughts anyway. In general, I'm for this idea. It separates community integrations entirely from offical Elastic ones, which helps keep the noise down in the main integrations repo.

With that said, I'm in favor of having an explicit flag for the type of owner for the package. I quickly drafted a new field in the package spec for this: 

```yaml
owner:
  type: object
  additionalProperties: false
  properties:
    type:
      description: Describes who owns the package and the level of support that is provided.
      type: string
      enum:
        - "elastic"
        - "partner"
        - "community"
    github:
      ...
```

(If anyone has better suggestions for naming or the description, I'm open to ideas)

This would be a required field moving forward. 

Alternatively, as @jsoriano mentioned, we could derive this "owner type" from the github owner field already present:

- Begins with `elastic/`: Elastic-owned integration
- Anything else: Community-owned integration

That leaves partner integrations. We could dedicate a group within `elastic/` for partner integrations (`elastic/partner-integrations`). When matched against that group, then it becomes a Partner-owned integration. However, That contradicts this statement:

> We will not own and support integrations that are contributed by the community/partner

A partner may develop an integration entirely separate from us, so using an Elastic-owned github group probably won't not work here. If we did want to call out partner integrations differently than community integrations, we would have to come up with a method to do that.

As far as the Kibana UI work is concerned, I'll have to defer to someone who understands this better. To me, having a dedicated field that can be filtered on seems more reliable than trying to derive the owner type from the github owner. I could be wrong, though.

One other issue I thought of with this approach is keeping the logic in sync between different systems which need to know the owner type. For example, docs generation will need to know the owner type in order to inject a statement about the support level of the package. Likewise, the Kibana UI will need to know the owner type in order to filter packages. These mechanisms exist in entirely different repos across different teams. I'm sure there are other places, too, and I have concerns about keeping the logic in sync, especially if there are a lot of edge cases that come up with partners vs community packages.

**Comment by jamiehynds** [comment]
@jsoriano would you mind reviewing Taylor's write up above and let us know your thoughts? As we ramp up on community and partner developed integrations, we're aiming to get this capability done for 8.10. Thanks!

**Comment by jsoriano** [comment]
Hey, sorry for the late reply.

I am fine with the `owner.type` field as a temporary solution as part of the "poor man's marketplace". It will work while we (as Elastic) review all packages that are published, and we remember to check this field. There are some things to define as what to assume by default when the field is not set. I don't think we cannot enforce this field as required because that would be a breaking change, and wouldn't work for packages already published. We can discuss about these details in the PR.

In the long run this should probably be part of the publishing pipeline. Ideally we would have a public API to publish packages, and the authentication used there would help us to distinguish the type of owner. We could also use the signing keys. We are currently the publishers of all packages, and all packages are signed with our keys, in the future external users could use their own keys.

A middle ground here that we could implement sooner, based on the owner handle, would be to have a list of partners somewhere, then `elastic/*` owners would indicate an Elastic integration, owners in the list of partners would indicate partners integrations, and the rest would be community.

ccing @mrodm in case you have other ideas or preferences.

**Comment by taylor-swanson** [comment]
Status update 2023-10-03:

- The `owner.type` field has been added as a required field to package-spec in the top-level `manifest.yml` file in a package
- All SEI packages have been updated to include an owner type
- Packages from other teams are being updated to include owner type as they move to package-spec `3.0.0`

Next steps:
- Expose the owner type field in the package details in the Kibana Fleet UI (similar to how other fields, such as subscription level and license are presented)
-  Determine if we need dedicated documentation or knowledge base article on owner types (describes support levels, expectations of developer support, etc)
- Add filters to Kibana Fleet UI to filter on owner type (future work, likely not under this issue)

**Comment by nimarezainia** [comment]
@kpollich @juliaElastic please see @taylor-swanson comment [here](https://github.com/elastic/integrations/issues/6569#issuecomment-1745094220).

**Comment by kpollich** [comment]
> Expose the owner type field in the package details in the Kibana Fleet UI (similar to how other fields, such as subscription level and license are presented)

This should be relatively low effort. I created https://github.com/elastic/kibana/issues/167981 to track this. 

> Add filters to Kibana Fleet UI to filter on owner type (future work, likely not under this issue)

This will probably be more involved, and we may want this filtering to be done at the API level in EPR. Agree on punting this to a follow-up where we can define the behavior better.

**Comment by kpollich** [comment]
> Do you recommend we host this within our integration docs, and we can link to those from the Fleet UI?

This seems like a good idea to me. That way if we ever add new owner types we can update the docs and we won't have churn to update a modal in Kibana. I'll add a note to that issue above saying we should link to a docs page once one exists.

**Comment by taylor-swanson** [comment]
@jamiehynds, with @kpollich (and team) working on implementing changes in the Kibana UI, I think the last remaining work would be to update our documentation.

I could see us making a change to `elastic-package` to generate a callout/section in the readme to note who developed the package and expected support levels. In order to do that, though, I would need some verbiage around each of the support levels. Would we want legal or perhaps the docs team to write something up? Would that be something you could track down?

I think once it's in the README, that information will be propagated throughout the ecosystem (i.e. it should show up on docs.elastic.co, the fleet integration page in Kibana, etc).

**Comment by taylor-swanson** [comment]
@kpollich, I think for https://github.com/elastic/kibana/issues/167981, the intent was to display it as data point on the right hand side along with other package info. While I still think this is a good idea, I think having a block in the main text of the package description would also be very import to have. I was thinking something on the lines of what is displayed for pre-release packages. I'll let UX decide how it wants decorate the block depending on the package owner/support level type. I originally thought this was rendered in the README markdown somehow, but I was wrong. We'll have to something similar to [docs.elastic.co/integrations](https://docs.elastic.co/integrations/airflow), as well.

![Screen Shot 2023-10-26 at 8 43 35 AM](https://github.com/elastic/integrations/assets/90622908/b6cb392b-d44a-4ee4-80c9-1ec2a5dda782)

I pointed to the pre-release tag, but I'm not as concerned about that. Again, I'll defer to UX if they have preferences either way. Mainly, we want a clear and upfront description of who developed this package and to set expectations of support levels.

**Comment by jamiehynds** [comment]
I'd worry about overloading the integration description with various labels, banners, etc. I'd be inclined to include it as a data point under the Details section. We'll also need to link to a page within our docs (or in-product) to explain what each 'Developed By' category means. I'm working on the wording of those descriptions. 

<img width="315" alt="Screenshot 2023-10-26 at 14 56 33" src="https://github.com/elastic/integrations/assets/62879768/86e0a4be-5926-4984-86de-90dd216fcc06">

We may need to put some thought into integrations developed by partners. Do we just say `Developed By: Partner` or include the partner/vendor name, and support contact details (which requires additional fields).

**Comment by taylor-swanson** [comment]
To be clear, here is what I was thinking about the banner (this would be for the docs site, but would apply to the Kibana UI as well):

**Disclaimer: Wording is NOT final.**

![Screen Shot 2023-10-26 at 9 04 43 AM](https://github.com/elastic/integrations/assets/90622908/fb8c2092-322c-4a14-b082-0bd919d9b191)

My concern with the sidebar is it will be overlooked/missed by users, but I can agree that overloading the description with too many labels, banners, etc can quickly become a problem.

**Comment by taylor-swanson** [comment]
> We may need to put some thought into integrations developed by partners. Do we just say Developed By: Partner or include the partner/vendor name, and support contact details (which requires additional fields).

Good point. As far as what's in the manifest, the only information we'd have access to currently is `owner.github`, which in most cases points back to SEI. I'd imagine we'd have to add a separate name field under `owner`.

**Comment by taylor-swanson** [comment]
Status update: The Kibana task has been completed and will be in 8.12. The remaining work is being tracked by the Docs team (see issue linked in the description).

**Comment by ebeahan** [comment]
EPR added support for `owner.type` in `v1.23.0`, and this version is deployed on EPR prod:

```
$ curl -sL https://epr.elastic.co/
{
  "service.name": "package-registry",
  "service.version": "1.23.0"
}
```

But the `owner.type` property is still not appearing for packages:

```
$ curl -sL https://epr.elastic.co/package/1password/1.26.0/ | jq '.owner'
{
  "github": "elastic/security-external-integrations"
}
```

Investigation still ongoing into why EPR isn't providing `owner.typer`.

Kibana handles the missing value gracefully in `8.12` and the `Developed By` field doesn't appear in if EPR doesn't provider `owner.type`. Once the value is supplied by EPR, `Developed By` should begin appearing with no other changes.

**Comment by 111andre111** [comment]
Just a coincidental question on that. Once it would appear in Kibana, would it be shown as well in docs.elastic.co?
https://github.com/elastic/integrations/issues/6569#issuecomment-1781175502

**Comment by taylor-swanson** [comment]
@111andre111, the docs team is looking into that now, but as of writing, I don't believe they have added anything in yet that displays this information. Discussions on how the information should be displayed and the resulting work is tracked here: elastic/integration-docs#255

**Comment by alaudazzi** [comment]
@taylor-swanson @111andre111 @jamiehynds @SubhrataK 
FYI the Obs doc team is taking this a priority for January. We will be creating a dedicated page with the [level of support](https://docs.google.com/document/d/1vUwBtHzLdhPsgahqOGR60OCGHgx9bbbrc17yP9XxcYM/edit) and reference it from the integration pages. 
Relates to https://github.com/elastic/integration-docs/issues/255

**Comment by taylor-swanson** [comment]
Thank you for the update, @alaudazzi! This is great news.

**Comment by ebeahan** [comment]
https://github.com/elastic/package-registry/issues/1126 is now resolved.

Examples of the different owner type values as displayed in EPM:

<img width="326" alt="Screenshot 2023-12-14 at 8 33 41 AM" src="https://github.com/elastic/integrations/assets/7226265/77634998-6ce9-48a6-ac22-37730a704d9d">

<img width="305" alt="Screenshot 2023-12-14 at 8 33 52 AM" src="https://github.com/elastic/integrations/assets/7226265/53c25b89-0856-4e84-9916-5c6f067dc9ff">

<img width="298" alt="Screenshot 2023-12-14 at 8 34 03 AM" src="https://github.com/elastic/integrations/assets/7226265/c76c389c-89ed-42fb-9e69-615ff47df622">

**Comment by taylor-swanson** [comment]
The owner type/support levels are now being presented on docs.elastic.co (see https://github.com/elastic/integration-docs/issues/255#issuecomment-1895744461), which wraps up the remaining work for this epic.
