### ISSUE TITLE
Serverless - Migrate integration dashboards to Lens

### ISSUE THREAD

**Issue by narph** [elastic/integrations#6787]
Below is the list of all remaining security integrations that require the migration of vis to lens (number of visualizations on the right for each integrations):

- [x] pfsense	18 https://github.com/elastic/integrations/pull/6859
- [x] ti_rapid7_threat_command	14 #6885
- [x] 1password	12 #6819
- [x] suricata	12 https://github.com/elastic/integrations/pull/6839
- [x] panw	11 https://github.com/elastic/integrations/pull/6876
- [x] auditd_manager	10 #6884
- [x] iptables	9 #6813
- [x] cisco_secure_email_gateway	8 #6812
- [x] github	8 #6883
- [x] cisco_asa	7 #6797
- [x] zeek	7 #6888
- [x] system_audit	6 https://github.com/elastic/integrations/pull/6894
- [x] m365_defender	5 https://github.com/elastic/integrations/pull/6898
- [x] microsoft_defender_endpoint	5 #6900
- [x] osquery	5 https://github.com/elastic/integrations/pull/6826
- [x] osquery_manager	5 https://github.com/elastic/integrations/pull/6836
- [x] santa	5 https://github.com/elastic/integrations/pull/6910
- [x] auditd	4 https://github.com/elastic/integrations/pull/6912
- [x] cisco_ise	4 #6799
- [x] infoblox_nios	4 #6901
- [x] o365	4 #6902
- [x] okta	4 #6903
- [x] qnap_nas	4 #6904
- [x] auth0	3 #6905
- [x] tenable_io	3 #6906
- [x] cisco_duo	2 #6815
- [x] google_workspace	2 https://github.com/elastic/integrations/pull/6914
- [x] microsoft_exchange_online_message_trace	2 https://github.com/elastic/integrations/pull/6931
- [x] sentinel_one	2 https://github.com/elastic/integrations/pull/6932
- [x] cyberarkpas	1 #6924
- [x] darktrace	1 #6924
- [x] infoblox_bloxone_ddi	1 #6924
- [x] jamf_compliance_reporter	1 #6924
- [x] ti_abusech	1 #6924
- [x] ti_cybersixgill	1 #6924
- [x] zscaler_zpa	1 #6924
