### ISSUE TITLE
[Meta] Lens migration phase 3

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#6907]
The initiative to migrate visualizations from TSVB to Lens was launched in the 8.8 release. This migration's first and second phases focused on prioritizing critical service integrations. The list of phases can be find from below tracker issue:

**Phases and issues tracker https://github.com/elastic/integrations/issues/6489** 

Continuing with our efforts in the same direction, the goal of Lens Migration Phase 3 is to migrate key Cloud Integrations. This issue describes the tasks to be accomplished in this phase.

- [x] Identifying the [list of Integrations](https://github.com/elastic/integrations/issues/6194) with visualizations that need migration to Lens and Prioritising a sub-set of Integrations to be migrated in this phase.
- [x] Creating a Migrations Check List
- [x] Migrations Status

## **AWS Integrations:**

**Completed Integrations**
- [x] AWS fargate https://github.com/elastic/integrations/issues/6893
- [x] AWS Firewall https://github.com/elastic/integrations/issues/6908
- [x] AWS Redshift https://github.com/elastic/integrations/issues/6862
- [x] AWS S3 Server Access Log https://github.com/elastic/integrations/issues/6779
- [x] AWS Billing https://github.com/elastic/integrations/issues/6361
- [x] AWS VPC Flow https://github.com/elastic/integrations/issues/6452
- [x] AWS Security Hub https://github.com/elastic/integrations/issues/6863
 
## **Azure Integrations:**

**Completed Integrations**
- [x] Azure Application Insights https://github.com/elastic/integrations/issues/7231
- [x] Azure Active Directory https://github.com/elastic/integrations/issues/7230 
- [x] Azure Billing Metrics https://github.com/elastic/integrations/issues/7218
- [x] Azure Metrics
    - [x] Container Service https://github.com/elastic/integrations/issues/7436
    - [x] Storage Account https://github.com/elastic/integrations/issues/7434
    - [x] Virtual Machine https://github.com/elastic/integrations/issues/7433
    - [x] Virtual Machine Scaleset https://github.com/elastic/integrations/issues/7431
    - [x] Database account https://github.com/elastic/integrations/issues/7427

## **GCP Integrations:**
**Completed Integrations**
- [x] Load balancing https://github.com/elastic/integrations/issues/7256
- [x] Audit https://github.com/elastic/integrations/issues/7260
- [x] Firewall https://github.com/elastic/integrations/issues/7257
- [x] vpcflow https://github.com/elastic/integrations/issues/7258
- [x] Billing https://github.com/elastic/integrations/issues/7250

## Blocker issues

- Fields with flattened data type are not supported in visualization.
https://github.com/elastic/integrations/issues/7259
- ~Update fields in GCP Load balancing dashboards~
~https://github.com/elastic/integrations/issues/7242~
- ~Fix metrics field in Container instance~
~https://github.com/elastic/integrations/issues/7158~
- Update panel titles in Azure Metrics Dashboard
https://github.com/elastic/integrations/issues/7585
