### ISSUE TITLE
[Epic] Create a Workday user provider for the entity_analytics Filebeat input

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#7009]
### Story

As a user of the Security Solution I want to continuously sync user metadata from Workday into Elasticsearch. Data is produced in accordance to [RFC 2022-09-07-user-host-entity-ingestion](https://github.com/elastic/security-external-integrations/blob/078acbafbdec6668ef387244096d082a239ef38f/rfcs/2022/2022-09-07-user-host-entity-ingestion.md).

### Acceptance Criteria
- [] Collect user data from Workday via a new provider in the `entity_analytics` Filebeat input.
- [] Generate one document per user that includes group membership data
- [] Periodically get a list of users that were modified or deprovisioned and generate new documents
- [] Persist data to disk that allows the input to resume from previous state

### Test Criteria
- [ ] Verify users are synced.
- [ ] Verify documents contain group membership info.
- [ ] Update a user in Workday, verify the change is reflected in Elasticsearch as a new document.
- [ ] Delete a user in Workday, verify the change is reflected in Elasticsearch as a new document that indicates a deleted status
- [ ] Create a new user in Workday, verify the new user reflected in Elasticsearch
- [ ] Verify that the data stream contains a "full sync marker" document with `event.action: started` when a new sync starts.
- [ ] Verify that the data stream contains a "full sync marker" document with `event.action: completed` when a new sync completed.
- [] Documentation exists that explains how the input works (what APIs it utilizes, how it persists information, etc)
- [] Documentation exists that explains how to authenticate and authorize the input with least privileges.

### References

- [Workday 'Person' API endpoint](https://community.workday.com/sites/default/files/file-hosting/restapi/index.html#person/v3/countries)
- [User Entity Integrations RFC](https://github.com/elastic/security-external-integrations/blob/078acbafbdec6668ef387244096d082a239ef38f/rfcs/2022/2022-09-07-user-host-entity-ingestion.md)

### Related

- Parent: https://github.com/elastic/security-team/issues/4163#issuecomment-1165709940
- https://github.com/elastic/beats/pull/34305
