### ISSUE TITLE
[Meta][aws-s3] Add system tests for integrations that use aws-s3 input

### ISSUE THREAD

**Issue by bhapas** [elastic/integrations#7034]
There are missing system tests for integrations with `awss3` input type. So , this issue consolidates a list of integrations that have `awss3` input and adds system tests using `terraform service deployer`. Currently the tests run against a real AWS environment but once we have support to use `Localstack` in `service deployers` then the system tests can be run against emulated cloud env.

- [x] Requires - https://github.com/elastic/beats/pull/36208
- [x] Requires - https://github.com/elastic/package-spec/pull/571
---
- [x] aws_logs https://github.com/elastic/integrations/pull/7029
- [x] sentinel-one-cloud-funnel https://github.com/elastic/integrations/pull/8386
- [x] cisco_umbrella https://github.com/elastic/integrations/pull/8388
- [x] trellix_edr_cloud https://github.com/elastic/integrations/pull/8392
- [x] aws https://github.com/elastic/integrations/pull/8398

**Comment by bhapas** [comment]
amazon_security_lake has issues related to elastic-package not supporting verification of events based on dataset name, rather verifying using the standard naming procedure `packageName-datastreamName-ep`. Hence moving this to #8439

**Comment by bhapas** [comment]
Closing this issue and followup in favour of #8439
