### ISSUE TITLE
[Meta] Provide the dashboard level filters to dashboards

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#7217]
Identify which integrations lack dashboard-level filters (for example, data_stream.dataset: "gcp.billing"). To ensure that integration users are not negatively impacted by the performance issue, it should ideally be present. Otherwise, dashboards will take longer to populate if the filters are not applied. 

- [ ] Identify the list of integration for which the dashboards level filters are absents and needed to fix it.
- [ ] Create a checklist for those integrations who need this fix
- [ ]  Status of the over all progress

## Affected Packages
TBD

**Comment by lalit-satapathy** [comment]
@milan-elastic, any update on this?

**Comment by milan-elastic** [comment]
Duplicate of https://github.com/elastic/integrations/issues/9323, hence closing
