### ISSUE TITLE
Missing enable_request_tracer option for httpjson/cel inputs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#7228]
Some integrations are missing a variable named `enable_request_tracer` to enable request tracing for the httpjson or cel input. It would be helpful for debugging purposes if all httpjson and cel inputs made this toggle option available. These are the data streams where I didn't find `enable_request_tracer`.

HTTPJSON
- [x] bitdefender.bitdefender_gravityzone #7339
- [x] bitwarden.collection #7338
- [x] bitwarden.event #7338
- [x] bitwarden.group #7338
- [x] bitwarden.policy #7338
- [x] couchbase.node #7344
- [x] hadoop.hadoop_metrics #7343
- [x] nagios_xi.nagios #7342
- [x] spring_boot.audit_events #7341
- [x] spring_boot.http_trace #7341
- [x] ti_maltiverse.indicator #7340
- [x] zeek.capture_loss #7336
- [x] zeek.connection #7336
- [x] zeek.dce_rpc #7336
- [x] zeek.dhcp #7336
- [x] zeek.dnp3 #7336
- [x] zeek.dns #7336
- [x] zeek.dpd #7336
- [x] zeek.files #7336
- [x] zeek.ftp #7336
- [x] zeek.http #7336
- [x] zeek.intel #7336
- [x] zeek.irc #7336
- [x] zeek.kerberos #7336
- [x] zeek.modbus #7336
- [x] zeek.mysql #7336
- [x] zeek.notice #7336
- [x] zeek.ntlm #7336
- [x] zeek.ntp #7336
- [x] zeek.ocsp #7336
- [x] zeek.pe #7336
- [x] zeek.radius #7336
- [x] zeek.rdp #7336
- [x] zeek.rfb #7336
- [x] zeek.signature #7336
- [x] zeek.sip #7336
- [x] zeek.smb_cmd #7336
- [x] zeek.smb_files #7336
- [x] zeek.smb_mapping #7336
- [x] zeek.smtp #7336
- [x] zeek.snmp #7336
- [x] zeek.socks #7336
- [x] zeek.ssh #7336
- [x] zeek.ssl #7336
- [x] zeek.stats #7336
- [x] zeek.syslog #7336
- [x] zeek.traceroute #7336
- [x] zeek.tunnel #7336
- [x] zeek.weird #7336
- [x] zeek.x509 #7336
- [x] zeronetworks.audit #7337

CEL
- [x] trellix_epo_cloud.device #7334
- [x] trellix_epo_cloud.event #7334
- [x] trellix_epo_cloud.group #7334

**Comment by chemamartinez** [comment]
@andrewkroh @efd6 while reviewing the PRs I am asking myself what happens if users enabling this feature want to modify the file location and also the other available [settings](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-cel.html#_resource_tracer_maxsize) such as maxsize, maxage, compress... They do not have the possibility to do it from the integration, do they?

I also found https://github.com/elastic/integrations/issues/4763 which looks like a duplicate of this one, just in case it has been missed.

**Comment by efd6** [comment]
> They do not have the possibility to do it from the integration, do they?

That's correct.

**Comment by andrewkroh** [comment]
I think a simple on/off toggle is ideal for the purposes of temporarily enabling verbose request logging. Exposing more settings adds opportunity for something to be misconfigured which compounds the problem the user is trying to debug. If there are settings that need tuned to make request logging work correctly when the toggle is enabled for a given integration then we should set them for all users (e.g. the maxsize might be one setting that needs increased if we know an integration produces huge responses).

#4763 should have been closed and is now.
