### ISSUE TITLE
[META] Azure Maintenance

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#7591]
```[tasklist]
### Improvements
- [ ] https://github.com/elastic/integrations/issues/7511
- [ ] https://github.com/elastic/integrations/issues/4111
- [ ] https://github.com/elastic/beats/issues/36377
```

```[tasklist]
### SDK Upgrades
- [ ] https://github.com/elastic/beats/issues/33815
- [ ] https://github.com/elastic/beats/issues/33278
```

```[tasklist]
### Docs
- [ ] https://github.com/elastic/integrations/issues/7586
- [ ] https://github.com/elastic/integrations/issues/7181
- [ ] https://github.com/elastic/integrations/issues/7032
- [ ] https://github.com/elastic/integrations/issues/4581
```

```[tasklist]
### Problems
- [ ] https://github.com/elastic/beats/issues/36181
- [ ] https://github.com/elastic/integrations/issues/7424
- [ ] https://github.com/elastic/integrations/issues/5880
- [ ] https://github.com/elastic/integrations/issues/5453
```
