### ISSUE TITLE
Azure Application Insights TSDB Enablement

### ISSUE THREAD

**Issue by gpop63** [elastic/integrations#7616]
## Test Environment Setup

- [x] Created Test Environment

## Data Stream: `app_insights`

- [x] Add dimensions and metric_types #7610

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `app_state`

- [x] Add dimensions and metric_types #7550

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## TSDB Release PR
- [ ] PR to enable TSDB #8648

## Screenshots

**Comment by gpop63** [comment]
Currently, both `app_state` and `app_insights` data streams use flattened type for `azure.dimensions`.

From my understanding there are 2 approaches since flattened type can't be a dimension at the moment:

- Keep it `flattened`, add an ingest pipeline to extract fields and mark them as dimensions
- Convert `azure.dimensions` to `group` which would provide more flexibility (breaking change?)

**Comment by gpop63** [comment]
Since `app_state` has predefined metrics/dimensions, it might make sense to convert `azure.dimensions` to a `group`.

`app_insights` data stream provides more flexibility to the user and they can define the metrics/dimensions they want to fetch. In this case, `azure.dimensions` could be converted to an `object`, to have some consistency across all cloud packages.

**Comment by gpop63** [comment]
Currently blocked because of the metrics grouping issue.

This change aims to fix that: https://github.com/elastic/beats/pull/36634
