### ISSUE TITLE
NATS TSDB Enablement

### ISSUE THREAD

**Issue by gpop63** [elastic/integrations#7745]
## Test Environment Setup

- [x] Created Test Environment

## Data Stream: `connection`

- [x] Add dimensions #7739
- [x] Add metric_types #7740

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `connections`

- [x] Add dimensions and metric types #7741

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `route`

- [x] Add dimensions #7742
- [x] Add metric_types #7743

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `routes`

- [x] Add dimensions and metric types #7744

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `stats`

- [x] Add dimensions #7746
- [x] Add metric_types #7747

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `subscriptions`

- [x] Add dimensions #7748
- [x] Add metric_types #7749

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## TSDB Release PR
- [x] PR to enable TSDB #8243

## Screenshots
