### ISSUE TITLE
[Meta] GCP Metrics Maintenance

### ISSUE THREAD

**Issue by endorama** [elastic/integrations#7751]
```[tasklist]
### Improvements
- [ ] https://github.com/elastic/integrations/issues/2794
- [ ] https://github.com/elastic/integrations/issues/7555
- [ ] https://github.com/elastic/integrations/issues/7400
- [ ] https://github.com/elastic/integrations/issues/5059
- [ ] https://github.com/elastic/integrations/issues/5169
- [ ] https://github.com/elastic/integrations/issues/5020
- [ ] https://github.com/elastic/beats/issues/30912
- [ ] https://github.com/elastic/beats/issues/30434
- [ ] https://github.com/elastic/beats/issues/21552
- [ ] https://github.com/elastic/beats/issues/29573
- [ ] https://github.com/elastic/beats/issues/25471
```

```[tasklist]
### SDK Upgrades
```

```[tasklist]
### Docs
```

```[tasklist]
### Problems
- [ ] https://github.com/elastic/integrations/issues/762
- [ ] https://github.com/elastic/integrations/issues/6568
- [ ] https://github.com/elastic/integrations/issues/7400
- [ ] https://github.com/elastic/integrations/issues/5127
- [ ] https://github.com/elastic/integrations/issues/4667
- [ ] https://github.com/elastic/integrations/issues/4172
- [ ] https://github.com/elastic/integrations/issues/4614
- [ ] https://github.com/elastic/integrations/issues/4375
- [ ] https://github.com/elastic/beats/issues/33118
- [ ] https://github.com/elastic/beats/issues/30911
- [ ] https://github.com/elastic/beats/issues/17552
- [ ] https://github.com/elastic/beats/issues/35092
- [ ] https://github.com/elastic/beats/issues/35098
- [ ] https://github.com/elastic/beats/issues/35091
- [ ] https://github.com/elastic/beats/issues/29573
- [ ] https://github.com/elastic/beats/issues/30217
- [ ] https://github.com/elastic/beats/issues/15613
```
