### ISSUE TITLE
[Meta] Lens migration phase 4

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#7797]
The initiative to migrate visualizations from TSVB to Lens was launched in the 8.8 release. This migration's first, second and third phases focused on prioritizing critical service, and cloud integrations. The list of phases can be found in below tracker issue:

**Phases and issues tracker https://github.com/elastic/integrations/issues/6489** 

Continuing with our efforts in the same direction, the goal of Lens Migration Phase 4 is to migrate key Cloud-native Integrations. This issue describes the tasks to be accomplished in this phase.

- [x] Creating a Migrations Check List
- [x] Migrations Status

## **Confirmed Integrations:**

**Completed Integrations:**
- [x] Kubernetes https://github.com/elastic/integrations/issues/7774
- [x] Nats https://github.com/elastic/integrations/issues/7777
- [x] Containerd https://github.com/elastic/integrations/issues/8057
- [x] docker https://github.com/elastic/integrations/issues/7775
- [x] Prometheus https://github.com/elastic/integrations/issues/7776
- [x] Nginx Ingress Controller https://github.com/elastic/integrations/issues/7812
- [x] Stan https://github.com/elastic/integrations/issues/7778
- [x] Windows https://github.com/elastic/integrations/issues/8161

## Blocker issues
- https://github.com/elastic/integrations/issues/7916
- https://github.com/elastic/kibana/issues/135883

**Comment by kush-elastic** [comment]
Upon consultation with @SubhrataK, we have opted to migrate only the following data streams as part of the Windows Lens migration process:
- Service
- Performance Monitoring (perfmon)

**Comment by rajvi-elastic** [comment]
All mentioned integration are migrated to lens therefore closing this issue.
