### ISSUE TITLE
STAN TSDB Enablement

### ISSUE THREAD

**Issue by gpop63** [elastic/integrations#7859]
## Test Environment Setup

- [x] Created Test Environment

## Data Stream: `channels`

- [x] Add dimensions #7863
- [x] Add metric_types #7862

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `stats`

- [x] Add dimensions #7864
- [x] Add metric_types #7861

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## Data Stream: `subscriptions`

- [x] Add dimensions #7865
- [x] Add metric_types #7860

**Verification and validation**
- [x] Verification of data in visualisation after enabling TSDB flag in kibana
- [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
- [x] Verify if dimension field mapping is correct in the data stream template.

## TSDB Release PR
- [x] PR to enable TSDB #8333

## Screenshots

**Comment by gpop63** [comment]
The dashboard for STAN metrics seems to be broken - visualizations are not loaded (this has to be addressed).
I recreated the lenses just for visualization and data validation purposes.

![scrnli_9_22_2023_12-15-28 AM](https://github.com/elastic/integrations/assets/94497545/b15547c9-75ae-4e54-a4eb-ed71481342fd)

**Comment by agithomas** [comment]
> The dashboard for STAN metrics seems to be broken

Found a [PR](https://github.com/elastic/integrations/pull/7959) to fix the issue

**Comment by lalit-satapathy** [comment]
> > The dashboard for STAN metrics seems to be broken
> 
> Found a [PR](https://github.com/elastic/integrations/pull/7959) to fix the issue

@gpop63, Is the latest dashboard working fine now and with the TSDB changes?

**Comment by gpop63** [comment]
> @gpop63, Is the latest dashboard working fine now and with the TSDB changes?

Yes.

![scrnli_11_8_2023_10-36-05 PM](https://github.com/elastic/integrations/assets/94497545/42e95510-17d3-4833-8cd8-45bfb5329e0a)

**Comment by mlunadia** [comment]
@lalit-satapathy can you please help getting someone to review this PR?

**Comment by lalit-satapathy** [comment]
> @lalit-satapathy can you please help getting someone to review this PR?

TSDB enablement [PR](https://github.com/elastic/integrations/pull/8333) approved.
