### ISSUE TITLE
[stack monitoring] remove beta flags

### ISSUE THREAD

**Issue by klacabane** [elastic/integrations#8040]
### Summary
The data streams powering stack monitoring are flagged as beta in elasticsearch/kibana/logstash packages. We can remove these flags to make them ga as satisfying testing/bugfix was done

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/integrations/pull/8044
- [ ] https://github.com/elastic/kibana/pull/167867
- [ ] https://github.com/elastic/kibana/issues/175794
```

**Comment by miltonhultgren** [comment]
@klacabane Is this still in progress?

**Comment by klacabane** [comment]
I'll merge the pending doc PR and create backlog issue for the suggested improvement

**Comment by klacabane** [comment]
Closing as https://github.com/elastic/kibana/issues/175794 won't be prioritized for now
