### ISSUE TITLE
Bulk package-spec v3 migration of packages for serverless

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#8147]
```[tasklist]
### Tasks
- [ ] https://github.com/elastic/integrations/pull/8170
- [ ] https://github.com/elastic/integrations/pull/8171
- [ ] https://github.com/elastic/integrations/pull/8159
- [ ] https://github.com/elastic/integrations/pull/8203
```

**Comment by shmsr** [comment]
Related links:

- https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md
- https://github.com/elastic/integrations/pull/8041 (sample PR)
- https://github.com/elastic/integrations/pull/8031 (sample PR)

**Comment by shmsr** [comment]
Rough notes (challenges faced while migrating to package-spec v3):

- https://github.com/elastic/integrations/pull/8170#issuecomment-1758996108
- https://github.com/elastic/integrations/pull/8171#issuecomment-1759389301
- https://github.com/elastic/integrations/pull/8203#issuecomment-1763791793

**Comment by shmsr** [comment]
pinging: 
@elastic/obs-service-integrations for review
@tommyers-elastic for review

**Comment by shmsr** [comment]
Have made the changes in batches so that it is easier to review.

In total 48 packages are owned by `@elastic/obs-infraobs-integrations` as per CODEOWNERS
```
$ pkgs=($(cat .github/CODEOWNERS | grep '@elastic/obs-infraobs-integrations' | cut -d ' ' -f 1 | cut -d '/' -f 3 | sort | uniq)
```

So packages are migrated in a batch of 15, 15 and 18 (15+15+18=48).

**Comment by shmsr** [comment]
Please read the rough notes carefully before reviewing because some packages need a thorough review.

**Comment by shmsr** [comment]
Also see https://github.com/elastic/integrations/pull/8174 before review. Related changes are there in all 3 PRs. As a side-effect of transformation that elastic-package makes, some fields needs to be quoted in test configuration files.

**Comment by tommyers-elastic** [comment]
closing this issue in favour of the tracking issue [here](https://github.com/elastic/integrations/issues/8028)
