### ISSUE TITLE
[Security Integrations] Moving integrations from Tech Preview to GA

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8389]
We currently have a number of integrations under Tech Preview, which have been available for some and we can confidently move to GA. 

- [ ] Amazon Security Lake
- [ ] Arista NG Firewall
- [ ] Cisco Nexus
- [x] Custom Azure Blob https://github.com/elastic/integrations/pull/8577
- [x] Custom Google Cloud Storage https://github.com/elastic/integrations/pull/8515
- [ ] Google Security Command Center
- [ ] Imperva
- [ ] Mandiant Advantage
- [ ] Maltiverse
- [ ] Microsoft Defender for Cloud
- [ ] Microsoft Entra ID Entity Analytics
- [ ] Okta Entity Analytics
- [ ] OpenCTI
- [ ] Palo Alto Prisma Cloud
- [ ] Qualys VMDR
- [ ] SentinelOne Cloud Funnel
- [ ] Symantec EDR Cloud
- [ ] Trellix EDR Cloud
- [ ] Wiz

~~Custom AWS Logs (confirm with o11y/cloud team??)~~ (Tracked separately by: https://github.com/elastic/integrations/issues/8919)
