### ISSUE TITLE
elastic/obs-infraobs-integrations: Issues blocking migration to format_version 3.0.0 (package-spec v3)

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#8450]
Parent: https://github.com/elastic/integrations/issues/8028

Here are a few blockers:

```[tasklist]
### Tasks
- [ ] #8209
- [x] [azure_app_service]: resolving external fields failed: can't resolve fields: field geo.continent_name cannot be reused at top level (see: [#1](https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md#error-building-package-failed-resolving-external-fields-failed-cant-resolve-fields-field--cannot-be-reused-at-top-level))
- [x] [citrix_adc]: resolving external fields failed: can't resolve fields: field interface.id cannot be reused at top level
- [ ] #8210
- [ ] #8211
- [x] [redis]: resolving external fields failed: can't resolve fields: field os.full cannot be reused at top level
- [x] [tomcat]: resolving external fields failed: can't resolve fields: field geo.city_name cannot be reused at top level
- [ ] [nagios_xi]: multiple set processors setting `event.dataset` in [this](https://github.com/elastic/integrations/blob/main/packages/nagios_xi/data_stream/service/elasticsearch/ingest_pipeline/default.yml) file. (see: [#1](https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md#field-eventdataset-should-have-value--it-has-)). Probable fix could be a breaking change.
```

**Comment by andrewkroh** [comment]
This appears to be complete. All of the mentioned integrations are on format_version: >=3.0.0.
