### ISSUE TITLE
elastic/obs-infraobs-integrations: Issues non-blocking migration to format_version 3.0.0 (package-spec v3)

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#8451]
Parent: https://github.com/elastic/integrations/issues/8028

```[tasklist]
### Tasks
- [x] [etcd]: While migrating we noticed the type `{backend_commit_duration,wal_fsync_duration}.ns.{count,sum}` is set to long but it should be float instead. ([ref](https://github.com/prometheus/prometheus/blob/main/model/histogram/histogram.go#L64))
- [x] [azure_app_service]: `geo` mappings are not allowed at root level in ECS ([ref](https://github.com/elastic/integrations/pull/8216))
- [x] [citrix_adc]: `interface` mappings are not allowed at root level in ECS ([ref](https://github.com/elastic/integrations/pull/8216)). Also, `interface` be nested like observer.egress.interface.*. Please refer ECS docs.
- [x] [redis]: `os` mappings are not allowed at root level in ECS ([ref](https://github.com/elastic/integrations/pull/8216))
- [x] [tomcat]: `geo` mappings are not allowed at root level in ECS ([ref](https://github.com/elastic/integrations/pull/8216))
```
