### ISSUE TITLE
elastic/obs-infraobs-integrations: Skipped validations during migration of packages to format_version: 3.0.0 (package-spec v3)

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#8452]
Parent: https://github.com/elastic/integrations/issues/8028

| Package name | Validation skipped | Progress |
| ------------ | ------------------ | -------- |
| activemq | SVR00004,SVR00002 | <li>- [ ] </li> |
| airflow | SVR00002 | <li>- [ ] </li> |
| apache_spark | SVR00004,SVR00002 | <li>- [ ] </li> |
| apache_tomcat | SVR00004 | <li>- [ ] </li> |
| azure_functions | SVR00004,SVR00002 | <li>- [ ] </li> |
| cassandra | SVR00004,SVR00002 | <li>- [ ] </li> |
| ceph | SVR00002 | <li>- [ ] </li> |
| cockroachdb | SVR00002 | <li>- [ ] </li> |
| coredns | SVR00002 | <li>- [ ] </li> |
| couchbase | SVR00002 | <li>- [ ] </li> |
| couchdb | SVR00002 | <li>- [ ] </li> |
| etcd | SVR00002 | <li>- [ ] </li> |
| golang | SVR00002 | <li>- [ ] </li> |
| hadoop | SVR00004,SVR00002 | <li>- [ ] </li> |
| iis | SVR00002,SVR00004 | <li>- [ ] </li> |
| influxdb | SVR00002 | <li>- [ ] </li> |
| kafka | SVR00002,SVR00004 | <li>- [ ] </li> |
| memcached | SVR00003,SVR00002 | <li>- [ ] </li> |
| microsoft_sqlserver | SVR00004,SVR00002 | <li>- [ ] </li> |
| mongodb | SVR00004,SVR00002 | <li>- [ ] </li> |
| mysql | SVR00002,SVR00004 | <li>- [ ] </li> |
| nginx | SVR00004,SVR00002 | <li>- [ ] </li> |
| oracle | SVR00002 | <li>- [ ] </li> |
| oracle_weblogic | SVR00002,SVR00004 | <li>- [ ] </li> |
| postgresql | SVR00001,SVR00002,SVR00004 | <li>- [ ] </li> |
| rabbitmq | SVR00002 | <li>- [ ] </li> |
| redisenterprise | SVR00002 | <li>- [ ] </li> |
| salesforce | SVR00002 | <li>- [ ] </li> |
| spring_boot | SVR00004,SVR00002 | <li>- [ ] </li> |
| system (upgrade by different team) | SVR00004,SVR00002 | <li>- [ ] </li> |
| traefik | SVR00004,SVR00002 | <li>- [ ] </li> |
| vsphere | SVR00002 | <li>- [ ] </li> |
| websphere_application_server | SVR00004,SVR00002 | <li>- [ ] </li> |
| zookeeper | SVR00002 | <li>- [ ] </li> |
| citrix_adc | SVR00002 | <li>- [ ] </li> |
| redis | SVR00002,SVR00004 | <li>- [ ] </li> |
```[tasklist]
### Tasks
- [ ] https://github.com/elastic/integrations/pull/8347
- [ ] https://github.com/elastic/integrations/pull/8348
- [ ] https://github.com/elastic/integrations/pull/8423
- [ ] https://github.com/elastic/integrations/issues/8938
```

**Comment by shmsr** [comment]
Please refresh the table after every PR merge in the tasklist.

**Comment by shmsr** [comment]
Update: As the inliner script is upgraded to inline saved searches too (see: https://github.com/elastic/visualizations_integrations_tools/issues/2) we can migrate most probably all packages now for whom we have skipped validation SVR00004.

Please see the description to see all the packages with skipped validation SVR00004 and also https://github.com/elastic/integrations/pull/8423 where already 8 packages have inlined viz.

I am creating a new issue to address SVR00004 for all other remaining packages.
