### ISSUE TITLE
[Entity Analytics] Active Directory

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8559]
### Description
Now that we have integrations to ingest contextual information relating to user/group/device data from Azure EntraID (formerly AzureAD), we need to ensure that users who have now moved to EntraID and still running Active Directory on-premises have the ability to ingest the same user/group/device data. 

Our Active Directory Entity Analytics integration should have the ability to connect to Active Directory (presumably via LDAP) and ingest data such as usernames, department, title, group membership, last login, locked out status, last password change date and more. We can explore the full set of fields once we've figured out the LDAP connection and what fields are available to us. 

As a user of the Security Solution I want to continuously sync user metadata from an Okta organization into Elasticsearch. Data is produced in accordance to [RFC 2022-09-07-user-host-entity-ingestion](https://github.com/elastic/security-external-integrations/blob/078acbafbdec6668ef387244096d082a239ef38f/rfcs/2022/2022-09-07-user-host-entity-ingestion.md).

Acceptance Criteria

- [x] Collect user data from Active Directory via a new provider in the entity_analytics Filebeat input.
- [x] Generate one document per user that includes group membership data
- [x] Periodically get a list of users that were modified or deprovisioned and generate new documents
- [x]  Persist data to disk that allows the input to resume from previous state

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to: v8.13.0

### New Package

- [ ] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [ ] Dashboards exists
- [ ] Screenshots added or updated
- [ ] Datastream filters added to visualizations

### Log dataset changes

- [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [ ] Generated output for at least 1 log file exists
- [ ] Sample event (`sample_event.json`) exists

**Comment by SourinPaul** [comment]
@jamiehynds this issue is currently not in the security-teams repo. Hence, I could not assign the `v8.13.0` label to this issue.

Can you please update this label? Thanks!
