### ISSUE TITLE
[containerd] TSDB Enablement

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#8613]
## TSDB Enablement
 - [x] PR link - #8954
 
## Test Environment Setup
- [x] #8614

## Datastream : `cpu` 
  - [x] Add dimension fields - #8893
  - [x] TSDB Package test completion

## Datastream : `blkio` 
  - [x] Add dimension fields - #8894
  - [x] TSDB Package test completion

## Datastream : `memory` 
  - [x] Add dimension fields - #8892
  - [x] TSDB Package test completion
