### ISSUE TITLE
[Meta] Add more benchmark schema templates to integrations

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#8636]
In https://github.com/elastic/elastic-package/issues/1476 the initial schema templates from the corpus generator repo were added to the integrations. Ideally all integrations would have templates but as this is not feasible, lets start small. This is a meta issue to track the top 5 integrations for which schemas should be added. The proposed list is:

* system
* nginx
* k8s
* aws / aws_logs
* mysql

Each of these integrations have quite a few datasets, for detailed tracking the datasets are listed below (this list might change over time).  Adding these dataset will potentially also add new requirements to the corpus which is expected. These additions in combination with the [stream command](https://github.com/elastic/elastic-package/issues/1541) will allow anyone to test integrations against a running Elastic Stack instance. The expected outcome is that the integration dashboards show mostly "reasonable" data. It is not expected that necessarily cross linking is possible or the data shown makes a 100% sense. For example CPU usage might fluctuate faster then in reality.

# Tracking: Dataset list

Below is the list of integrations and dataset for tracking. Lets add reference to PR or code if completed. For each integration, lets add the most important datasets.

* [x] K8s
  * [x] [kubernetes.container](https://github.com/elastic/integrations/tree/main/packages/kubernetes/_dev/benchmark/rally/container-benchmark)
  * [x] [kubernetes.pods](https://github.com/elastic/integrations/tree/main/packages/kubernetes/_dev/benchmark/rally/pod-benchmark)
  * [x] [kubernetes.node](https://github.com/elastic/integrations/pull/9100)
  * [x] [kubernetes.state_container](https://github.com/elastic/integrations/pull/9106)
  * [x] [kubernetes.state_pod](https://github.com/elastic/integrations/pull/9136)
  * [x] [kubernetes.events](https://github.com/elastic/integrations/pull/9161)
* [x] AWS
    - [x] [billing](https://github.com/elastic/integrations/pull/8403)
    - [x] [ec2_logs](https://github.com/elastic/integrations/pull/8416)
    - [x] [ec2_metrics](https://github.com/elastic/integrations/pull/8442)
    - [x] [sqs](https://github.com/elastic/integrations/pull/8429)
    - [x] [vpcflow](https://github.com/elastic/integrations/pull/9242)
    - [x] [waf](https://github.com/elastic/integrations/pull/9377)
    - [x] [cloudtrail](https://github.com/elastic/integrations/pull/9448)
* [x] Nginx
    - [x] [access](https://github.com/elastic/integrations/pull/9032)
    - [x] [error](https://github.com/elastic/integrations/pull/8762)
    - [x] [stub_status](https://github.com/elastic/integrations/pull/8800)
* [x] System
    - [x] [cpu](https://github.com/elastic/integrations/pull/9294)
    - [x] [diskio](https://github.com/elastic/integrations/pull/9295)
    - [x] [memory](https://github.com/elastic/integrations/pull/9296)
- [x] MySQL
    - [x] [error](https://github.com/elastic/integrations/pull/8957)
    - [x] [performance](https://github.com/elastic/integrations/pull/8761)
    - [x] [slowlog](https://github.com/elastic/integrations/pull/9024)
    - [x] [status](https://github.com/elastic/integrations/pull/8868)
    - [x] [galera_status](https://github.com/elastic/integrations/pull/8923)

**Comment by lalit-satapathy** [comment]
We have a low level issue: https://github.com/elastic/integrations/issues/8719 which will be closed (not immediately but after all the WIP PRs are done) and we can use this top level issue for tracking of all package level template additions. 

Right now adding Aliabbas as owner, please add anyone else as applicable.

Also adding the issue into relevant project boards.

**Comment by lalit-satapathy** [comment]
Hi @ruflin,

Since all the data streams benchmark schema templates are completed, can this issue be closed or any additional package(s) we should expand the scope it?

**Comment by ruflin** [comment]
This is great @lalit-satapathy Are the templates used to run benchmarks that we also look at from time to time?

We can close this issue but lets make sure we follow up on actively using these templates for developing features and running benchmarks.
