### ISSUE TITLE
[Meta] Highlight packages that need to be run as root

### ISSUE THREAD

**Issue by jlind23** [elastic/integrations#8642]
We are driving an effort to encourage the declaration packages that need to be run as root.
This option has been added [here](https://github.com/elastic/package-spec/issues/537) and will require new package version in order to let developers define this value.

By default all packages are NOT marked as requiring root privileges to properly run which might lead to confusion if users try to deploy a package that need root privileges but that was never updated.
```[tasklist]
### Tasks
- [ ] https://github.com/elastic/integrations/issues/8647
- [ ] https://github.com/elastic/integrations/pull/8651
- [ ] https://github.com/elastic/elastic-package/issues/1586
```

**Comment by jlind23** [comment]
@epixa @bturquet could you please share with us any related issues you might have on your end?

**Comment by nimarezainia** [comment]
fyi: @jamiehynds @andrewkroh

**Comment by florianl** [comment]
Universal Profiling is affected as well but should be fixed with https://github.com/elastic/integrations/pull/8651.

Just out of curiosity:
What is the expected behavior if `agent.privileges.root = true` from the manifest of the integration package conflicts with `runtime.preventions.condition` in the [specification of EA supervised processes](https://github.com/elastic/elastic-agent/tree/main/specs)? And why do we need both?

**Comment by jlind23** [comment]
Both are not linked for now but need to be done in a near future where Agent will need to report through metadata the mode it is running in.
We need both to avoid something like:
- Users install an integration that needs root privileges but the agent is not run as root
- Users will be able to do it as the UI can not prevent this because Fleet does not know in which mode the Agent is running

**Comment by nimarezainia** [comment]
I'd say do it for all the packages and datastreams. Whether we have the implementation for Windows or not. At the moment, this mainly allows us to notify the user and there are no controls or checks to see what mode the agent is running.

**Comment by nimarezainia** [comment]
@graphaelli & @simitt wanted to also bring this issue to your attention.

**Comment by lucabelluccini** [comment]
Added https://github.com/elastic/integration-docs/issues/288

**Comment by jlind23** [comment]
Thanks @lucabelluccini.
@norrietaylor @epixa were you able to make some progress on your end?

**Comment by jlind23** [comment]
@bturquet @lalit-satapathy any follow up issue to add here or will all 'your' integrations work out of the box without root/admin privilegeS?

**Comment by nimarezainia** [comment]
> Last time we discussed it we could not think of any issues for Hosted Services

@bturquet does your team have a suite of smoktests for us to determine how the proposed changes will impact the integrations? We have a linux image that is going through some smoketesting. It would be great to be as comprehensive as possible.

**Comment by simitt** [comment]
The apm-server itself does not require root privileges, so we do not expect issues with the apm-server. Once this is available for testing, please let us know so we can verify everything still works as expected.

**Comment by jlind23** [comment]
@simitt this is available for testing on linux host once you provide the `--unprivileged` flag.
cc @pierrehilbert @cmacknz

**Comment by simitt** [comment]
@jlind23 I'm a bit confused now, my understanding is as follows: starting in version x (`8.13`?) the Elastic Agent will _by default_ not run sub-processes with root privileges anymore. Integrations that do require root privileges need to update the package spec to specifically set `agent.privileges.root: true`. APM Server does not want to be run with root privileges, therefore there are no plans for updating apm package. 
My assumption was that once a PR with the Elastic Agent changes is ready (or merged), we can test with this Elastic Agent branch, without any changes on apm side. If everything still works, we are good. 

It's not clear to me from reading this and related issues where the `--unprivileged` flag comes in.

**Comment by pierrehilbert** [comment]
Hey @simitt 
The Agent will continue to run with root privileges by default in 8.13 and the `--unprivileged` (hidden flag for now as this is only experimental) is the way to run Agent without root privileges.

**Comment by lalit-satapathy** [comment]
> @bturquet @lalit-satapathy @tommyers-elastic any follow up issue to add here or will all 'your' integrations work out of the box without root/admin privilegeS?

Hi @jlind23,
 
Is there a quick way to find out which integration would require a root access to be run? Are there any static checks today, which will fail, if _agent.privileges_ is not set and the integration requires a root permission?

Out of the long list integrations, How do we find some specific corner case integration requiring root permission, if any ?

**Comment by cmacknz** [comment]
> Out of the long list integrations, How do we find some specific corner case integration requiring root permission, if any ?

More specifically than root, it will be anything that a basic user on the system cannot do without being granted additional privileges. 

1. Requiring elevated privileges to use restricted OS or kernel level features. On Linux things like BPF, installing kernel modules, network packet capture, possibly interacting with the audit framework. I will make a bit of an assumption here that most integrations doing this know they are doing it, and you unlikely to be surprised that you fall into this category.
2. Reading files whose default permissions are restricted to root or specific groups. A good example is the system integration where on Linux it tries to read from `/var/log/auth.log` and `/var/log/syslog' by default, on Ubuntu systems you need to be in the `adm` group to do this. See https://github.com/elastic/elastic-agent/issues/4112#issuecomment-1904082802. On Windows this would be having additional group memberships like `Performance Monitor Users` and `Event Logs Reader`.

That second category will be the one that causes the most problems, because anything that reads a log file is potentially affected depending on where that log file is located.

This should allow us to exclude certain integrations from being affected quickly as well, for example integrations that are are making HTTP requests should not require root.

> Is there a quick way to find out which integration would require a root access to be run? Are there any static checks today, which will fail, if agent.privileges is not set and the integration requires a root permission?

One thing that complicates this is that the tests in this repository run in containers, and container file systems do not always match up with the official native file system of that Linux distribution. For example the ubuntu:22.04 container does not contain `/var/log/auth.log` or `/var/log/syslog` but an Ubuntu 22.04 VM image does.

**Comment by lalit-satapathy** [comment]
@cmacknz, This is a good list of what to look for checking packages requiring  root access. Assuming system & windows packages are being looked into already.

>A quick addition to this, there are ports that require root to bind to them (those <1024) so integrations that implement servers are potentially affected depending on what ports they use.

Does [stated input](https://docs.elastic.co/integrations/statsd_input) fit into this category? This is one of inputs, where we are spawning a server in metricbeat.

**Comment by jlind23** [comment]
@lalit-satapathy You are probably the most knowledgeable about this input as according to the [CODEOWNERS](https://github.com/elastic/integrations/blob/42da1a0cd814b52285e32f02927a369d5eafdda4/.github/CODEOWNERS#L285C1-L286C1) file your team is owning it.

The Elastic Agent team will not test each and every integration, this has to be done by the packages owners.
We are working on two things:
- With `elastic-package` allowing system tests to run with a non root user - https://github.com/elastic/elastic-package/issues/1586
- `elastic-agent` integration tests were also updated - https://github.com/elastic/elastic-agent/pull/3931

**Comment by jlind23** [comment]
@kpollich What do you think about closing this as the only remaining task is https://github.com/elastic/elastic-package/issues/1586? Using only https://github.com/elastic/elastic-package/issues/1586 is probably enough wdyt?

**Comment by kpollich** [comment]
Yes we can close this issue in favor of the Elastic Package work. FYI that issue is blocked on https://github.com/elastic/elastic-package/issues/787 for now.
