### ISSUE TITLE
[MongoDB] replstatus large temp files and sort function issues

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#8683]
**Reference :** 

We have multiple seemingly related issues for high disk usage and temp files generated in MongoDB 

- https://discuss.elastic.co/t/metricbeat-8-8-1-mongodb-module-error-fetching-data-replstatus-sort-operation-used-more-than-the-maximum-bytes-of-ram/348057
- https://discuss.elastic.co/t/mongodb-integration-generates-huge-amount-of-temp-files/350226 

**Reference:**

```
When trying to set up the mongodb.replstatus metricset on my replica set (MongoDB v3.6), I am given the error:
Error fetching data for metricset mongodb.replstatus: error getting replication info: could not get last operation timestamp in oplog: could not get cursor on collection 'oplog.rs': (OperationFailed) Executor error during find command :: caused by :: errormsg: "Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."

My oplog collection totals 16GB.

The error seems to happen when the the module attempts to sort the oplog in reverse natural order and get the first result.

From a quick look at the module's source code, the module appears to be executing the query db["oplog.rs"].find({}).sort({ "-$natural": 1 }) to get the last entry in the oplog. Executing this query through the Mongo shell throws the same out of RAM error.

Executing the query db["oplog.rs"].find({}).sort({ "$natural": -1 }) appears to provide the same ordering of results, and does not throw the same error.

```

```[tasklist]
### Tasks
- [ ] Replicate the sorting problem and large temp files generation. https://github.com/elastic/obs-infraobs-team/issues/1295
- [ ] Technical proposal of the solution
- [ ] Early proto code changes in beats
- [ ] Validate using the proto code
- [ ] Close PR/release (beats & integration)
```

**Comment by agithomas** [comment]
Possible area for investigation : [here](https://github.com/elastic/beats/blob/49ae09a5614b79696fd02e752bee56492a9ca72d/metricbeat/module/mongodb/replstatus/info.go#L95)
