### ISSUE TITLE
File Integrity Monitoring | User Information - Linux | KProbe Backend

### ISSUE THREAD

**Issue by Tacklebox** [elastic/integrations#8692]
This is a subtask of #7401 to track tasks related specifically to the KProbe backend for the FIM module in auditbeat

Targeting 8.13 FF

```[tasklist]
### Tasks
- [x] Implement tk-btf library to support generating kprobe strings from btf symbols
- [x] Implement runtime verification of probes for FIM
- [x] Implement in memory data structure to react and filter probe events and monitor the given paths from the auditbeat configuration
- [x] Align with ebpf implementation of FIM's ECS structure and implement events reader
- [x] Investigate e2e coverage and implement necessary tests to ensure end to end coverage
- [x] support reporting uid and gid of pid that caused the file event utilising the add_process_metadata processor
- [ ] update auditbeat running on docker page to capture the requirements of FIM with kprobes backend
- [ ] support input metrics [not required for completion]
```

**Comment by pkoutsovasilis** [comment]
all of the above tasks are captured [in this PR](https://github.com/elastic/beats/pull/37796).

**Comment by pkoutsovasilis** [comment]
PRs pending to be merged 

- https://github.com/elastic/beats/pull/38199
- https://github.com/elastic/beats/pull/38328
- https://github.com/elastic/beats/pull/38716
- https://github.com/elastic/integrations/pull/8807

when all the above are merged FIM can report `uid` and `gid` for both `ebpf` and `kprobes` backends

**Comment by norrietaylor** [comment]
@pkoutsovasilis can we mark this as done?

**Comment by pkoutsovasilis** [comment]
> @pkoutsovasilis can we mark this as done?

I think that yes; the metrics is something that we need to discuss whether it makes sense to have or not and how to make it for all FIM backends. Now about the docs we should do it but when the kprobes BE hits GA

**Comment by norrietaylor** [comment]
marking done, tracking further work in parent epic.
