### ISSUE TITLE
Shipping SLOs with Integration Packages

### ISSUE THREAD

**Issue by SubhrataK** [elastic/integrations#8903]

**Comment by muthu-mps** [comment]
### Updates
The manual process to create the SLO has been done. The steps will be captured in this issue. As part of integrating the SLOs in the integrations there are quite a few areas that needs to be worked on. Some of them has already in place and few of them are work in progress. I am capturing the detailed summary of what is done already and the in-progress tasks. As a first step we will have the SLOs configured and installed for Nginx integration.
### Tasks

- [x] https://github.com/elastic/package-spec/pull/767
  - For the integrations to add the SLOs the package-spec should include the SLO definition's. This is already done in the above PR.

- [ ] https://github.com/elastic/kibana/pull/186974

  - At the moment the FLEET API to install the SLOs is in-progress and the above PR has updates on the same.
  - The expectation would be to have support for installing the SLOs, Updating the SLOs and Deleting the SLOs from the integration install.
- [ ] https://github.com/elastic/integrations/pull/10269
  - The above PR includes an SLO for Nginx integration to test the process end-to-end.
  - The SLO defined here is to check the service availability.

**Comment by muthu-mps** [comment]
As discussed with @mgiota and @grabowskit over the slack, We will not be creating the `burn_rate_rule` from the integrations. The user can create or edit the burn rate rule from the UI itself.
