### ISSUE TITLE
[Meta][CrowdStrike] Supporting Event Streaming API

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9082]
Our existing CrowdStrike integration requires the [Falcon SIEM Connector ](https://www.crowdstrike.com/blog/tech-center/integrate-with-your-siem/) in order to pull detections and audit events from Falcon. This adds complexity and a maintenance overhead for users which could be eliminated if our integration connected directly to Falcon's Event Streaming API to pull the data. 

The Event Streaming API works differently to most API's we interact with and our CEL or HTTPJSON inputs cannot currently handle API. In order to get data, you keep one request open indefinitely, while periodically making an independent request to refresh the streaming session to keep it alive. 

In order to unblock us from adding support for the Event Streaming API, we need to research if a new input is required or can we bridge the functionality gap via one of our existing inputs. 
```[tasklist]
### Tasks
- [ ] https://github.com/elastic/integrations/issues/10262
- [ ] https://github.com/elastic/beats/issues/40264
- [ ] Add input/data stream to Crowdstrike integration to make use of streaming input
- [ ] Add input/data stream to Proofpoint integration to make use of streaming input
```

**Comment by jamiehynds** [comment]
Thanks for the feedback @mbudge. Based on that, if we supported the Event Streaming API directly would you envisage some value there and likely to remain on SIEM Connector?

**Comment by mbudge** [comment]
The advantage of using the SIEM connector is you can push customers to use crowdstrike support if there is a problem downloading data. 

As this one is a bit complicated with persistent connections I'd prefer to use the SIEM connector.

**Comment by NateUT99** [comment]
We have used the event stream API with a few other products, and have had good success with it. I would certainly be comfortable moving our production data ingest to this (from SIEM connector) once it becomes available.

**Comment by ShourieG** [comment]
The last time we had discussions on supporting event stream inputs the following approaches were decided upon :-
- Build a standalone input similar to the websocket  input and have support for CEL to process the responses
- Bundle both websocket and event streaming input under a single umbrella sharing common CEL code and have them aliased under say a category like "streaming inputs".

@brijesh-elastic @piyush-elastic, I recall last time we spoke on this, support for CEL was requested because support for response manipulation was required as well as support for URL modification based on cursor values. Could you confirm this and expand on the reason for CEL support ?

**Comment by piyushw-crest** [comment]
@ShourieG - Yes we did discuss on this last time for CrowdStrike only, as we have option to configure event stream API and access it via http endpoint. For more details refer this [pdf](https://www.crowdstrike.com/wp-content/uploads/2020/07/CrowdStrike-Falcon-Event-Streams-Add-on-Guide.pdf). Let me know if you need more help on the same.

**Comment by ShourieG** [comment]
> @ShourieG - Yes we did discuss on this last time for CrowdStrike only, as we have option to configure event stream API and access it via http endpoint. For more details refer this [pdf](https://www.crowdstrike.com/wp-content/uploads/2020/07/CrowdStrike-Falcon-Event-Streams-Add-on-Guide.pdf). Let me know if you need more help on the same.

@piyush-elastic thanks for the update, I was curious on the CEL support. Do you think it would add value and if what would be the use case here?

**Comment by leandrojmp** [comment]
@jamiehynds hello,

I'm a little curious if this is already GA or just in beta? We are on 8.17.3 and testing the Event Streaming API input which is already available and having some issues, but since this issue is still open I'm not sure if this input is already in GA.
