### ISSUE TITLE
[New Integration] Tychon

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9214]
Tychon provides an enterprise endpoint management platform with a focus on US Federal customers. Their platform offers capabilities such as Asset Inventory, Application Tracking, Patch Status and Vulnerability Status. Tychon have built an Elastic integration that they provide to customers via a custom package (zipped). However, an in-product integration is preferred for improved visibility. Tychon have provided us with their package, with the goal of us raising a PR on our side to get the integration into our ecosystem. 

The goal of this task is to review the integration in it's current state and adding any necessary tests, sample data, etc in order to get a PR raised, reviewed and merged. 

Tychon have agreed to support the integration long-term, so we can set this as a partner integration. 
```[tasklist]
### Tasks
- [x] Identifiying and removing redundant files between data streams
- [x] Making the integration functional
- [x] Fixing pipeline and system tests
- [x] Consolidating transforms with same source/ different destination
- [x] Testing and comparing sample logs against pipelines, introducing them into the integration
- [x] Reformatting field definitions, fix field definition versioning, identifying new ECS fields
- [ ] https://github.com/elastic/integrations/issues/10221
- [ ] https://github.com/elastic/integrations/issues/10222
- [ ] https://github.com/elastic/integrations/issues/10264
- [ ] https://github.com/elastic/integrations/issues/10263
```

**Comment by chrisberkhout** [comment]
@jamiehynds @joeperuzzi I see that https://github.com/elastic/integrations/pull/8400 was closed by the bot a couple of weeks ago. Shall we reopen that and use that as our starting point? Or is there an updated or different current state?

**Comment by chrisberkhout** [comment]
@joeperuzzi Also, it would be helpful if you can provide additional example log files for testing locally and expanding automated tests, and any documentation you have.

**Comment by chrisberkhout** [comment]
I now have the `Elastic_Integration_tychon-2.4.8.zip` file and will use that as the starting point. I see it has `sample_event.json` files for each of the 18 data streams, but no source files to use as input for pipeline or system tests.

For the next steps it would be great to get examples of the following files:
```
tychon_arp_info.json
tychon_browsercryptography_info.json
tychon_cmrs.json
tychon_coams_info.json
tychon_cpu_info.json
tychon_cve_info.json
tychon_epp_info.json
tychon_exposedservice_info.json
tychon_features_info.json
tychon_harddrive_info.json
tychon_hardware_info.json
tychon_hostcerts_info.json
tychon_host_info.json
tychon_listeningcerts_info.json
tychon_listeningcipher_info.json
tychon_networkadapter_info.json
tychon_softwareinventory_info.json
tychon_stig_info.json
tychon_volume_info.json
```

**Comment by chrisberkhout** [comment]
This is blocked until an upcoming meeting in which we will see a demonstration and discuss how to align the existing integration with our usual integration guidelines. Particular questions there include having non-ECS fields outside of a vendor prefix and inclusion of many Kibana objects we don't usually include in our integrations, such as index patterns and alert rules.
