### ISSUE TITLE
Update service integrations to package spec 3.0.2 to gain secrets validation

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#9237]
Thee service integrations should be upgraded to package spec `3.0.2` or later to gain the secrets validation added in `3.0.2`. The latest version of package spec as of writing is `3.0.3`, so going to this version is also an option.

The following integrations can go to `3.0.2` or later without issue:

- [x] barracuda #9390
- [x] barracuda_cloudgen_firewall #9390
- [x] box_events #9389
- [x] carbonblack_edr #9399
- [x] cribl #9399
- [x] cyberark_pta #9399
- [x] cyberarkpas #9399
- [x] darktrace #9402
- [x] fireeye #9402
- [x] infoblox_nios #9402
- [x] jamf_compliance_reporter #9402
- [x] keycloak #9402
- [x] mattermost #9403
- [x] netskope #9403
- [x] pulse_connect_secure #9403
- [x] santa #9403
- [x] symantec_endpoint #9403
- [x] thycotic_ss #9404
- [x] ti_abusech #9404
- [x] ti_util #9404
- [x] tines #9404
- [x] zscaler_zpa #9404

The following integrations encounter validation issues going to `3.0.1` or later:

- [x] amazon_security_lake #9516
- [x] crowdstrike #9536
- [x] google_scc #9392
- [x] google_workspace #9527
- [x] prisma_cloud #9517
- [x] proofpoint_tap #9518
- [x] tanium #9519
- [x] trend_micro_vision_one #9520
- [x] vectra_detect #9521
