### ISSUE TITLE
Move Security integrations to GA

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#961]
The majority of our security integrations are currently experimental and our goal is to move these integrations towards GA in 7.14 to ensure full support as users adopt them in production environments. 

**Priority Order** (based on Fleet telemetry)
- [x] Windows (PowerShell/Security/Sysmon) 
  - [x] HTTP system tests
    - [x] Windows package https://github.com/elastic/integrations/pull/1044
    - [x] System security https://github.com/elastic/integrations/pull/1069
  - [x] All edge processing in ingest pipelines
  - [x] `event.original` is optional
    - [x] Windows package https://github.com/elastic/integrations/pull/1122
    - [x] System security https://github.com/elastic/integrations/pull/990
  - [x] Bump version https://github.com/elastic/integrations/pull/1214
- [x] auditd
  - [x] All edge processing in ingest pipelines https://github.com/elastic/integrations/pull/989
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/989
  - [x] Bump version https://github.com/elastic/integrations/pull/1215
- [x] Suricata
  - [x] All edge processing in ingest pipelines
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/991
  - [x] Bump version https://github.com/elastic/integrations/pull/1216
- [x] Zeek
  - [x] HTTP system tests https://github.com/elastic/integrations/pull/1108
  - [x] All edge processing in ingest pipelines
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/992
  - [x] Bump version https://github.com/elastic/integrations/pull/1217
- [x] Netflow
  - [x] All edge processing in ingest pipelines https://github.com/elastic/integrations/pull/1006
  ~- [ ] `event.original` is optional~ not apply
  - [x] Bump version https://github.com/elastic/integrations/pull/1218
- [x] O365
  - [x] HTTP system tests https://github.com/elastic/integrations/pull/1119
  - [x] All edge processing in ingest pipelines https://github.com/elastic/integrations/pull/983
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/1117
  - [x] Bump version https://github.com/elastic/integrations/pull/1219

~- [ ] Cisco~
~- [x] All edge processing in ingest pipelines (missing RSA) https://github.com/elastic/integrations/pull/1073~
~- [x] `event.original` is optional https://github.com/elastic/integrations/pull/1073~
~- [ ] Bump version https://github.com/elastic/integrations/pull/1220~

- [x] Palo Alto
  - [x] All edge processing in ingest pipelines
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/1007
  - [x] Bump version https://github.com/elastic/integrations/pull/1221
- [x] Okta
  - [x] HTTP system tests https://github.com/elastic/integrations/pull/1034
  - [x] All edge processing in ingest pipelines
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/1009
  - [x] Bump version https://github.com/elastic/integrations/pull/1222
- [x] Fortinet
  - [x] All edge processing in ingest pipelines (missing RSA) https://github.com/elastic/integrations/pull/1075
  - [x] `event.original` is optional https://github.com/elastic/integrations/pull/1075
  - [x] Bump version https://github.com/elastic/integrations/pull/1223

### Other packages (non RSA) that meet all requirements to GA

**Partially (not all data streams) RSA packages**
- Juniper
- Sophos

**Non RSA packages**
- CEF
- Checkpoint
- Crowdstrike
- Cyberarkpas
- GCP
- Iptables
- Santa
- Google Workspace
- Osquery

---
 
**Requirements for moving a package to GA:**

- Any package with httpjson input requires:
  - Closed beats/integrations gap on httpjson system tests
  - ~~Persistent storage for registry data in Hosted Elastic Agent https://github.com/elastic/obs-dc-team/issues/517~~
- All packages require:
  - Edge processing moved to ingest node pipeline https://github.com/elastic/security-team/issues/791
  - event.original is optional https://github.com/elastic/integrations/issues/777
  - Bump version to >=1.x.x

**Comment by epixa** [comment]
I updated the description to add the additional must-have requirements we identified recently
