### ISSUE TITLE
Meta: Key updates planned to the corpus generator tool

### ISSUE THREAD

**Issue by shmsr** [elastic/integrations#9751]
### Introduction

The elastic-integration-corpus-generator-tool is a valuable resource for generating test corpus for testing & benchmarking. To improve its usability and functionality, we have identified several areas for enhancement in this issue.

### Notes

- Enum Support:
  - Currently, enum is only supported for the keyword type.
  - Extend enum support to other relevant types, such as the long type.
  - Use case: http-response-status-code of long type could benefit from enum support.
  - Implement support for weighted enum as proposed in [elastic/elastic-integration-corpus-generator-tool#130](https://github.com/elastic/elastic-integration-corpus-generator-tool/issues/130).

- Configuration Simplification:
  - Generating Schema B currently requires multiple config files.
  - Simplify the configuration by adding a types section to config.yml.
  - Allow either the types section or fields.yml, but not both. Raise a validation error if both are present to avoid ambiguity.
  - Update the package-spec to make fields.yml optional.
  - The goal is to provide a minimal configuration to start the corpus generator.

- Counter Type Enhancements:
  - Counter support was recently added to the tool.
  - Introduce a counter-reset feature for the counter type.
  - See [elastic/elastic-integration-corpus-generator-tool#124](https://github.com/elastic/elastic-integration-corpus-generator-tool/issues/124) for more details.

- Formatting Pattern Feature:
  - There have been requests to add helper methods like path and hostnames, but adding individual helpers is not sustainable.
  - Introduce a formatting_pattern feature to provide a more flexible and extensible solution.
  - See the discussion in [elastic/integrations#8781 (comment)](https://github.com/elastic/integrations/pull/8781#discussion_r1462991509) for more context.

- Clarification Needed:
  - Seek clarification on the discussion in [elastic/integrations#8781 (comment)](https://github.com/elastic/integrations/pull/8781#discussion_r1433869402).

Related PRs and Issues:
- [elastic/integrations#8781](https://github.com/elastic/integrations/pull/8781)
- [elastic/elastic-integration-corpus-generator-tool issues](https://github.com/elastic/elastic-integration-corpus-generator-tool/issues)

Notes are extracted from GitHub issues and the related PR linked. From the notes itself, some tasks have been created to get started with the enhancements for the tool.

### Tasks

- [ ]  Add `enum` support for all relevant types
- [ ]   Implement support for weighted `enum`
 - [ ]  Simplify configuration by making `fields.yml` optional and adding `types` field to `config.yml`
 - [ ]  Add counter-reset feature to the `counter` type
 - [ ]  Introduce `formatting_pattern` feature

Above mentioned tasks are
