### ISSUE TITLE
Traefik Integration Migrations

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#9821]
Currently the Traefik integrations is compatible and tested with the 1.6 version. This version is deprecated and it reached EOL. The integration isn't pulling the metrics for 2.x versions now.

### Reported Issues
- V2 Access Log Failure - https://github.com/elastic/integrations/issues/9117
- Ingest pipeline Failure(1.11.x) - https://github.com/elastic/integrations/issues/8886

### Removal of Metrics API support in V2
- Metrics API Deprecation - https://github.com/traefik/traefik/issues/7629

### Log Migration 
- The integration is not supporting the new log format introduced in 2.x version's because of the breaking change. 
- The support for new log format is in progress and you can find more details in this [PR](https://github.com/elastic/integrations/pull/9131).

### Metric Migration
- As the metrics collection is currently supported natively using the beats module. The /health API end point is not available in the 2.x version.
- The metrics collection can be performed using prometheus or StatsD in the recent version. Please find the supported backends listed [here](https://doc.traefik.io/traefik/observability/metrics/overview/#addinternals).
- Ideally we could use the prometheus endpoint to collect the metrics from Traefik.

```[tasklist]
### Migrations
- [ ] Migrate logging data stream to support 2.x version. https://github.com/elastic/integrations/pull/9131
- [ ] Disable the metrics collection tab and update documentation to have a mention about the only log is supported with this version.
- [ ] Make logging data stream to BETA.
- [ ] Add support for metrics collection using prometheus. https://github.com/elastic/integrations/issues/9820
```
