### ISSUE TITLE
[META][Kubernetes Integration] Kubernetes volume integration enhancements

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/integrations#9859]
A meta issue to group suggested enhancements  for Kubernetes volume integration

- [x] https://github.com/elastic/beats/issues/39523
- [x] https://github.com/elastic/beats/issues/39524
- [x] https://github.com/elastic/beats/issues/39525
