### ISSUE TITLE
[Meta] 7.14 Planned changes to all packages

### ISSUE THREAD

**Issue by P1llus** [elastic/integrations#994]
This issue is an overview of planned changes that affect all or most packages to prepare them for GA.

**List of tasks:**

- **Update ECS version to 1.10**
Each package should have an updated ECS version, even if no changes is needed for the specific package, the new fields added in 1.10 is:
_New fields:_
Datastream: https://github.com/elastic/ecs/blob/master/rfcs/text/0009-data_stream-fields.md
_Beta fields:_
Orchestrator: https://github.com/elastic/ecs/blob/master/rfcs/text/0012-orchestrator-field-set.md
_Experimental:_
Threat fields: https://github.com/elastic/ecs/blob/master/rfcs/text/0018-extend-threat-group-software.md

- **Make sure the package is synced with any changes done to its related module**
There might still be changes, hotfixes or enhancements added to modules which is not synced over.

- **Make sure all packages have pipeline test files.**
Currently not all packages have pipeline test files, this should be added to make sure it has more feature parity with how CI tests are done for pipelines in the beats repo.

- **Remove any edge processing that might still exist.**
All edge processing is removed from the security-integrations packges already, but there might be some smaller processors left to convert.

- **Implementation of "Preserve Raw Event" option for all packages.**
All packages should follow the principles discussed in an earlier issue: https://github.com/elastic/integrations/issues/777#issuecomment-794077231
Each package will have the following changes:

1. Move the original data from its source field (default is the `message` field), to `event.original`.
2. All ingest pipeline processors handling values stored in the `message` field, will instead handle the` event.original` field. This simplifies reindexing of data by a lot, 
3. Preserve raw event defaults to `off`.
4. Overwrite any existing setting if some packages might already handle event.original, with on/off by default.
5. A menu option is added to preserve raw events for each package:
```
    vars:
      - name: preserve_original_event
        required: true
        show_user: true
        title: Preserve original event
        description: Preserves a raw copy of the original event, added to the field event.original
        type: bool
        multi: false
        default: false

```
Which looks like this:
![image](https://user-images.githubusercontent.com/8027539/118470800-5265f600-b707-11eb-9223-06ff60ffd3aa.png)

**Comment by P1llus** [comment]
As discussed @masci these are the changes we would like to perform, in which we could always track cross-team.

**Comment by P1llus** [comment]
Packages to track:

apache
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

auditd
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

aws
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

azure
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

barracuda
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

bluecoat
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

cef
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

checkpoint
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

cisco
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

crowdstrike
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

cyberark
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

cylance
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

docker
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

f5
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

fortinet
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

gcp
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

google_workspace
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

haproxy
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

iis
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

imperva
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

infoblox
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

iptables
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

juniper
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

kafka
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

kubernetes
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

linux
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

microsoft
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

mongodb
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

mysql
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

nats
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

netflow
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

netscout
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

nginx
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

nginx_ingress_controller
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

o365
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

okta
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

panw
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

postgresql
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

prometheus
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

proofpoint
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

rabbitmq
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

radware
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

redis
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

santa
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

sonicwall
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

sophos
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

squid
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

stan
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

suricata
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

system
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

tomcat
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

traefik
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

windows
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

winlog
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

zeek
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

zookeper
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

zoom
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

zscaler
- [ ] Update ECS.
- [ ] Sync package if any module changes.
- [ ] Add pipeline test files
- [ ] Remove edge processing
- [ ] Implement Preserve Raw Event

**Comment by epixa** [comment]
I'm going to close this since 7.14 is out. Feel free to reopen/rename if there's still something to track here.
